### ISSUE TITLE
[DataCap Application] TF Securities

### ISSUE THREAD

**Issue by yangbaby6** [filecoin-project/filecoin-plus-large-datasets#1026]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: TF Securities
- Website / Social Media: https://www.tfzq.com/, https://space.bilibili.com/628573375
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100 TiB
- On-chain address for first allocation: f1w4afhkcbflh7zbckcwzvgqjt7flsug7rqwdrlvq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
TF Securities founded in 2000 and headquartered in Wuhan, is an up-and-coming 
brokerage with a registered capital of RMB 4.662 billion, has entered the main board
 listing counseling, cross-border financial services expert with securities as its core. 
Since its development, TF Securities has grown into a national comprehensive 
securities company with full license.
```

What is the primary source of funding for this project?
```
Company capital.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other stakeholders, by company itself.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Trading data, listed company reports (Quarterly/Semi-Annual/Annual Reports, Finacial Reports, Analysis Reports, etc), promotional videos.
```

Where was the data in this dataset sourced from?
```
Sourced from internet public data & company resources. 
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://1drv.ms/u/s!AlZIcmcLPGRQaXJjwiZeEUKywvU?e=U7DTO9
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, confirm.
```

What is the expected retrieval frequency for this data?
```
Quarterly.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We would like to store long enough, probably 3 to 5 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We plan to make deals in Asia, perhaps HongKong, Vietnam, or CN.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Better offline data transfer due to bandwidth limitation.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are looking for qualified SPs with stable services, we are still looking into it.
```

How will you be distributing deals across storage providers?
```
We need to store multiple copies of data, and we will make sure no SPs will store for over 30%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. 
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by yangbaby6** [comment]
> Can you explain your data composition? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

our data including historical market data archives, trading data, listed company public reports etc, 3 to 5 copies should be 
enough.
I am the staff from company, introduced by someone to try to use the ipfs/filecoin network.

we looking for reputable SPs through slack and contacted some SPs with node id f0116445, f010491, f01192325
f043929, f0133886, f082635.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1w4afhkcbflh7zbckcwzvgqjt7flsug7rqwdrlvq

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Hey @yangbaby6 , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
