### ISSUE TITLE
[DataCap Application] <Ergeng TV> - <Ergeng TV>

### ISSUE THREAD

**Issue by Jacob12345nn** [filecoin-project/filecoin-plus-large-datasets#1042]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Ergeng TV
- Website / Social Media:https://www.ergengtv.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1z2nibcfuvpkf4yzbbqcipn344gr6bod7pgqh6sq

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Ergeng TV, which was built up in 2015, is a well-known original short video content platform in China, and is building a blueprint for the future ecological development of the content field, and is striving towards the goal of an excellent Internet content platform. In past years, Ergeng Media has established a globalized, urbanized and vertical product matrix in more than 30 cities across the country and even overseas. Content brands such as life and more entertainment have been viewed by more than 30 billion people around the world, won more than 300 professional awards at home and abroad, such as Golden Rooster and Hundred Flowers, Golden Investment Awards, etc., and are well received by users, industries and professional institutions. Anyway, look forward to the future in Web3 and meet the challenge of service infrastructrure and needs from the users on video qualifty/data security, we are gladly embracing the change and transition from web2 to web3 to provide many angles of online-based service in a new way.
```

What is the primary source of funding for this project?
```
Own fund and business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
We are not only working with business partners, local video platforms, commercial brands, Ergeng Public Welfare has also cooperated with dozens of public welfare organizations such as China Foundation for Poverty Alleviation, WHO, WWF, Shanghai Charity Foundation and so on. The shooting topics involve rural education, disease relief, cultural protection, animal protection, targeted poverty alleviation, care for vulnerable groups, and star public welfare.
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data we want to store on filecoin are public internet dataset which can be shared with the public. They are publicly distributable video cuts and some original films.
```

Where was the data in this dataset sourced from?
```
Ergeng self-produced videos/films data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Bilibili Main Page: https://space.bilibili.com/19591909?spm_id_from=333.337.0.0#/                                                              
Douyin Main Page: https://www.douyin.com/user/MS4wLjABAAAAhCy1yQRUlEMisle7_431wpoiNAg4K25lO2-PyseubAM                                                              Youtube Channel: https://www.youtube.com/c/%E4%BA%8C%E6%9B%B4%E8%A7%86%E9%A2%91
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
We have started the public service, so it is retrieved frequently. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Expectedly 3 years and it might be extended afterwards.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Greater China，Southeast Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online and offline.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We plan to select the SPs with high storage needs and insightful suggestions.
```

How will you be distributing deals across storage providers?
```
Garrantee at least 2 copies per client, and then distribute quota and files fairly and  dynamically.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by Jacob12345nn** [comment]
Hi Team, any progress? Thanks

**Comment by Sunnyiscoming** [comment]
How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Jacob12345nn** [comment]
Hey Sunny

To answer your questions, please find my answers as below:
1.How many copies will you store? at least 2
2. what's the relationship between you and the organization? Partner in
terms of video diversity/operation.
3. Can you provide more detailed information about other storage provider? We
are reaching out to some local SPs since it is a long term activity and
ErgengTV has continous storage needs.We prefer the SPs with stable network
and speed.

Thanks



Sunnyiscoming ***@***.***> 于2022年11月30日周三 20:02写道：

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1z2nibcfuvpkf4yzbbqcipn344gr6bod7pgqh6sq

**Comment by Jacob12345nn** [comment]
hey team, please refer to my email confirmation as below. 
![#1042KYC](https://user-images.githubusercontent.com/105485758/210546505-6952f362-7ebe-4a71-b76c-ba2e57f736c0.png)

**Comment by cryptowhizzard** [comment]
Hi @Jacob12345nn 

Can you tell us if you are authorized on behalf of Ergeng TV to distribute their data? If so, can someone of this Ergeng TV confirm this?

**Comment by Jacob12345nn** [comment]
Hi there 

Yes, I do this job on behalf of ErgengTV.
There is an agreement signed off between two sides.

Thanks

**Comment by herrehesse** [comment]
@Jacob12345nn Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Jacob12345nn** [comment]
Hey Greetings

Quick reply to your questions

Project-based contact. Depends on customer’s needs.

As you can see on website, there is huge amount of data here, but we will start with specific categories first - original videos/films by working with some filmmakers of ErgengTV.
ErgengTV devotes itself to influence the world by making/sharing the videos recording meaningful and colorful life moments/memorable social focus and other aspects for humans .

We have prepared no less than 10G bandwidth and enough to deal with those data in question.

2-3 copies for each is in plan.

**Comment by herrehesse** [comment]
@Jacob12345nn Can you try and answer the above questions in detail please?

**Comment by cryptowhizzard** [comment]
Hi @Jacob12345nn 

This is very confusing to me.

I have taken a look on the website ( https://www.ergengtv.com/service/ ) and i see that the email addresses for this company are kefu@ergengtv.com / @ergengtv.com

Reading your application i see you try KYC from an QQ.Com address. This means that we cannot verify you and if you act on behalf of ergengtv.com

Can you send an email to filplus-app-review@fil.org with who you are as data preparer with your personal and company details? 
Also in this e-mail please include the documents that you are authorized on behalf of ergengtv.com?

**Comment by cryptowhizzard** [comment]
Any news here?

**Comment by Jacob12345nn** [comment]
Hey!
Sorry for the late reply due to the long vacation.
I'll prepare all the information and send them to the required email!

Thanks

CryptoWhizzard ***@***.***> 于2023年1月30日周一 23:43写道：

**Comment by cryptowhizzard** [comment]
HI @Jacob12345nn 

I did not receive anything until now.
