### ISSUE TITLE
[DataCap Application]  - <Lindsay>

### ISSUE THREAD

**Issue by Lindsay2012** [filecoin-project/filecoin-plus-large-datasets#1164]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Lindsay
- Website / Social Media:https://space.bilibili.com/520819684?from=search&seid=4326099354298808455  https://www.youtube.com/c/Lindsay%E8%AF%B4/videos
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f17dk5z7346pknamn4ugk6q7m6utawwjbirm2zbey

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
As the founder of Lindsay in Youtube and Bilibili and with the experience in investment banking/finance and education technology entrepreneurship in J.P. Morgan and Peking University & Columbia University, I devote myself into publicizing some business/finance/education techonology entrepreneurship knowledge and personal understanding for years. The way I do my job is knowledge talk show videos, which I hope can help others in some way or bring some fun. 
I also have my Startup Company - Offerbang, an online learning platform for job hunting among students abroad. During the knowledge sharing, I got in touch with Web3 concept and had strong interest in crypto and blockchain. Considering the upcoming future, I apply for LDN for my existing and future videos/courses. 
```

What is the primary source of funding for this project?
```
business income
```

What other projects/ecosystem stakeholders is this project associated with?
```
nope
```

## Use-case details

Describe the data being stored onto Filecoin
```
The dataset we want to store onto Filecoin are the videos/live tetecast I made and posted in YouTube/Bilibili
```

Where was the data in this dataset sourced from?
```
videos/courses created and edited by myself and my team.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://space.bilibili.com/520819684?from=search&seid=4326099354298808455  https://www.youtube.com/watch?v=pFRXGxwat_U https://www.youtube.com/watch?v=hDkCf4FIbfI https://www.youtube.com/watch?v=shDL1NNHCqw https://www.bilibili.com/video/BV1h34y1n7A3/?spm_id_from=333.999.0.0 https://www.youtube.com/watch?v=u7rAwl6OY9U https://www.youtube.com/watch?v=YdWP-wJh9jA
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
everyday
```

For how long do you plan to keep this dataset stored on Filecoin?
```
3-5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
globally
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
Prefer to consider the SPs with Network stability and fast retrieval
```

How will you be distributing deals across storage providers?
```
fairly
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f17dk5z7346pknamn4ugk6q7m6utawwjbirm2zbey

**Comment by Alex11801** [comment]
@Lindsay2012 I noticed that there are many videos about news and some people's daily life that containing so many people's faces. Can you explain the relationship between these kind of videos with your videos? Are there any copyright issues with your videos?

**Comment by Lindsay2012** [comment]
Hi Alex
Thanks for your question.

pleasure to clarify:

  1.  The copy law does not prohibit the use of other's works to create another story and perspectives. The key is wether the re-produced works have their own originality.
  2.  my works do not distort the original meaning of those works and use them for graceless purpose
  3.  The principal line is my narrative presentation and use some images for referrence and my team will also clarify all the similar resources come from the internet-to answer your concern of people's daily life. The current % is fine for self-produced media.

        So there is no copyright issue in my videos in conclusion.
        Anway thanks for your kind reminder. I might pay more attention on such issues.




  1.

________________________________
发件人: Alex11801 ***@***.***>
发送时间: 2023年1月3日 10:55
收件人: filecoin-project/filecoin-plus-large-datasets ***@***.***>
抄送: Lindsay2012 ***@***.***>; Mention ***@***.***>
主题: Re: [filecoin-project/filecoin-plus-large-datasets] [DataCap Application] - <Lindsay> (Issue #1164)


@Lindsay2012<https://github.com/Lindsay2012> I noticed that there are many videos about news and some people's daily life that containing so many people's faces. Can you explain the relationship between these kind of videos with your videos? Are there any copyright issues with your videos?

―

**Comment by Alex11801** [comment]
@Lindsay2012  Well I don't think I am totally convinced. Let's see whether other notaries are in support of this project.

**Comment by Lindsay2012** [comment]
Hi Alex, Thanks for your concern all the same.

**Comment by Lindsay2012** [comment]
To further clarify, I can guarantee there is no such issue in my videos . Looking at the similar things in the public vidoes globally, you will find more and most of them are workable (get rid of those with evil purposes). Absolutely, to clear the sensitive concern in a proper way, I might put some clear clarification in the future video editing to claim that all open sources from internet are for referrence. Look forward to joining this terrific project which can really help me fix the videos storage issue with IPFS.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by newwebgroup** [comment]
Client finds me through Slack
**About KYB/KYC**
1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？

The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates

2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
3. How large is your existing dataset? How much is the data growth per month?

**Comment by Lindsay2012** [comment]
> Client finds me through Slack **About KYB/KYC** 1：Could you send an email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) ？
> 
> The content should include the number of the LDN application. If possible, please attach copies of the business license and other valid certificates
> 
> 2：Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? 3. How large is your existing dataset? How much is the data growth per month?

Hi newwebgroup 
1 - have sent the email for KYC 
2 - there are 6-8 SPs in china now contacting with us.
3-We will try 1-2P first, normally 50-80T growth per month.

**Comment by herrehesse** [comment]
@Lindsay2012 

1. Thank you for the email, please try and answer the above questions also.
2. This is not allowed, data should be disbursed among multiple continents/regions and cities.
3. If you want to try 1-5P first please lower your 5P request to meet your request.

**Comment by Lindsay2012** [comment]
Hi herrehesse
Thanks for your long comments and extra questions/suggestions after my reply to another notary.
Actually I am writing.... to answer your long questions as below:

1)Could you demonstrate exactly how and to what extent customer contact occurred?
Not sure I have got your true meaning, but all the videos are produced and owned by my team.

2)Did the customer specify the amount of data involved in this relevant correspondence?
All the videos

3)Why does the customer in question want to use the Filecoin+ program?
I have learned blockchain and very interested in the concept of decentralization. Filecoin and IPFS were very famous in Chinese community but mostly it is for mining I think.

4)Here comes a project that claims to store valuable and public data in the world. So I gave a try.
Should this only be soley for acquiring datacap this is of course out of the question. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network.
I think our videos are useful for everyone who are interested in finance and economy.


5)Why is the customer data considered Filecoin+ eligible?
(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)
Because of the long-term and the increasing storage, I applied for the LDN.
Sorry I have no idea about those projects.
Anyway, I think my application is also qualified here.

6)Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation? 
Firstly start from China and I am talking with some SPs who are interested in and also have stable network and fast retrieval

7)Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?

8)Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
Not sure I have understood you here. We plan to store 2 copies, is that an abuse - I don’t think so?

9)Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.
Understood.
But also hope the entire community and notaries can be more active and positive here to support the applicants and attendees in this project. That is the best way to make Fil community thrive.

10)Regions issue
The region of China only comes first and then US is taken into consideration. The two locations are more familiar to me.
Do you have any other recommendations in different regions?

11)Allocation issue
1-2P with 2 copies. That is the original plan.
Is it better to apply for 4P anyway?

Thanks

**Comment by herrehesse** [comment]
Hello Lins

1. Is your team a storage provider or a content creation producer?

2. Your data request is for 1-2P of video data, which is converted 4.5GB per hour of HD video that comes to 444 thousand hours of footage. About 50 years! Looking at the youtube channel I see 73 uploads available between 10-30 minutes, which amounts to less than 24 hours.

Even in RAW 4K it is 110GB per hour which amounts to 18.5 thousand hours of footage. Please explain why you requested so much datacap.

3. You are not answering the question. I asked why Filecoin+ not why Filecoin. This program is meant to store humanity's most important and useful data. If this is purely meant for "mining" then your application should not be approved.

4. Agreed. Up for debate due to the nature of the content, but fair point.

5. Stated  at4.

6. If there is no plan in place and you are just starting to talk to SP's I would suggest you start experimenting with a lower datacap request like 100TiB. 

7. Can you answer?

8. I would suggest to store a minimum of 6 copies of the data to keep a proper redundancy.

9. Fully agreed with you.

10. You should have a minimum of multiple continents and cities to be eligible for Filecoin+. If you only want to store two copies in mainland China then please contact FIL-E or send regular deals to storage providers.

11. It would be better to start with a lower amount and doing a bit of testing before you start with 5P. Also, you should explain the size calculated at #2.

**Comment by Lindsay2012** [comment]
Hello again :)
Thanks for your further questions and information.

1.Is your team a storage provider or a content creation producer?
   Content producer

2.Your data request is for 1-2P of video data, which is converted 4.5GB per hour of HD video that comes to 444 thousand hours of footage. About 50 years! Looking at the youtube channel I see 73 uploads available between 10-30 minutes, which amounts to less than 24 hours.
Even in RAW 4K it is 110GB per hour which amounts to 18.5 thousand hours of footage. Please explain why you requested so much datacap.
Thanks for the detailed calculation.
I thought all the videos in hand including posted and planned ones can be considered, and 5P is a common application in community. Sorry that I might misunderstand rules in this part. Appreciate your information!

3.You are not answering the question. I asked why Filecoin+ not why Filecoin. This program is meant to store humanity's most important and useful data. If this is purely meant for "mining" then your application should not be approved.
  Hey! I just stated a fact that Filecoin mining was famous(not sure now) in CH community, right? How come my purpose is for mining.....I don’t think anyone in this community learn little about mining or tokens. You just asked me why choose Filecoin+, and I threw some honest answers here how I learned about Filecoin - it is where everything got started.
  Surely, I should answer directly why filecoin+, but actually I do the application by myself, I am not a native block chain or tech person here.
  Have to admit it was recommended by some of my friends in our industry, who has in block chain industry for many years! And they let me know there is a project to develop/optimize storage tech and ecosystem(in my POV).
Anyway thanks for your effort to broadcast the value of Filecoin+, which help some new hands like me to merge into the community fast.

7.Can you answer?
  I think no less than 10G is better.

8.I would suggest to store a minimum of 6 copies of the data to keep a proper redundancy.
  Thanks for the advice

**Comment by lvschouwen** [comment]
@Lindsay2012 
Can you provide a list of MinerIDs for the SPs you plan to store this on?

**Comment by cryptowhizzard** [comment]
Hi @Lindsay2012 

Thanks for cooperating with us to get the LDN. I need to perform some KYC and due diligence in order to decide if i can support your LDN application. Can you please fill out this form:

https://form.jotform.com/230232885049356

I will proces it asap.

**Comment by Lindsay2012** [comment]
@cryptowhizzard 
 
Hi Cryptowhizzard 
I have submitted the form.
If anything unclear,pls. Let me know.
Thanks

**Comment by cryptowhizzard** [comment]
Hi @Lindsay2012 

Thanks, it is received. I replied with the link to Veriff to finish the process and a second email with some final questions.

**Comment by Lindsay2012** [comment]
Hi@cryptowhizzard 
First of all.
Thanks for the elaborate information as below!
We totally understand the rules in this community and project, and will keep that in mind as always.
We also appreciate your kind reminder on the CID sharing problem and we have reached out to some other SPs for further communication to execute the project exactly within the rules.
You can refer to the miner IDs:
f01402814
f01854772
f0240185
f0143858
f01853077
f02003005
f01972110
f02017390
f01786736
f0717969
f01943959

Thanks for your support.
If no further question on your last concern, I will start asking for a signature from the community.

**Comment by cryptowhizzard** [comment]
> 

There are still SP's with bad reputation in this list. Please provide me with a list + contact information ( if you prefer it may be done per e-mail ).

**Comment by Lindsay2012** [comment]
@cryptowhizzard 

I just talked with those SPs for initial touching and cooperation communication.
From my side, they all promise to abide by the rules because I mentioned the issue here.

Is that a rule now to disclose SPs’ information which I think it might be privacy?
All that you concern can be checked by the community here during data processing, right?

As a customer, I am not sure if this is right to disclose information of others.

Sorry that I am a bit confused.

**Comment by cryptowhizzard** [comment]
Hi @Lindsay2012 

No problem, i appreciate that we can share thoughts.

The problem is not that some of the SP promise you that they abide by the rules. We know they promise everything, even selling their mother in law if needed :) It really has zero value to me because i want to help you and the FIL ecosystem / community to improve.

What i want to accomplish is that:

- You have a administrative record for the people you do business with and where you are storing data. In case anything goes wrong you and i should be able to reach them just as well as i do.

- You are aware that some of your Sp's are bad (in your list). Doing business with them might end up with fake data being stored and your LDN getting blocked and your reputation down the drain. They don't care!.................

- Make sure that you start with SP's owning a good reputation trackrecord and who are honest.

Giving you a head start with this you have the biggest chance that in the future you can contribute in a valuable way to the ecosystem making things better for us al. The frustration of things going wrong when you have no idea on what happened is not where you want to be in a few weeks. That's what i am here for and what i am doing.

**Comment by Lindsay2012** [comment]
Hi @cryptowhizzard 

I will keep your kind suggestions in mind!
Thanks for your support.

**Comment by Tom-OriginStorage** [comment]
applicant contact me
@Lindsay2012 
1:Have you emailed to filplus-app-review@fil.org yet?
2:In which areas are you planning to package? please show your SP ID;

**Comment by Lindsay2012** [comment]
@Tom-OriginStorage 
1. I have sent the email to official address in Jan.
2.We plan to store our data in different locations per rules like US, Europe, Asia. SP ids have been required before and you can refer to above information I answered. 

Thanks!
