### ISSUE TITLE
[DataCap Application] KUAYUE-EXPRESS

### ISSUE THREAD

**Issue by AFFKKK** [filecoin-project/filecoin-plus-large-datasets#1389]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: KUAYUE-EXPRESS
- Website / Social Media: https://www.ky-express.com/  https://weibo.com/u/3072931447
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1kxkrhkjojsuuw5vtphd7yc3lbhwonr5btn5hwai

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
KUAYUE-EXPRESS Group Co., Ltd. was founded in 2007. It has honorary titles such as "National AAAAA-level Logistics Enterprise", "National High-tech Enterprise", "Top 30 Excellent Brands in China's Logistics Industry", "Famous Brand in China's E-commerce Logistics Industry", and "Guangdong Province Integrity Logistics Enterprise".
```

What is the primary source of funding for this project?
```
Company profit
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
videos of local branches & logistics sorting centers; promotional videos uploaded on various platforms
```

Where was the data in this dataset sourced from?
```
All the data are generated by our own company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes.
https://drive.google.com/drive/folders/1SF64iO9nRZLPfVwrK80lMyYs4lFLtlkF?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
every half a year. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
About 1 to 2 years.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We can store data globally as long as the storage providers able to provide secure and stable storage space.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
For domestic storage providers we wil prefer offline transfer, however for overseas storage providers we will transfer online.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We would like to find SPs with high reputation.
```

How will you be distributing deals across storage providers?
```
We would like to have multiple storage providers involved in and distribute with fairness. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, I do
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1kxkrhkjojsuuw5vtphd7yc3lbhwonr5btn5hwai

**Comment by zizi-defil** [comment]
Can you email filplus-app-review@fil.org using your official domain name to confirm your identity? 
Email name should contain Issue ID #1389.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
