### ISSUE TITLE
[DataCap Application] <BEIJING YuTian Technology Co., Ltd.> - <Substation battery monitoring project>

### ISSUE THREAD

**Issue by cindy19875** [filecoin-project/filecoin-plus-large-datasets#1415]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: BEIJING YuTian Technology Co., Ltd.
- Website / Social Media:http://www.yutiantech.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3.5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ryyncangs2ljcx7na3yn6xsqkawvj5gfvjxopta

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
DC standby power supply is widely used in communication, finance, power, transportation and other industries to provide "uninterrupted" power supply guarantee for data centers and communication equipment. In the backup power supply scheme, the battery pack is a very important component, and the battery status is the basis for the normal operation of the backup power supply. However, from the current situation of the industry, for the lack of refined management of batteries, there are unknown risks in the backup power supply scheme.

Under the general environment of pursuing safe production, if the production safety departments at all levels attach importance to the maintenance of the battery from the perspective of ensuring the operation quality, production safety and property safety, and equip the battery online monitoring system, it is no longer a consumer expenditure, but a long-term investment in safety.
```

What is the primary source of funding for this project?
```
Project Income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
The data are mainly satellite monitoring data
```

Where was the data in this dataset sourced from?
```
Data generated by the Company in conducting its business.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Link：https://www.aliyundrive.com/s/jsbzkg7AJRh 
Extraction code：none 
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes,it is
```

What is the expected retrieval frequency for this data?
```
Yearly
```

For how long do you plan to keep this dataset stored on Filecoin?
```
5 years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
HTTP or FTP Server
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are currently discussing capabilities and performing due diligence with several SPs. We chose these based on their current storage capacity, compute capabilities, enterprise-grade DCs and bandwidth and their familiarity and passion for open source software.
```

How will you be distributing deals across storage providers?
```
We will distribute them equally to the high-quality storage providers that pass our audit.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes.
```

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Your application is for 5PB of datacap. Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
