### ISSUE TITLE
[DataCap Application] <Hilamg> - <Encrypted instant messaging software>

### ISSUE THREAD

**Issue by yijuqingshi** [filecoin-project/filecoin-plus-large-datasets#1420]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Hilamg
- Website / Social Media:https://hilamg.com
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1mkhrvixl4pejrmwddwrekxsmpzc2e6753thwxfa

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Hilamg is an encrypted communication tool that protects your privacy and security.

From the first day of creating Hilamg, our mission is to help you create a safe communication environment with your friends. We don't expect to see users' important information leaked, personal data exploited, etc. Because you share your most personal moments on Hilamg, we built technologies like end-to-end encryption into the app. With end-to-end encryption protection, your messages, photos, videos, voice messages, documents, buzz, and calls are protected from falling into the wrong hands.

We don't read or listen to any of your chats
We do not and cannot sell your personal data
More than just end-to-end encryption
Hilamg does not provide any services other than secure encrypted chat services; there is no transfer business, please pay attention to the safety of your funds, and operate carefully to prevent being deceived.

Hilamg is an end-to-end encrypted instant messaging software, and its client is a free and open source software. Users can exchange encrypted and self-destructing messages with each other (similar to "burn after reading"), send photos, videos and all types of files. Officially provide mobile version (Android, iOS), desktop version/Mac version (under development) and other platform clients; at the same time, the official open application program interface (API), so there are many third-party clients to choose from[2] , many of which have built-in Chinese.
Software name: Hilamg
Software language: Simplified Chinese, English
Software platform: Android, IOS
Software version: v 1.0.12
Public beta launch time: September 25, 2020
Software size: 30MB
Software type: instant messaging software
Founder: Mag

Introduction
Hilamg is a cross-platform instant messaging software, users can exchange encrypted and self-destructing messages, send photos, videos and other types of files.

development path

The software was founded in 2019 and has released two versions. As early as 2020, the 1.0 social version of Hilamg has received widespread attention, with a cumulative user base of around 400,000. An iterative version will be launched in 2021, and the function concept will be completely new.

Technical introduction

Hilamg uses a communication protocol based on MTProto, which can transmit at high speed in a weak network environment, and ensure the safety and reliability of data and reach users in a timely manner. Any data sent and received through Hilamg (including but not limited to voice, phone calls, and document files, etc.) is encrypted end-to-end, and only the two parties in the conversation or group friends have access to it, and it is impossible to be read by telecom operators, network administrators or others. Third-party decryption inspection. Technically eliminate the risk of privacy leakage.

```

What is the primary source of funding for this project?
```
Company's own funds.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Data include video, images, audio, text, voice, and files. 
```

Where was the data in this dataset sourced from?
```
Company data.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/15MQ8nAI9xx4V5GO0Kc89NxlwMd7UaCUH/view?usp=share_link
https://drive.google.com/file/d/1hRUl_S78Xm_cH-6FDUrz7_uxwGAx_tpN/view?usp=share_link
https://drive.google.com/file/d/1Mx4iayrgG3t20v1tyUvU0KPy9-5aImQn/view?usp=share_link
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm.
```

What is the expected retrieval frequency for this data?
```
Our data has been backup, and the frequency of retrieval of retrieval according to customer needs. 
```

For how long do you plan to keep this dataset stored on Filecoin?
```
We hope to store long -term storage, especially some important file data.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia,China. 
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
online and offline.

```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
1. We plan to choose the storage supply of multiple Filecoin storage experience to ensure long -term storage.
2. We will choose storage providers according to the functions of the storage provider, credibility, integrity and response speed, and scale. 
```

How will you be distributing deals across storage providers?
```
We will allocate average. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we have enough funds to trade.
```

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 3PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1mkhrvixl4pejrmwddwrekxsmpzc2e6753thwxfa

**Comment by NDLABS-OFFICE** [comment]
You should send a confirmation email to [filplus-app-review@fil.org](mailto:filplus-app-review@fil.org) using the email address of your company domain. And @Sunnyiscoming  please help verify and confirm.

**Comment by yijuqingshi** [comment]
I have replied. Please confirm it
![微信图片_20230104184457](https://user-images.githubusercontent.com/24369754/210538933-54c059a7-1811-4bc4-b6c8-dae9014972da.jpg)

**Comment by cryptowhizzard** [comment]
Hello @yijuqingshi 

Happy to see you use Filecoin. Can you tell us your role in the company? Are you an employee of Hilamg?

What can you tell us about the data that you guys want to store on Filecoin. What is the size of the set and how many times do you want to distribute it to SP's?

I see a few video's in Google drive. How large is the total set of video's and what do they contain?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by yijuqingshi** [comment]
Customer data is stored in the cold data of encrypted user communication data.  When the user calls to check the history, it will contact the data stored in filcoin through the platform.
The amount of communication data stored by the customer is at least 3Pib.
Customers use filecoin because filcoin network storage is cheaper, more secure, faster, and ideal for storing cold data that has not been used for a long time.
Customer data comes from user communications, which are increasing every day and need to be saved.  For data half a year ago, it is suitable to be compressed and encrypted and stored on the filcoin network.
The data will be packaged and encrypted by the customer and transmitted through the storage provider's interface, which will then upload it to the filcoin network.
We have communicated well, and the storage provider's network service test is no problem, both sides can prove each other.
The problem of data leakage can be solved by zero-knowledge proof technology in the later period.

**Comment by herrehesse** [comment]
@yijuqingshi Thank you so much for your response.

1. Encrypted customer data is not allowed on Filecoin+. The FIL-E program was created for this purpose.

We understand that the customer wants to use Filecoin as storage because of its advantageous features, however, the question is why does the customer relevantly want to use the Filecoin+ program? As far as I can read, the data simply does not satisfy.

2. The details regarding the download, processing and distribution are very vague. Would you elaborate on this a bit more please?

I look forward to your answers.

Translated with www.DeepL.com/Translator (free version)

**Comment by yijuqingshi** [comment]
Requesting valid data allows for better and faster storage of customer data. Miners will also find me to store data for me on their own initiative, which saves a lot of hassle.

The data can be downloaded by storing the data on a hard drive and providing it to the miner by mail, which saves time and does not require a network. Then the hard disk is plugged in and the data is transferred through the intranet for data processing. The distribution of data is mainly done by miners who take the initiative to contact us wanting to store data for us, and after the evaluation of the miners' storage devices is completed, a partnership is established

**Comment by herrehesse** [comment]
Hello @yijuqingshi - Thank you again for your quick response. We love to help you onboard new customers onto the Filecoin network, but we must follow the rules for the Filecoin+ program. If this is business data then we must move the application to FIL-E.

As seen in your responses we are talking about customer data for cold storage, that is a perfect use-case for Filecoin, just not for this Filecoin+ program. You should be looking at FIL-E (Filecoin enterprise) to serve your customers. The Filecoin+ LDN applications are meant for useful public large scale datasets. Preserving human's most important information. 

Distribution is clear.

**Comment by yijuqingshi** [comment]
Our main data can be disclosed. At present, the applied storage is 3Pib, but with the increase of customers and the passage of time, the volume will be larger. I think our data is in line with filcoin+

**Comment by herrehesse** [comment]
The storing of client files such as video, images, audio, text and voice is an awesome application for Filecoin, however the application should be done on FIL-E not Filecoin+.

Do you need assistance with that program from me? Love to help.

**Comment by yijuqingshi** [comment]
What I might say is too vague. Some of our data is publicly available and can be called by people using our software. It 's completely open data and we store it. These data are often referred to as, and are public data that satisfy the filcoin+ condition.

**Comment by cryptowhizzard** [comment]
That is indeed vague. Let me clarify:

You intend to store (some) data that is only accessible through your software. Right?

**Comment by cryptowhizzard** [comment]
Any news here?
