### ISSUE TITLE
[DataCap Application] Fujian Rotation Technology Co., Ltd.

### ISSUE THREAD

**Issue by minecryptoHub** [filecoin-project/filecoin-plus-large-datasets#1429]
### Data Owner Name

Fujian Rotation Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

https://www.minecrypto.cn/

### Social Media

```text
https://www.minecrypto.cn/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f13ft4pxztumga6bl5jtvrm24l35t3qw5p25cbwza

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Founded in May 2021, our team now has 50 staff members. The company mainly operates a video content creation platform, which mainly provides copyright commercial operation services, content promotion and distribution services, content distribution services, AI intelligent advertising services, etc., and is committed to providing users with a simple, fast, efficient and high-value open content platform.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Every day, our team members do secondary creation on film and television resources, so we need a lot of storage space to store video data, which is a very large data set. For example, original files of film and television resources, draft video files that are being created, short video files that have been created, and so on. So we need a lot of storage.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1gZBNiViJtwH2taFqLNZHNCJ6UO7l-zKP?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Big data exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://drive.google.com/drive/folders/1gZBNiViJtwH2taFqLNZHNCJ6UO7l-zKP?usp=sharing
![image](https://user-images.githubusercontent.com/105098820/207358494-1c387864-5ad5-444c-910e-17c430d08b90.png)
As you said, you will store original files of film as public data on the Filecoin network.  Do you have the authorization of the data owner? Many films have commercial value, they are not suitable for storing as public data. If you have the authorization to store them, please provide the relative materials.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by minecryptoHub** [comment]
I'm sorry for not replying to your message in time. Because I had COVID-19 a few days ago. To answer your question, we own the copyright of the videos, but we don't want to store them publicly, which may be my mistake.
In addition, in addition to film and television resources, we also have a large number of original videos, which are shot by ourselves, including original videos and edited finished products. These videos are not copyrighted and we are fully willing to store them publicly. This is our sample video: https://drive.google.com/drive/folders/1HwpY7tefOqExT-YIOmJWolH4vaZ8K_wy?usp=sharing

**Comment by minecryptoHub** [comment]
@Sunnyiscoming

**Comment by cryptowhizzard** [comment]
Hello,

I am confused. What does a domain name minecrypto ( Cryptocurrency mining ) have to do with cooking video's who are online in the Google drive? Are these video's created by you and do you have the copyright for it because it doesn't look this way.

**Comment by cryptowhizzard** [comment]
To avoid confusion here ... this is what i mean

https://user-images.githubusercontent.com/36404435/210545791-701122a9-62d1-40b6-805e-8654522a1216.mp4

**Comment by minecryptoHub** [comment]
Hello, yes, we have many types of video material, including life, pets, food, scenery, music and so on. The video source files are mainly the videos we shoot independently and a small part of the free videos on the Internet. We do not use or publicly store videos that are in dispute.
In addition to your doubts about the domain name, we are a start-up team. This domain name started to be used as the company's official website domain name in 2020. Although the business has changed during this period (now we are a team specializing in video editing), we have been using this domain name and continue to use it till now.

**Comment by minecryptoHub** [comment]
Our need for storage is real, and we sincerely hope that filecoin will provide us with storage capacity to meet our actual needs.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by minecryptoHub** [comment]
@cryptowhizzard    Hello, what do I need to do to move to the next stage of the process?

In addition, this issue has been closed, is it necessary to reopen it?

**Comment by minecryptoHub** [comment]
@herrehesse ，Hello, I don't think these data belong to business data. We have uploaded the finished video to different we-media platforms. On the filecoin network, I store backups of videos in case they are later used for other purposes (such as re-editing or distribution to other platforms).

**Comment by herrehesse** [comment]
@minecryptoHub My apologies, but the content is not valid to grant datacap to.

Can I help you with a FIL-E application or with doing regular deals so you can make use of the Filecoin network for your data storage needs?

**Comment by minecryptoHub** [comment]
Hello, do I have to use FIL-E to store public data?
I haven't learned the detailed rules of FIL-E yet. Does it meet my storage requirements? What are the obvious differences from fil+? It would be great if I had a document to learn from!

**Comment by minecryptoHub** [comment]
@cryptowhizzard @raghavrmadya @Kevin-FF-USA 
Can you give me your opinion? I would really appreciate it!

**Comment by herrehesse** [comment]
@kevzak Can you please advise the above client @minecryptoHub further on the FIL-E front, his data needs are aligned with the program.

**Comment by kevzak** [comment]
@minecryptoHub if your data is private, please refer to the our E-Fil pilot [here](https://efilplus.super.site/) or feel free to reach out to me on slack @KevinZ to discuss more

**Comment by minecryptoHub** [comment]
@kevzak It is also acceptable to store data publicly

**Comment by minecryptoHub** [comment]
@cryptowhizzard     Hello, do you have any new progress? We've waited a long time. What do we need to do?

**Comment by cryptowhizzard** [comment]
Hi @minecryptoHub 

Yes. I would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it. 

Please note, i do need the SP's and their contact information otherwise i cannot do due diligence.

**Comment by cryptowhizzard** [comment]
Hello @minecryptoHub 

Thanks for completing KYC.

There are 2 fields that you left open on the KYC form. I need that information before i can sign on your application.

You indicated that you are the data preparer and owner of the dataset. Can you confirm you don't have any stake in SP's you are going to send this data to?  As stated in the form I am allowing 1 replica of the set to be stored on your own miners. That's the reason i ask.

Second:

As the form states _> RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed.
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.

Can you provide me with the Sp's and their contact information? 

Thanks!
