### ISSUE TITLE
[DataCap Application] Wuxi Xinjie Electric - Industrial Automation Data

### ISSUE THREAD

**Issue by CreamPiPi** [filecoin-project/filecoin-plus-large-datasets#1431]
### Data Owner Name

Wuxi Xinjie Electric Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.xinje.com

### Social Media

```text
http://www.xinje.com/xj_about/index.html
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

450TiB

### On-chain address for first allocation

f17yb53dklk3ceqpru42ujan2bwi4ii2zkvqtcrgi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Wuxi Xinjie Electric Co., Ltd. is a well-known enterprise focusing on the R & D and application of industrial automation products.
​
The company has programmable controller (PLC) and man-machine interface (HMI), servo control system, variable frequency drive and other core products.The company also closely serves end customers through cutting-edge products such as intelligent machine vision systems, teaching manipulator and customizes more competitive industry segmentation solutions for equipment manufacturing companies.
​
Xinjie Electric has set up 40 offices and 170 distributors in China, covering all parts of the country.Overseas, it has one subsidiary and 20 agents, covering Europe, America, Southeast Asia, the Middle East and Africa. It was successfully listed on the main board of Shanghai Stock Exchange in December 2016 (Stock Code: 603416).
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data we want to store on Filecoin is a large amount of industrial automation data output from our company's R&D center, laboratories and training base, including PLC data, man-machine interface history, generated data, drive system data and intelligent device data.The above data is mainly in the form of pictures, videos, documents, etc. These data will not cause disputes. 
The following sample provides a link to the documentation.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, graphsplit

### Please share a sample of the data

```text
https://xinje.com/xj_service/xj_xzzx.html
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by Sunnyiscoming** [comment]
Close for no reply.

**Comment by CreamPiPi** [comment]
Hi, @Sunnyiscoming.

Sorry for the late reply.
Our team just got recovered from horrible COVID-19 and has been back from a short holiday.

About the above question, there are nearly 1.5 PiB data in our IDC.
And we believe Filecoin could be the best choice to store them in a decentralized way. Safer and cheaper.
![0837569C-E705-4BB6-B8E1-B4588C14DFCC](https://user-images.githubusercontent.com/95162312/210718787-61602ddf-6e1a-472f-84f0-70600a2f640d.png)

Please help us reopen this application, thanks.

**Comment by herrehesse** [comment]
**Dear @CreamPiPi - Hopefully you and your team recovered from the COVID outbreak. Wish you good health.**

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 450TiB 

#### Client address
> f17yb53dklk3ceqpru42ujan2bwi4ii2zkvqtcrgi

**Comment by CreamPiPi** [comment]
Dear Notaries!

Please review this application!
We need two sig to start this project.

Thanks!

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by mjroddy** [comment]
This is not suited to FIL+. Effectively private company data. I do not believe It is helping accelerate the usefulness of filecoin by storing

5 PiB is too large for use case

**Comment by CreamPiPi** [comment]
Would any Notaries please take a look at this application?
We've been waiting for a long time.
Thanks!

**Comment by Joss-Hua** [comment]
@CreamPiPi  Before starting everything, we need to focus on KYC/KYB. Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? The email name should include the issue id #1431. Then @Sunnyiscoming please help verify and confirm.
If you have more KYC data, please send them to @Joss-Venus on Slack.

**Comment by Joss-Hua** [comment]
The client contacted me on Slack, and currently, it appears that this LDN is a continuation of #174 from the same applicant. I have reviewed the relevant KYC materials. Willing to help this LDN get on track, but please maintain reasonable dispersion and attention.

**Comment by Joss-Hua** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecmxu3gml2hldl5a5bq4pim6igngak56mqin3zgv52zamnhqt2klc 
#### Address 
> f17yb53dklk3ceqpru42ujan2bwi4ii2zkvqtcrgi
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1tfg54zzscugttejv336vivknmsnzzmyudp3t7wi
#### Id
> 61ecf6c5-47df-41c7-acb9-c293fabc287b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecmxu3gml2hldl5a5bq4pim6igngak56mqin3zgv52zamnhqt2klc

**Comment by laurarenpanda** [comment]
Had chatted with this Client via Slack.
I noticed that this application has been waiting for a long time, so I'd like to support this round.

**Comment by laurarenpanda** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaixovzibmkz7psxyzrl7m7ibo2ftezm53ofkcggpa47xssv6l3vo 
#### Address 
> f17yb53dklk3ceqpru42ujan2bwi4ii2zkvqtcrgi
#### Datacap Allocated
> 225.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 61ecf6c5-47df-41c7-acb9-c293fabc287b
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaixovzibmkz7psxyzrl7m7ibo2ftezm53ofkcggpa47xssv6l3vo

**Comment by laurarenpanda** [comment]
checker:manualTrigger

**Comment by laurarenpanda** [comment]
Hi, @CreamPiPi.
Any comments about the previous report or future allocation plan?

**Comment by steven004** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
To much duplicate data. Also SP's without IP address set.

Please fix this before signing.

**Comment by steven004** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedg6nylzyfjhqupoc3h47rzntrrqicmpcfafyckc3ry4w7cjwjz3w 
#### Address 
> f17yb53dklk3ceqpru42ujan2bwi4ii2zkvqtcrgi
#### Datacap Allocated
> 900.00TiB
#### Signer Address
> f1ozt3gaqbnzfic6f2zsj4vppncws36ik5nqofhka
#### Id
> e567212b-12c8-4095-80bd-638d56084de1
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedg6nylzyfjhqupoc3h47rzntrrqicmpcfafyckc3ry4w7cjwjz3w

**Comment by cryptowhizzard** [comment]
> ## Request Proposed
> Your Datacap Allocation Request has been proposed by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzacedg6nylzyfjhqupoc3h47rzntrrqicmpcfafyckc3ry4w7cjwjz3w
> 
> #### Address
> > f17yb53dklk3ceqpru42ujan2bwi4ii2zkvqtcrgi
> 
> #### Datacap Allocated
> > 900.00TiB
> 
> #### Signer Address
> > f1ozt3gaqbnzfic6f2zsj4vppncws36ik5nqofhka
> 
> #### Id
> > e567212b-12c8-4095-80bd-638d56084de1
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedg6nylzyfjhqupoc3h47rzntrrqicmpcfafyckc3ry4w7cjwjz3w

why are you signing

**Comment by cryptowhizzard** [comment]
@steven004 

I will make a dispute about this one.

**Comment by steven004** [comment]
Aha, @cryptowhizzard , sorry just see you message. 
The data is distributed well in 3 nodes, that is what I saw. 

One SP ip address bunding need to be fixed. @CreamPiPi , please inform your storage provider to fix this.

**Comment by cryptowhizzard** [comment]
> Aha, @cryptowhizzard , sorry just see you message. The data is distributed well in 3 nodes, that is what I saw.
> 
> One SP ip address bunding need to be fixed. @CreamPiPi , please inform your storage provider to fix this.

There is duplicate data ( high rates ) that are sealed here. Also there are SP's without IP adres set on chain.
Please revoke your signature until this is fixed.

**Comment by CreamPiPi** [comment]
Please keep this application open.

**Comment by CreamPiPi** [comment]
Keep this application open please

**Comment by CreamPiPi** [comment]
Keep this application open, Thanks~

**Comment by cryptowhizzard** [comment]
Dear CreamPiPi,

As notary I am doing due diligence on your LDN. I could not get retrieval to work. Can you please upload the car file of CID  ?

You can use our upload system at http://send.datasetcreators.com. Please select 7 days for the system to keep the file and post the link you received here so I (and other notaries) can download your content.

**Comment by CreamPiPi** [comment]
Please keep this application open. Thanks!

**Comment by CreamPiPi** [comment]
Please keep this application open. Thanks!
