### ISSUE TITLE
[DataCap Application] StarRiver Group 

### ISSUE THREAD

**Issue by Potel64** [filecoin-project/filecoin-plus-large-datasets#1435]
### Data Owner Name

StarRiver Group 

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

http://www.star-river.com/

### Social Media

```text
https://weibo.com/u/1969582850
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f1z4c3lz62cj6ttz75n5y35uldc6plhzgwcdjn6ma

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Star River Group beling at the forefront of reform and opening up, under the care of the Party and government, Star River has gradually developed into a conglomerate with a number of business maps, including city operation, hotel, property management, manufacturing, education, commerce and investment. The Group has nearly 100 branches (subsidiaries) and nearly 10000 employees. Focusing on quality and adhering to quality, star river group has become a benchmark of high-quality properties in china.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Promotion videos, design pictures, design documents.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://1drv.ms/u/s!AukgXeO7_gzEbocrT4NQF3ng7XY?e=9TdKIy
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://www.chateaustarriver.com/ This is the official website of StarRiver Hotel.
http://www.star-river.com/ is recorded by Guangzhou Hongfu Real Estate Co. LTD. Can you explain about that?
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by Potel64** [comment]
> https://1drv.ms/u/s!AukgXeO7_gzEbocrT4NQF3ng7XY?e=9TdKIy

StarRiver Hotel as one part of our group.
![image](https://user-images.githubusercontent.com/114043605/207543151-950d0c00-6b5b-4851-a367-4f37f292fef3.png)
Real Estate & Hotel are 2 main business of our company. I am in charge of Markeing planning and 
introduced and guided by one of customer for FIL+ program. effect pictures, archives of our wechat Official Account contents are the data we would like to store: https://1drv.ms/u/s!AukgXeO7_gzEbocrT4NQF3ng7XY?e=9TdKIy we have actively get in touch with some of the SPs (f0878005,f085777,f01275559,f01269025) and was recommended to save 5 copies.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 150TiB

**Client address**

> f1z4c3lz62cj6ttz75n5y35uldc6plhzgwcdjn6ma

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
