### ISSUE TITLE
[DataCap Application] <hashfin> 

### ISSUE THREAD

**Issue by qituo** [filecoin-project/filecoin-plus-large-datasets#1440]
### Data Owner Name

hashfin

### Data Owner Country/Region

Japan

### Data Owner Industry

Web3 / Crypto

### Website

https://www.hashfin.com

### Social Media

```text
https://www.bloks.io/account/hashfineosio

1: EOS whole node data

2: Log data of EOS project,

3: Log data of 7 currencies of staging;

4: Our statistics on staging;

5: We distribute the platform project data of staging revenue ourselves;
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

400TiB

### On-chain address for first allocation

f1lgbffxfxen7ok2cgkhscgqhcynzxkapj7opofsa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
This project is a project that we have been working on staging since 2019. At present, our EOS has voted 160 million votes, ranking sixth in the whole network. Other projects are also under way. We want to store our data on filecoin. I hope to get approval. Thank you
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
1: EOS whole node data

2: Log data of EOS project,

3: Log data of 7 currencies of staging;

4: Our statistics on staging;

5: We distribute the platform project data of staging revenue ourselves;
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
1: EOS whole node data

2: Log data of EOS project,

3: Log data of 7 currencies of staging;

4: Our statistics on staging;

5: We distribute the platform project data of staging revenue ourselves;
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Big data exchange, Partners

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please share some samples of the data, such as a link.

**Comment by Louis9125** [comment]
https://drive.google.com/file/d/1bLc3xgg2GA7BDyD6pKjqkwOwjU-JqRZm/view?usp=share_link
https://drive.google.com/file/d/1puI37JcnD_mcAc7dRdpgt90KBujvDzee/view?usp=share_link
https://drive.google.com/file/d/1s5mHMaZmjZ0hoJWRryWZ68ievv-0pK22/view?usp=share_link
https://drive.google.com/file/d/1pjr5DhoTbDcfRY_NoMXWTfUxxpS__zHi/view?usp=share_link
https://drive.google.com/file/d/1ZBvEqXcUobs-h3lzR-26VAdYBC7kj7Xw/view?usp=share_link

**Comment by Louis9125** [comment]
@Sunnyiscoming  Submit, please check, thank you!

**Comment by qituo** [comment]
https://drive.google.com/file/d/1bLc3xgg2GA7BDyD6pKjqkwOwjU-JqRZm/view?usp=share_link
https://drive.google.com/file/d/1puI37JcnD_mcAc7dRdpgt90KBujvDzee/view?usp=share_link
https://drive.google.com/file/d/1s5mHMaZmjZ0hoJWRryWZ68ievv-0pK22/view?usp=share_link
https://drive.google.com/file/d/1pjr5DhoTbDcfRY_NoMXWTfUxxpS__zHi/view?usp=share_link
https://drive.google.com/file/d/1ZBvEqXcUobs-h3lzR-26VAdYBC7kj7Xw/view?usp=share_link

**Comment by qituo** [comment]
Submit, please check, thank you!

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 400TiB

**Client address**

> f1lgbffxfxen7ok2cgkhscgqhcynzxkapj7opofsa

**Comment by liyunzhi-666** [comment]
hey @qituo 
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by qituo** [comment]
1: EOS whole node data
2: Log data of EOS project,
3: Log data of 7 currencies of staging;
4: Our statistics on staging;
5: We distribute the platform project data of staging revenue ourselves;
They have a total of about 800T of data,I temporarily decided to package 5 copies.

I am the technical lead of this project；

At present, the SPs in communication include Hong Kong, the United States, Singapore, and South Korea, and their node numbers are f01851482 f01852023 f01852325 f01852664 f01852677;

They both support data retrieval；

**Comment by liyunzhi-666** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceak3i3sxlefse3jp4so74c5n7a7xopdfr77vtoo3ygwswhn4tpwrc 
#### Address 
> f1lgbffxfxen7ok2cgkhscgqhcynzxkapj7opofsa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1pszcrsciyixyuxxukkvtazcokexbn54amf7gvoq
#### Id
> 7da112c3-9ed5-45a9-908e-b368758b509c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceak3i3sxlefse3jp4so74c5n7a7xopdfr77vtoo3ygwswhn4tpwrc

**Comment by Tom-OriginStorage** [comment]
can you send email to [[filplus-app-review@fil.org]

**Comment by qituo** [comment]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/15155802/209055765-0fa4d66b-779c-42d9-9465-22f9cc5ed875.png">

**Comment by Tom-OriginStorage** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecshl5r3vxoyrqtd2vesw62xodxctftnzclex7hi6omamsuobiqri 
#### Address 
> f1lgbffxfxen7ok2cgkhscgqhcynzxkapj7opofsa
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 7da112c3-9ed5-45a9-908e-b368758b509c
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecshl5r3vxoyrqtd2vesw62xodxctftnzclex7hi6omamsuobiqri

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Tom-OriginStorage** [comment]
checker:manualTrigger

**Comment by qituo** [comment]
> @qituo the EOS chain only is a few TiB's in size why would you need 5PiB ?

In addition to EOS nodes, there are many other data,

1: EOS whole node data
2: Log data of EOS project,
3: Log data of 7 currencies of staging;
4: Our statistics on staging;
5: We distribute the platform project data of staging revenue ourselves;
They have a total of about 800T of data,I temporarily decided to package 5 copies.
https://www.hashfin.com

**Comment by cryptowhizzard** [comment]
proposals dealscanner-f01999116-f01851482: ERROR: offer error: retrieval query offer errored: failed to fetch piece to retrieve from: getting pieces for cid QmebLJuX4igcmSj6Mhi4FxWyEh2qFNdYZMT5JVFoBWzER3: getting pieces containing block QmebLJuX4igcmSj6Mhi4FxWyEh2qFNdYZMT5JVFoBWzER3: failed to lookup index for mh 1220f17de5e3a637556bf7b2531de03931bb88b030cafde7d5c6252e401084969ebe, err: datastore: key not found

It seems retrievals are not working. Can you contact f01851482 to get that fixed?

**Comment by qituo** [comment]
> This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to contact the Fil+ Gov team to re-open the application if it is still being processed. Thank you!

We are preparing to launch this project recently. Could you please help me reopen it  Thank you

**Comment by qituo** [comment]
checker:manualTrigger

**Comment by qituo** [comment]
> This application has not seen any responses in the last 14 days, so for now it is being closed. Please feel free to contact the Fil+ Gov team to re-open the application if it is still being processed. Thank you!

@kevzak We are preparing to launch this project recently. Could you please help me reopen it Thank you

**Comment by qituo** [comment]
checker:manualTrigger
