### ISSUE TITLE
[DataCap Application]<Jiangsu Byte ZhiHong Technology Co., Ltd.>-<Cloud storage platform>

### ISSUE THREAD

**Issue by leoink** [filecoin-project/filecoin-plus-large-datasets#1442]
### Data Owner Name

Jiangsu Byte Zhihong Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

www.zjzhpool.com

### Social Media

```text
www.zjzhpool.com
```

### Total amount of DataCap being requested

1PiB

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1qysp3gb7j5bjw4jf2n5njtfmmsmc5q36j6gjn7q

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Jiangsu Byte Zhihong Technology Co., Ltd., headquartered in Nanjing, Jiangsu, was established on March 1, 2021, with a registered capital of 10 million yuan. The company is committed to providing users with distributed storage solutions, distributed network solutions, distributed computing solutions, Web3.0 application development and blockchain technology services, and deeply cultivating the construction of a distributed business ecosystem.
We believe that Filecoin will be an integral part of achieving this vision.
We hope to continue to expand our participation in networks and communities
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We have a lot of customer data to archive
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://pan.baidu.com/s/1jTgF5Enqz4G0g1Enla2-pw  Extraction code:zjzh
https://pan.baidu.com/s/1i-z7TWRN65CggGqUvupDfg  Extraction code:zjzh
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Big data exchange

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Have you authorized to store the data of users? Can you explain user data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
Whether the sps you choose can support data retrieval?

**Comment by leoink** [comment]
Thank you for your reply.

The website of your organization shows that you operate an E-commerce platform. The Data samples you provided doesn't seem to have much to do with your business. Can you explain about that?

The website is another business of the company. The company also provides distributed storage solutions. Data samples are from the storage business.
https://pan.baidu.com/s/1Ir7hZE3GSekioR-DAfTNrw Extraction code:zjzh
This is the copyright registration certificate of some software related to our storage.

Have you authorized to store the data of users? Can you explain user data composition and provide sufficient data samples separately? How many copies will you store?
Yes. 
https://pan.baidu.com/s/1L8lTVYt5paUQnkjhEzb8fg Extraction code:zjzh
This is the data stored by users, These data are live playback backups of live broadcast platforms (such as twitch)，plan to store 1-2 copies, maybe more.

What's the relationship between you and the organization?
Partner.

Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?
http://www.sunrisegroup.com.cn/software2_detail.aspx?t=100&cid=93

Whether the sps you choose can support data retrieval?
Yes.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 1PiB

**Expected weekly DataCap usage rate**

> 50TiB

**Client address**

> f1qysp3gb7j5bjw4jf2n5njtfmmsmc5q36j6gjn7q

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by leoink** [comment]
Could you demonstrate exactly how and to what extent customer contact occurred?
This is a public dataset and the dataset can be onboarded without customer contact
Other questions are hence not applicable

Why is the customer data considered Filecoin+ eligible?
Because it is public dataset

Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
We will use the program developed by ourselves to distribute, usually there will be no duplicate transactions

@herrehesse

**Comment by herrehesse** [comment]
@leoink your answers do not align with your datacap requests. Please explain:

“We have a lot of customer data to archive”

Why this is a “public dataset” ?

**Comment by leoink** [comment]
For example, 
https://pan.baidu.com/s/1L8lTVYt5paUQnkjhEzb8fg Extraction code:zjzh
This is the data stored by users, These data are live playback backups of live broadcast platforms (such as twitch)，plan to store 1-2 copies, maybe more.

The data itself is published on the web and available for public inquiry
@herrehesse

**Comment by herrehesse** [comment]
@leoink Thank you for providing a sample and an explanation, appreciated.
I do not fully understand why this data fits the narrative of "storing humanities most important information". 
I can setup a permanent copy from YouTube or Twitch channels and store them with 5 copies onto the Filecoin network with Datacap, this is NOT where the Filecoin+ program is meant for.

Please, if you want to store livestreams, use regular deals.

@raghavrmadya @Sunnyiscoming

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
