### ISSUE TITLE
[DataCap Application] <Tensee> - <SAP IDES Resource Management Storage>

### ISSUE THREAD

**Issue by KevinXiong2018** [filecoin-project/filecoin-plus-large-datasets#1445]
### Data Owner Name

Guangzhou Tensee Information Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.tensee.com.cn

### Social Media

```text
http://www.tensee.com.cn
xying@tensee.com.cn
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1de4p54dgtlms5ldkjmitf5caafhov4i6vxtfmca

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
organization:
Tensee has a professional ERP consultant team with more than 10 years of experience in the IT industry, providing excellent services to customers. Tensee's professional and mature operation and maintenance service system and operation and maintenance project management methods help users successfully build an ERP system operation and maintenance mechanism and reflect the value of operation and maintenance, helping users to operate with excellence. As a professional ERP service provider, Tense has senior experts in the ERP field and rich experience in homogeneous/heterogeneous migration projects. Early warning and assessment of possible risks in the migration process can be made in advance, and the project can be managed in turn according to the perfect project implementation method to minimize the risk.

project:
In 2023, Cabbeen Apparel is based on the new ECC upgrade project of SAP Business Suite 4 SAP HANA (SAP S/4HANA).
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Milestones:
The first stage: project preparation. Including: project management, project team training, preliminary project implementation plan, formulating project implementation norms and standards, starting project network/hardware technical environment analysis and planning, quality inspection.

The second stage: blueprint design. Including: project management, primary and intermediate training of project team, establishment of system technology environment, determination of enterprise organizational structure, description, analysis, optimization and determination of enterprise business process, quality inspection.
We need to build SAP IDES (Internet Demonstration and Evaluation System) or our own IDES dataset for customers.

The third stage: system implementation. Including: project management, advanced training of project team, basic system configuration and confirmation, system management, final system configuration and confirmation, development of data conversion program, development of application interface program, development of plug-in or extension program, report definition, format definition, authority definition and Administration, archive definition and management, system integration testing, user manuals and training materials, quality checks.
We need to build SAP DEV (Development System) and our own defined DEV dataset for customers.

Phase Four: Testing and Preparation. Including: project management, user training, system management, formal operation, installation test of technical environment, system performance, safety test, formulation of detailed operation plan, formulation of system switching plan, formulation of system operation support plan, data preparation, system switching, quality inspection .
We need to build SAP QAS (Quality Assurance system) or our own QAS data set for customers.
[Optional] Need to build SAP PET (Performance Evaluation Test) or our own defined PET data set for customers.
[Optional] It is necessary to build SAP UAT (User Acceptance Testing) or a UAT dataset defined by ourselves for customers.
[Optional] It is necessary to build SAP SIT (System Integration Testing) or our own defined SIT data set for customers.

The fifth stage: the system goes online. Project management, follow-up training, providing user support, confirming the correctness of formal business processes, optimizing the use of the system, formulating follow-up long-term plans, system upgrades, daily maintenance, and project reviews.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, singularity, graphsplit

### Please share a sample of the data

```text
https://pan.baidu.com/s/1-5Npnphv05w7ATGWrrVo5Q?pwd=nvjs#list/path=%2FDC

https://pan.baidu.com/s/1-5Npnphv05w7ATGWrrVo5Q?pwd=nvjs
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f01090983,f0673990,etc
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you tell me how to open the data sample you provided?
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Whether the sps you choose can support data retrieval?

**Comment by KevinXiong2018** [comment]
Can you tell me how to open the data sample you provided?
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
--------------------------
Ok, very happy, just updated a sample file after decompression,
https://pan.baidu.com/s/1-5Npnphv05w7ATGWrrVo5Q?pwd=nvjs#list/path=%2FDC 
Plan to store 3-5 copies, maybe more.

What's the relationship between you and the organization?
--------------------------
Partner. For some professional SAP implementation consultant teams, we assist in building SAP IDES, DEV, QAS, etc. to develop and test open datasets.

Whether the sps you choose can support data retrieval?
--------------------------
yes.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1de4p54dgtlms5ldkjmitf5caafhov4i6vxtfmca

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
