### ISSUE TITLE
[DataCap Application] Atomic International

### ISSUE THREAD

**Issue by coldjoke1** [filecoin-project/filecoin-plus-large-datasets#1451]
### Data Owner Name

Atomic International 

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

http://www.amisinternation.com/

### Social Media

```text
NA
```

### Total amount of DataCap being requested

4PiB

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f1fqbgy26t3bh7spmasqhoujo7urmhgy5iroja7iq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Atomic International Pte. Ltd. is a global e-commerce trading company, located in the center of Shenzhen Golden Dragon City, specializing in online marketing, brand building and cross-border e-commerce. The company specializes in online marketing, brand building and cross-border e-commerce. It provides B2C, B2B and other e-commerce services. The company's products include: auto parts, motorcycle parts, LED, electronic products and other categories, with a good reputation has been trusted by customers at home and abroad
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Product/UI/promotion design material
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
Here is the link:
https://1drv.ms/u/s!AsTmtmvmZZv7anEda9vAHQSzMyA?e=yqa7Oh
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

I don't know yet

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
How much data do you have? A psd. document is about 10 MB.
It seems that these pictures is not created by your organization. Are you authorized to store these data as public data on the Filecoin network.
![image](https://user-images.githubusercontent.com/105098820/208283388-509b10bd-ee12-41e6-8bc4-8de1f38ca655.png)

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Close for no reply.
