### ISSUE TITLE
[DataCap Allocation] - Filecoin Fullnode dataset application

### ISSUE THREAD

**Issue by heroapn** [filecoin-project/filecoin-plus-large-datasets#1452]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Filecoin Fullnode dataset application"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: WenChu BlockChain
- Website / Social Media: https://www.wenchu.io/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 560TiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1p76yub2nedezhhfthgq4euol5d2d6ok2rowlxra
- Region: Greater China Region

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Projeck:
We will run multiple lotus full nodes and provide API access services to the outside world. Synchronization starts from tipset 0. The data volume is about 30T. These data are stored in high-speed arrays. We hope that these data will be stored in 5 SPs through 4 copies middle. So that when something else happens, we don't need to start synchronization from 0, we all know that it takes a very long time to synchronize to the current altitude.
Organization:
Wenchu blockchain is a blockchain infrastructure service provider integrating blockchain technology research and development, government and enterprise solutions, professional talent training and certification, and industrial investment. Wenchu adheres to the corporate values of "pragmatic and sincere, open and innovative, and long-term win-win", and is committed to technological breakthroughs and industrial applications of blockchain.
```

What is the primary source of funding for this project?
```
ourself
```

What other projects/ecosystem stakeholders is this project associated with?
```
no
```

## Use-case details

Describe the data being stored onto Filecoin
```
Lotus node synchronization data
```

Where was the data in this dataset sourced from?
```
from our fullnode machine
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/file/d/1YbFAK8P7mz-FL0JSYSbq2Omwn5zbNpFu/view?usp=sharing
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
yes
```

What is the expected retrieval frequency for this data?
```
yearly
```

For how long do you plan to keep this dataset stored on Filecoin?
```
permanently
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
China
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Shiping hard drives.Offline
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We choose my partners.

```

How will you be distributing deals across storage providers?
```
 data will be stored in 5 SPs through 4 copies.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
yes
```

**Comment by Sunnyiscoming** [comment]
For most of the datacap application, below restrictions should apply.

Storage provider should not exceed 25% of total datacap.
Storage provider should not be storing duplicate data for more than 20%.
Storage provider should have published its public IP address.
All storage providers should be located in different regions.

You will store 4 copies on each sp. It is not allowed for the second restriction.

What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by heroapn** [comment]
I'm sorry that it took so long to restore you. I'm an employee of wenchu blockchain. The fil+document only mentions that each SP cannot exceed 30% of the datacap, so I am not very clear about the above-mentioned limitations. The fullnode only has 30T data, so I can't apply for LDN according to the above requirements. Is there a better way to save him among the five miners.

**Comment by Sunnyiscoming** [comment]
If you do not have storage requirement for more than 500 TB, you can apply datacap from notaries directly.

**Comment by heroapn** [comment]
Something wrong in https://plus.fil.org/.Can not apply from general verification.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 560TiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1p76yub2nedezhhfthgq4euol5d2d6ok2rowlxra

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
