### ISSUE TITLE
[DataCap Application] Brose

### ISSUE THREAD

**Issue by Broseoffcial** [filecoin-project/filecoin-plus-large-datasets#1453]
### Data Owner Name

Brose

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

www.brose.com

### Social Media

```text
https://www.facebook.com/brosecareers
https://twitter.com/brose_karriere
https://www.xing.com/pages/brosegruppe
https://www.linkedin.com/company/brose?original_referer=
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1wj736fmm23g3qzibmrbrzvtc46zwpfedh7gb27q

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Brose is the fourth-largest family-owned automotive supplier. Every second new car worldwide is equipped with at least one Brose product. Including the joint venture Brose Sitech, the company employs 30,000 people at around 70 locations in 25 countries. For 2022, the Brose Group expects a turnover of more than 7 billion euros. With numerous patent applications per year, Brose is one of Germany's most innovative companies.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Videos of Brose which are introduce our company's business.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
https://c.gmx.com/@1162700078998100672/nz6mmhFNT6uoEL_jldLFUg
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
We haven't found suitable sps yet, we expect to find a sp to help us store data soon.
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? 
How many copies will you store? 
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by Broseoffcial** [comment]
@Sunnyiscoming Our data mainly consists of videos and we have a 315MB data sample, you can check it here. We prepared 5 copies for this storage. https://c.gmx.com/@1162700078998100672/nz6mmhFNT6uoEL_jldLFUg I am an employee applying for a storage capacity on behalf of our company. We are looking for it to store our data. We are actively contacting sp and we will confirm sp support for retrieval before working with them.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Waiting for KYB email.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1wj736fmm23g3qzibmrbrzvtc46zwpfedh7gb27q

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Hello @Broseoffcial 

Seems your datacap has not been used yet. When can we expect the first deals to arrive on the network?

**Comment by swatchliu** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7vp2iqxih7frjbv3omi357ts75nrvqnb74h6ykwfnr22ntpf6lq 
#### Address 
> f1wj736fmm23g3qzibmrbrzvtc46zwpfedh7gb27q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### Id
> 27b0dbe4-aff2-42b3-bb69-1b3f43f11366
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7vp2iqxih7frjbv3omi357ts75nrvqnb74h6ykwfnr22ntpf6lq

**Comment by 1475Notary** [comment]
I know the assistant GM of Brose and have confirmed that this application is true. willing to support!

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedsu57g2dhhvfi77ebynnecd2rtucnmcytclzqnccton2thdetjuk 
#### Address 
> f1wj736fmm23g3qzibmrbrzvtc46zwpfedh7gb27q
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### Id
> 27b0dbe4-aff2-42b3-bb69-1b3f43f11366
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsu57g2dhhvfi77ebynnecd2rtucnmcytclzqnccton2thdetjuk

**Comment by Broseoffcial** [comment]
yes!

**Comment by Sunnyiscoming** [comment]
Hello, @Broseoffcial per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.
