### ISSUE TITLE
[DataCap Allocation] - Artificial Intelligence

### ISSUE THREAD

**Issue by ruiyaningAI** [filecoin-project/filecoin-plus-large-datasets#1458]
---
name: Large Dataset Notary application
about: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "Artificial Intelligence"
labels: 'application, Phase: Diligence'
assignees: ''

---
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Chengdu Ruiyan Technology Co., Ltd
- Website / Social Media: https://www.ruiyanai.com/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1g6xfvaj2utdig4dvfiiayywiwua3hbq5d36iooi
- Region: Asia (excl. Greater China)

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Chengdu Ruiyan Technology is a leading artificial intelligence R&D enterprise in the industry, committed to the research and innovation in the field of computer vision and deep learning.

Chengdu Ruiyan Technology Co., LTD., set up a top R & D team with the international frontier research vision. The core members of the team are composed of masters and doctors from well-known universities and national key laboratories. The team has reached the world-class level in 2D behavior recognition, face recognition, object cutting and recognition, target tracking, OCR field, super division scheme field fields. 
Ruiyan Technology has achieved excellent results in artificial intelligence competitions in various fields such as behavior recognition, target tracking, target re-recognition (ReID/MTMC), remote sensing image interpretation, OCR, etc. Lock cheap, intelligent and efficient war supplies in the military track, provide the supplies with mission load, communication, AI chip and flight control, ground end, and use cost-effective electronic components to achieve high-precision control. It mainly includes photoelectric pod, Ai board card, video board card, TV guidance infrared guidance and other cost-effective AI photoelectric equipment, low delay data link of 100 km level, AD hoc networking equipment and other products. In addition, we have a professional analysis team in military big data, especially in intelligence processing, which is committed to achieving the military purposes of attack, cover and war of attrition loss with the ultimate cost performance.
Ruiyan Technology has set up R&D centers in Chengdu and Beijing, offices in Xiamen and Shenzhen, and established cooperation with hundreds of world famous enterprises and institutions. Ruiyan Technology's excellent platform and leading technology are widely used in video audit and broadcast control, smart security, smart city, Xueliang engineering, smart retail, smart campus, power grid oil and other fields, to help Ruiyan partners to build a more intelligent business center.
```

What is the primary source of funding for this project?
```
corporate income
```

What other projects/ecosystem stakeholders is this project associated with?
```
None
```

## Use-case details

Describe the data being stored onto Filecoin
```
We need to store a large number of people, things and 2D, 3D image video files to meet the 2D behavior recognition, face recognition, object cutting and recognition, target tracking and so on.
```

Where was the data in this dataset sourced from?
```
These data come from the company's business. Every day, it will generate a large number of video surveillance data, and it will provide customers in various industries with security artificial intelligence services.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://drive.google.com/drive/folders/1rCiRHRHdvzlWWxz8w8kreXld1SKB5hb9
https://drive.google.com/drive/folders/1SrKG7_MEMUv_zaKLNkx2VHRS_xgfYP-t
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm
```

What is the expected retrieval frequency for this data?
```
No need to frequent, 1-2 times a day
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Three years
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
All regions
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We have our own IDC room, can open the external network for customers downloading.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We will choose a storage provider with high reputation and strong transaction confidentiality. Before we cooperate with them, we should know the size of their business, reliability, whether they have core hardware and professional technical team. Because we know the confidentiality of the data is very important
```

How will you be distributing deals across storage providers?
```
We will distribute equally to high-quality storage providers
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
When we get our datacap, we make the transaction immediately. And there is enough money to pay for it.
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/208377937-797c41aa-4be4-4d3b-bfda-033c3d936420.png)
The links of data samples you provided is unavailable. Please check them.

![image](https://user-images.githubusercontent.com/105098820/208381782-de2e9fba-4379-4eef-aa2d-b65e631aec75.png)
The website doesn't seem to have substance either.

**Comment by ruiyaningAI** [comment]
@Sunnyiscoming 
Hello, the permission has been reset, and it can be opened normally now, please check again. And the official website has substantial content. It's better that you can wait for the content to load after you open it
![image](https://user-images.githubusercontent.com/120539984/208570121-cf6ba7e8-1bf3-43ca-ad9d-71fe5250a2b3.png)

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1g6xfvaj2utdig4dvfiiayywiwua3hbq5d36iooi

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by ruiyaningAI** [comment]
@cryptowhizzard 
hi,this is the storage system we use, which stores our company's business data
![1675132477462](https://user-images.githubusercontent.com/120539984/215649093-f349b936-6b3d-4af1-917f-3d4fe461f5c8.jpg)

**Comment by cryptowhizzard** [comment]
>>
As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
>> 

?

**Comment by hail100** [comment]
@cryptowhizzard 
hi,Completed, please check
