### ISSUE TITLE
[DataCap Application] <Jinhua Zhiyang Information Technology Co., Ltd.>

### ISSUE THREAD

**Issue by gethong** [filecoin-project/filecoin-plus-large-datasets#1459]
### Data Owner Name

Jinhua Zhiyang Information Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

www.jhzyxx.com

### Social Media

```text
https://www.taptap.cn/developer/24752
https://www.taptap.cn/app/223060
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1frejwasmyel3oay5yemvelva5ydjcgff6u3argq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Jinhua Zhiyang Information Technology Co., Ltd. was established in March 2014. It is a software and high-tech enterprise specializing in Internet software development and technical services. The company focuses on developing and designing mobile games and is committed to providing high-quality and rich mobile games to mobile Internet end users.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
These are all self-owned company data, including mobile game installation packages, word docs and spreadsheets of whitepapers, protocol, configuration files, and online streaming surveillance videos and all kinds of game picture materials of the company.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

https://github.com/filswan/go-swan-client#Graphsplit

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1uHDlEpsV0yCmbPl7Dr6aBjKEx-zNNAit
https://drive.google.com/drive/folders/1OfrHG9TmIDZeE61udHgtw70jtcBljLOr
https://drive.google.com/drive/folders/1j_jkGSZzS4iuv4C5WpECveMweBGMKtN1
https://drive.google.com/drive/folders/1FPEdtXF8parhs6PHxOAsMLeD37MfPvFt
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Others

### If you answered "Others" in the previous question, what is the tool or platform you plan to use

https://filswan.com

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here

https://github.com/filswan/go-swan-client#15-create-a-task

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? 
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by gethong** [comment]
> Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

@Sunnyiscoming 
The data we’d like to store onto Filecoin include:
- Mobile game intallation resources: https://drive.google.com/drive/folders/1uHDlEpsV0yCmbPl7Dr6aBjKEx-zNNAit
- Development resources and materials: https://drive.google.com/drive/folders/1uuFrSMnKzUW-NdSHEJustJy4sK3mkQLg
- Online streaming surveillance videos: https://drive.google.com/drive/folders/1j_jkGSZzS4iuv4C5WpECveMweBGMKtN1
- Operation and maintenance management documents: https://drive.google.com/drive/folders/1OfrHG9TmIDZeE61udHgtw70jtcBljLOr
- Game pictures and related materials: https://drive.google.com/drive/folders/1FPEdtXF8parhs6PHxOAsMLeD37MfPvFt

We would like to store 10 copies of the data. I’m Wang Kai, the IT Director of the company and my email address is wangkai@jzjjh.com. The storage providers we have contacted so far are f01947280, f01955028, f01955030, f01955034, and all of them are required to support data retrieval.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1frejwasmyel3oay5yemvelva5ydjcgff6u3argq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by gethong** [comment]
> Dear applicant,
> 
> Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.
> 
> Looking at your application i have some questions: As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?
> 
> Can you show us visible proof of the size of your data and the storage systems you have there?
> 
> As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.
> 
> Thanks!

@cryptowhizzard Thanks for your review. We have not applied for datacap before. The data size is about 502TB in total, as seen from the pic. And we've already filled out the form. Please check it.

A part of the dataset is stored on my server, the screen sanpshot is as follows:
![image](https://user-images.githubusercontent.com/36029973/216548911-a02b1244-c61d-48c0-a6f4-ffb1f1754678.png)

**Comment by cryptowhizzard** [comment]
Hello @gethong 

Thanks for doing KYC. I received the form in good order.

Upon evaluation i see that f01947280, f01955028, f01955030, f01955034 are all one organization and all in the same datacenter. Are these your own SP's where you have stake in and what is the organization name?

You mentioned you don't have stake in any SP and that you are data owner yourself correct? Please confirm again.

As the form states i need 3 more organizations ... can you please provide them to me?

>>
RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:

Data must be stored with multiple independent service providers, not just one organization running multiple SPs.
Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed.
Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost.
Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way.
Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead.
Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.
>>

**Comment by gethong** [comment]
> Hello @gethong
> 
> Thanks for doing KYC. I received the form in good order.
> 
> Upon evaluation i see that f01947280, f01955028, f01955030, f01955034 are all one organization and all in the same datacenter. Are these your own SP's where you have stake in and what is the organization name?
> 
> You mentioned you don't have stake in any SP and that you are data owner yourself correct? Please confirm again.
> 
> As the form states i need 3 more organizations ... can you please provide them to me?
> 
> > >
> 
> RULES: In order to be eligible for the Filecoin+ incentive program, which provides 10x the power (QAP) for storing data on the Filecoin network, there are certain rules that must be followed:
> 
> Data must be stored with multiple independent service providers, not just one organization running multiple SPs. Data must be distributed across multiple regions. Using a VPN to fake presence is not allowed. Data must be publicly retrievable for verification that it is being stored as claimed. It is highly recommended to run boost. Data must align with the mission of FIL+, meaning it must be valuable for humanity, whether scientific or unique in some other way. Data must be open and not encrypted. If you wish to encrypt your data, consider applying for the FIL-E program instead. Note: As a data preparer, you are allowed to store one copy yourself for redundancy at the request of the client. However, if your copy is stored in the USA, the other organizations/SPs must be outside your region. Dcent encourages applications with a minimum spread of 2 continents and 3 different organizations.
> 
> > >
@cryptowhizzard 
These are not our own SPs. 
And no, we don't have a stake in any SPs. 
We confirm again that we are the data owner.
 We just contact storage providers from Asia, and we'd like to use FilSwan platform to find storage providers from other regions. As we all know, the platform will automatically match suitable SPs for storing our data.

**Comment by flyworker** [comment]
The answer looks good for me.
Would like to give it a try.

**Comment by flyworker** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea4wapbvjvlvxiba7xashb3hobqeztadq6zamn4773nrrs6kdnfzs 
#### Address 
> f1frejwasmyel3oay5yemvelva5ydjcgff6u3argq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1hlubjsdkv4wmsdadihloxgwrz3j3ernf6i3cbpy
#### Id
> 60e3b98f-ad8a-4841-a7e3-b04e772840d0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea4wapbvjvlvxiba7xashb3hobqeztadq6zamn4773nrrs6kdnfzs

**Comment by kernelogic** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy6fdi6ygaojj3zvcf2rj7vw3x4pb7g3qlmmlrmarq7rx4sya73y 
#### Address 
> f1frejwasmyel3oay5yemvelva5ydjcgff6u3argq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> 60e3b98f-ad8a-4841-a7e3-b04e772840d0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy6fdi6ygaojj3zvcf2rj7vw3x4pb7g3qlmmlrmarq7rx4sya73y

**Comment by gethong** [comment]
Hello, I forgot to use this application after it was approved before. Can you help me open it again? We will strictly follow the regulations in the future to avoid this happening again.
@kevzak @Sunnyiscoming
