### ISSUE TITLE
[DataCap Application] <Beijing Junqianzi Technology Co., LTD>

### ISSUE THREAD

**Issue by liufeng6582** [filecoin-project/filecoin-plus-large-datasets#1460]
### Data Owner Name

Beijing Junqianzi Technology Co., LTD

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

http://www.dao1nft.com/

### Social Media

```text
http://www.dao1nft.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1gf4f5xyxuexadtelb7onnbgg2nukail3lv6kd3y

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Beijing Junqianzi Technology Co., Ltd. is a technology company with independent research and development of Internet projects. The company has connected with a number of small e-commerce platforms and NFT platforms to provide users with high-quality technical support services. At the same time, we also have a perfect e-commerce platform, with a large number of users and product resources, we are committed to providing customers with better quality products and services. Improve people's quality of life and happiness
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
1、Article picture material
2、Object video material
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
aaa
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
> Please share a sample of the data
> aaa
> 

You have no data sample shared. Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? 
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Any update here?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1gf4f5xyxuexadtelb7onnbgg2nukail3lv6kd3y

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
checker:manualTrigger
