### ISSUE TITLE
[DataCap Application] WenChu Blockchain

### ISSUE THREAD

**Issue by data-programs** [filecoin-project/filecoin-plus-large-datasets#1465]
### Data Owner Name
WenChu Blockchain

### Data Owner Country/Region
China

### Data Owner Industry
Web3 / Crypto

### Website
[https://www.wenchu.io/](https://www.wenchu.io/)

### Social Media
WeChat Official Accounts: http://weixin.qq.com/r/Bi5ZXJfEnF-gKNM-b3uC (@WenChu_BC)

### Total amount of DataCap being requested
560 TiB

### Weekly allocation of DataCap requested
80 TiB

### On-chain address for first allocation
f1p76yub2nedezhhfthgq4euol5d2d6ok2rowlxra

### Custom multisig
No

### Identifier
---

### Share a brief history of your project and organization
Projeck:
We will run multiple lotus full nodes and provide API access services to the outside world. Synchronization starts from tipset 0. The data volume is about 30T. These data are stored in high-speed arrays. We hope that these data will be stored in 5 SPs through 4 copies middle. So that when something else happens, we don't need to start synchronization from 0, we all know that it takes a very long time to synchronize to the current altitude.
Organization:
Wenchu blockchain is a blockchain infrastructure service provider integrating blockchain technology research and development, government and enterprise solutions, professional talent training and certification, and industrial investment. Wenchu adheres to the corporate values of "pragmatic and sincere, open and innovative, and long-term win-win", and is committed to technological breakthroughs and industrial applications of blockchain.

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
---

### Describe the data being stored onto Filecoin
Lotus node synchronization data

### Where was the data currently stored in this dataset sourced from
My own storage infra

### If you answered "Other" in the previous question, enter the details here
---

### How do you plan to prepare the dataset
IPFS

### If you answered "other/custom tool" in the previous question, enter the details here
---

### Please share a sample of the data
https://drive.google.com/file/d/1YbFAK8P7mz-FL0JSYSbq2Omwn5zbNpFu/view?usp=sharing

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
Shipping hard drives

### How do you plan to choose SP
Partners

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
---

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
---

### How do you plan to make deals to your storage providers
Lotus client

### If you answered "Others/custom tool" in the previous question, enter the details here
---

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by timelytree** [comment]
@heroapn I migrated your application from [here](https://github.com/xinaxu/filecoin-plus-large-datasets/issues/8). Our system had mistakenly submitted it to the wrong repo. Can you confirm that this is your application and not someone else's?

**Comment by heroapn** [comment]
> @heroapn I migrated your application from [here](https://github.com/xinaxu/filecoin-plus-large-datasets/issues/8). Our system had mistakenly submitted it to the wrong repo. Can you confirm that this is your application and not someone else's?

Yes,that is my application.Hope the team can review and approve asap.

**Comment by Sunnyiscoming** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1452
Is this the same request submitted by your organization?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Close for same request https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1452
