### ISSUE TITLE
[DataCap Application] UZERO

### ISSUE THREAD

**Issue by data-programs** [filecoin-project/filecoin-plus-large-datasets#1469]
### Data Owner Name
UZERO

### Data Owner Country/Region
China

### Data Owner Industry
Other

### Website
[http://www.uzero.com.cn/](http://www.uzero.com.cn/)

### Github Handle
@UZERO2022

### Social Media
https://weibo.com/uzerochina?is_all=1 (Weibo    10/2000  Wechat public account)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq

### Custom multisig
No

### Share a brief history of your project and organization
UZERO was born in Hangzhou, China in 2009. It belongs to the A-share listed company Proya Cosmetics Co., Ltd. and is a natural skin care brand.

UZERO adheres to scientific and technological innovation, uses high-tech research and extracts the essence of tea, and brings a new natural, safe and healthy skin care experience to women.

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
1. UZERO and China Tea Museum are strategic partners.
2. UZERO operates a professional e-commerce platform.

### Describe the data being stored onto Filecoin
The data stored on Filecoin is the data of our e-commerce platform, such as product photos, videos, customer data and other publicly available data

### Where was the data currently stored in this dataset sourced from
Google Cloud

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
Tools from the Storage providers

### Please share a sample of the data
https://drive.google.com/file/d/1r-RaeQzMPKEgkdSHfFYt4vXUTNHG85s_/view?usp=sharing
https://drive.google.com/file/d/1dQS0lGOFoaoJ4cir2zLiKz-V0Ic2VTH1/view?usp=sharing

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Asia other than Greater China

### How will you be distributing your data to storage providers
Cloud storage (i.e. S3)

### How do you plan to choose SP
Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
f0152799 f01943959  f01853104 f01853077

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
Tools from the Storage providers

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/208412801-19254799-0491-407b-a793-c397a4cf1757.png)
https://filplus.d.interplanetary.one/clients?filter=f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq
Whether the sps you choose can support data retrieval?
How much data do you have? How many copies will you store?
What's the relationship between you and the organization?

**Comment by UZERO-2022** [comment]
Hello， @Sunnyiscoming 
We already have a 2.5P data set and plan to store 2-3 copies. The currently selected SPs all support data retrieval.
I have sent the kyc email, please check it.
Thanks!

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq

**Comment by UZERO-2022** [comment]
@Sunnyiscoming We sent the email again, please check.
![image](https://user-images.githubusercontent.com/121491619/212613860-0682a661-ef28-437f-ba71-fb5f277a1daf.png)

**Comment by cryptowhizzard** [comment]
Can you provide us with a list of CID's you have build for this dataset so we can verify the data?

**Comment by UZERO-2022** [comment]
Hello,  @CryptoWhizzard 
Of course you can check the CID. I will list it if you need when we upload data. 
How would we proceed now? I will call out more notaries to review our application. TY!


Best,
Uzero

**Comment by Tom-OriginStorage** [comment]
> @Sunnyiscoming We sent the email again, please check. ![image](https://user-images.githubusercontent.com/121491619/212613860-0682a661-ef28-437f-ba71-fb5f277a1daf.png)

@UZERO-2022 
1：The domain name applied for is www.aa.com, which is different from the domain name sent by email. Can you explain the reason?
2：Can you tell me about the SPs you will package?

**Comment by UZERO-2022** [comment]
Hello  @Tom-OriginStorage 


Please check out the official email on our official website. It is ***@***.***



basically, the SPs that we are choosing are :
f02024315 Thailand, f02013434 Vietnam , f02031006 US., f01853077 Singapore, f01971431 Mainland CN, f02047841 HK
Data will separately transfer to those SPs in various regions.



Appreciate if if you could sign and follow up.


Best,
Uzero

**Comment by UZERO-2022** [comment]
@Tom-OriginStorage

**Comment by UZERO-2022** [comment]
![屏幕截图 2023-03-03 150137](https://user-images.githubusercontent.com/121491619/222653409-95663ce4-9898-43b0-8fb7-e560e93ef48f.png)

**Comment by Tom-OriginStorage** [comment]
Well, it looks good. I'm willing to support you in the first round

**Comment by Tom-OriginStorage** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecl37vx2p5l4n7bbblphqf24myslffolqkzy3ejp5ffao6dnvvpcy 
#### Address 
> f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1q6bpjlqia6iemqbrdaxr2uehrhpvoju3qh4lpga
#### Id
> 276d428d-9295-44dd-ba99-acbbdb27d702
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecl37vx2p5l4n7bbblphqf24myslffolqkzy3ejp5ffao6dnvvpcy

**Comment by cryptowhizzard** [comment]
I received the data. Willing to support first round to see where this goes.

**Comment by cryptowhizzard** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceav2q6w4lfbi2decd77js2ldamj5qu3pt5ry5thoa55uo7nlz6pgw 
#### Address 
> f1df64fi3a4pmo5mxvdrz2zs7n2bfd4wnixomudcq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1krmypm4uoxxf3g7okrwtrahlmpcph3y7rbqqgfa
#### Id
> 276d428d-9295-44dd-ba99-acbbdb27d702
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceav2q6w4lfbi2decd77js2ldamj5qu3pt5ry5thoa55uo7nlz6pgw
