### ISSUE TITLE
[DataCap Application] Banma App

### ISSUE THREAD

**Issue by cxk10** [filecoin-project/filecoin-plus-large-datasets#1475]
### Data Owner Name

Banma App

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://banmaapp.com/

### Social Media

```text
https://www.douyin.com/user/MS4wLjABAAAAwwOlR8yhLYuV-G_kXaJmaEDk0U2EtD7Ip6mh6zAIqQw
https://space.bilibili.com/404224022?spm_id_from=333.337.0.0
https://weibo.com/zebraenglish
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1s3hr5z5zz5n24tiyuglddrx5g4rxpkgymlc4uui

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Banma App was launched in 2017 and is a professional digital content . Through interesting animated interactive content, it helps children understand the world and explore it while building a foundation of all-round abilities, accompanying them to grow together.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Our in-app/platform education contents.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Aliyun
```

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
Sure.
https://1drv.ms/u/s!AtjBTIZxjC3XaRv2LepTVo5vku4?e=0eTCnm
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

I don't know yet

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1s3hr5z5zz5n24tiyuglddrx5g4rxpkgymlc4uui

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by cxk10** [comment]
Hi, we have sent out the confirmation email and waiting for the next step process.
![image](https://user-images.githubusercontent.com/116630136/227765715-a66ae77e-2f08-4c34-b5e2-cd4b8f6b626b.png)
