### ISSUE TITLE
[DataCap Application] Momoshop

### ISSUE THREAD

**Issue by Gitel26** [filecoin-project/filecoin-plus-large-datasets#1477]
### Data Owner Name

Momoshop

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

https://www.momoshop.com.tw/

### Social Media

```text
Facebook - https://www.facebook.com/momofans
Instagram - https://www.instagram.com/momoshopping_/
Linkedin - https://www.linkedin.com/company/fubon-multimedia-technology-co.-ltd/?originalSubdomain=tw
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1nh77gas227kn3mprrcbpou5wwkfb4n52vemgpta

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Momo shopping is under Fubon Media Technology which is the leading online retailer in Taiwan. Our business includs Motian Mall, TV shopping and catalog shopping. Headquartered in Taiwan, our group is also actively establishing international markets. On the mainland, Fubon Gehua (Beijing) Trade Co., Ltd. was established in May 2011. In March 2014, our company established TVD momo in Thailand as a joint venture.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
We want to store pictures and videos of these products which showed on our website.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://drive.google.com/file/d/1RtKB_Q1flCoeN6N1Gth4c581kwbZcIdM/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
We plan to choose f0513351 at first.
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 200TiB

**Client address**

> f1nh77gas227kn3mprrcbpou5wwkfb4n52vemgpta

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Carohere** [comment]
The resources available for review in the first round are very limited. For now i would like to go ahead and help this application move forward.

**Comment by Aaronn85** [comment]
checker:manualTrigger

**Comment by clriesco** [comment]
Removed stale label and reopened issue :)

**Comment by TobyShea** [comment]
need update
