### ISSUE TITLE
[DataCap Application] YahooTW

### ISSUE THREAD

**Issue by Jeremy917** [filecoin-project/filecoin-plus-large-datasets#1478]
### Data Owner Name

Yahoo

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

https://tw.buy.yahoo.com/

### Social Media

```text
https://www.facebook.com/YahooTWEC
https://www.instagram.com/yshop_tw/
https://line.me/R/ti/p/@yahooshopping?from=page&openQrModal=true&searchId=yahooshopping
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1p7djyfci37vzr7vnzy4jp46xlh5vacz5745vv3y

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Yahoo offers the latest and most popular products, and insists on giving clients the most charming discount prices. We provide fun way to buy, as well as themed promotions, holiday sales, credit card activities, generous free on full value, and other exciting activities. We have more than 400,000 items in 13 major categories.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Data from our app---Yahoo
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
ok. https://drive.google.com/file/d/1PHHKOnECb8dZCJ2WkHnMaMe9_sdZvOJF/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 300TiB

**Client address**

> f1p7djyfci37vzr7vnzy4jp46xlh5vacz5745vv3y

**Comment by Sunnyiscoming** [comment]
How much data do you have? How many copies will you store?
What's the relationship between you and the organization?

**Comment by Jeremy917** [comment]
Up till now we have 463TiB of data intended to be stored in filecoin. Since we want to store 10 copies, we have requested 5PiB. I'm an employee of the Yahoo. Because I know more about filecoin storage, our company asked me to make this application.

**Comment by Sunnyiscoming** [comment]
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #1078.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Jeremy917** [comment]
Hello, can anyone help us repair the label of this application? It seems that our application can not be signed because of the labels.

**Comment by lvschouwen** [comment]
@Jeremy917 
In all honesty, proper due diligence needs to be done here.
You claim to represent a 7.4 billion USD company. You application states the "Data Owner Country/Region" to be China.
Yahoo ceased all operations in China on November 2021 (https://en.wikipedia.org/wiki/Yahoo!).

The sample data provided are product videos of various copyright holders (Sony, Philips, Nintendo). Are these videos created by Yahoo or a different company?

I am not a notary, but I think we are miles away for this LDN request to be signed. Repairing labels is not a top priority for this application at this stage.

**Comment by lvschouwen** [comment]
> Hello, can anyone help us repair the label of this application? It seems that our application can not be signed because of the labels.

Other question, how do you know it cannot be signed?
Did you confirm with a notary?

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Jeremy917** [comment]
We are YahooTW, our website is in operation.
https://tw.buy.yahoo.com/
https://www.facebook.com/YahooTWEC
We are a commercial shopping site, so we have to store information about our clients' products to display on it.
What I know about the role of labels comes from what deep said in slack.
![pic](https://user-images.githubusercontent.com/112623718/216544455-6a6e111d-b1b3-49cf-86d3-c0d623b3a994.png)

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by Aaronn85** [comment]
checker:manualTrigger

**Comment by Aaronn85** [comment]
checker:manualTrigger

**Comment by Neal-fil** [comment]
checker:manualTrigger
