### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by ffff2022** [filecoin-project/filecoin-plus-large-datasets#1480]
### Data Owner Name

zhonglianzhiyun

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

zhonglzhiyun.com

### Social Media

```text
zhonglzhiyun.com
```

### Total amount of DataCap being requested

3PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1f55iw37fqhzxsxcmbsuavixd7uk6h4lu6lfpn2i

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shenzhen Zhonglian Zhiyun Technology Co., Ltd. is located in 3001 Ludan Building, No. 1011 Binhe Road, Ludan Village Community, Guiyuan Street, Luohu District, Shenzhen, with a registered capital of 100 million yuan and was established on April 12, 2021. At present, the company's main business scope is general business items, including: technology development, technology consulting and technology services of the Internet; Mobile Internet APP technology development, technical consulting and technical services; technology services and technology transfer of computer technology; Research and development of network technology; Data processing service; Technical development of computer software; R&D and sales of new materials and communication products
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data stored on Filecoin is all about monitoring data, production data, R&D data, sales data.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Mainly from the data generated during our research and development, design, transportation and sales
```

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1AJMSXjkGwQycvZk3-N8BetkdtN_ubBXs?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server, I don't know yet

### How do you plan to choose storage providers

Big data exchange, Partners, I don't know yet

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/209458828-3b653531-b343-4cee-a0da-01f268d456ad.png)
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by Sunnyiscoming** [comment]
Please provide the Chinese name of your organization.

**Comment by ffff2022** [comment]
> Please provide the Chinese name of your organization.

zhongliankonggu

website restored

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by ffff2022** [comment]
Customer data
1、Could you demonstrate exactly how and to what extent customer contact occurred?
   Contact customers through sales personnel or APP registered users, and we usually communicate directly by phone.

2、Did the customer specify the amount of data involved in this relevant correspondence?
   We have very close cooperation with customers, and we have contact almost every week

3、Why does the customer in question want to use the Filecoin+ program?
   Through communication with customers, specific data volume is sometimes mentioned according to customers' needs

4、Why is the customer data considered Filecoin+ eligible?
   Customers need a cheap, free storage space


Files and Processing
1、Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
   The content of customer data does not contain any sensitive information, does not involve copyright issues, and is suitable for free sharing on the Internet

2、Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
   For small data, we will process online, and for a large amount of data, we will process offline
   For large data, we use offline import

3、Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
   We use HASH verification to ensure that there is no duplicate data

**Comment by herrehesse** [comment]
@ffff2022 Thank you very much for all clear answers, I really appreciate you taking the time to answer me in detail.

Looking at your description of the data "The data stored on Filecoin is all about monitoring data, production data, R&D data, sales data." It seems to me that this type of data is suited for the FIL-E program for business requests. The Filecoin+ program is not the right place for this data.

Your answer 4 worries me a bit because this program is not meant for businesses to provide their clients/customers with free or cheap storage. It is meant to store important information and make the Filecoin network more valuable.

We love to help you and your business onboard customers onto the ecosystem but i recommend you to do the following:

- Store data on filecoin with regular deals (1/100th the costs of AWS)
- Try and do an application on the FIL-E program (business application)

If you need any help, please ask. Thank you.

**Comment by cryptowhizzard** [comment]
It is hilarious for the monday.

Can i just recommend you to not put passwords and sensitive information in your Google drive and then share it?

Second, i have downloaded the documents here. Can you tell me something about RRmine and their relationship to you? I just want to verify that i read and translated all documents correctly here. I am very interested in the amount of nodes they host for you guys etc.

You are sure that you won't store this data on your own nodes right?

[行业部分公司产品信息表 (2).xlsx](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10373270/2.xlsx)
[自媒体账号信息 (1).xlsx](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10373271/1.xlsx)

**Comment by lvschouwen** [comment]
> > Please provide the Chinese name of your organization.
> 
> zhongliankonggu
> 
> website restored

Website is unreachable for me.

**Comment by Carohere** [comment]
Hi @ffff2022, the last Q&A says that your organization has 150 petabytes and 120 PiB are not yet sealed (please correct me if im wrong). I don't understand how can one company get this shockingly huge quota... Please elaborate and disclose the relevant info.
[中链◆问答.pdf](https://github.com/filecoin-project/filecoin-plus-large-datasets/files/10374992/default.pdf)

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 3PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f1f55iw37fqhzxsxcmbsuavixd7uk6h4lu6lfpn2i

**Comment by cryptowhizzard** [comment]
@raghavrmadya @simonkim0515 @Kevin-FF-USA 

Please close this application.
