### ISSUE TITLE
[DataCap Application] Pullman Lijiang

### ISSUE THREAD

**Issue by wyf13** [filecoin-project/filecoin-plus-large-datasets#1486]
### Data Owner Name

Pullman Lijiang

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

http://www.pullmanlijiang.com/

### Social Media

```text
https://space.bilibili.com/680069135?spm_id_from=333.337.search-card.all.click
https://weibo.com/u/1842484960
```

### Total amount of DataCap being requested

4PiB

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f13ytpuyhr5nuhmsadyxdhpil5o3pfv6or4yx6yoa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
As the flagship hotel of Accor's Pullman brand in Greater China, Pullman Lijiang Resort & Spa is located at the foot of Yulong Snow Mountain, enjoying the sacred and ever-changing scenery of snow and ice. Due to its proximity to the ancient town of Shuhe, the hotel also follows the local characteristics by arranging a traditional horse-drawn carriage parade, where people can enjoy the Naxi scenery along the way with the sound of horses' hooves, and embark on a holiday trip to the pure ancient city.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Promotional materials/construction data/ hotel images
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://1drv.ms/u/s!Ap3ecrG5msD6aTxy1x6m5ifPkbQ?e=xvEg8a
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by wyf13** [comment]
@Sunnyiscoming ,Hi, we have saved the design documents since the starting of the the hotel, and i have uploaded more samples as evidence. we would like to store 5 copies if possible, and i am the IT director responsible for servers performance monitoring and storage usage. At present, SPs contacted are f01780906, f01766263,f0454186.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 4PiB

#### Expected weekly DataCap usage rate 
> 150TiB 

#### Client address
> f13ytpuyhr5nuhmsadyxdhpil5o3pfv6or4yx6yoa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!


Ps. 

**None of the SP's you provided are applicable for the FIL+ program. Please check the RULES**

lotus net connect f01780906
f01780906 -> {12D3KooWAD7Nw8keV5psk25H5FC9h29ZCC2dmGkwXPgoXMv6Mzop: []}
ERROR: failed to parse multiaddr "f01780906": must begin with /

lotus net connect f01766263
f01766263 -> {12D3KooWGPn5QGwFufnCSn2iCvMUEfAs8uKyDDQAgJ28v8zPVBhK: []}
ERROR: failed to parse multiaddr "f01766263": must begin with /

lotus net connect f0454186
f0454186 -> {12D3KooWBHwpw2AsRiDj4oVaUZ2pQCFNiSG9KKAeXh8fmuFL8w5k: []}
ERROR: failed to parse multiaddr "f0454186": must begin with /
