### ISSUE TITLE
[DataCap Application] LIGHTING

### ISSUE THREAD

**Issue by Dibaisa** [filecoin-project/filecoin-plus-large-datasets#1487]
### Data Owner Name

LIGHTING

### Data Owner Country/Region

China

### Data Owner Industry

Arts & Recreation

### Website

https://www.gybn100.com/

### Social Media

```text
https://www.douyin.com/user/MS4wLjABAAAA7icNUIQZM-VJkWMDrzocNocPRhpozBnmj0_u74eBqqLy8Y3s5DqLZIKk-paxwGmn
https://www.youtube.com/channel/UCg5iC3V2yBCp8m70dDbioZQ
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f1lxz5sdss6674ruruianbmpztrp5llbiq6rxwvoa

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
LIGHTING Focusing on active immersion "five senses, one sense" cultural tourism night tour; with "more than content, more than experience" as the creation concept, the core content advantages: creative planning + art choreography + interactive R & D + film creation + new media art and the theme of cultural combination, through the fun theme walking line, fantasy shock audio-visual, integrated interactive experience and other applications, passive viewing for active immersion, trigger the five senses, the theme deep into the heart, awakening empathy emotions, to create both "culture + creativity + technology" content-based cultural tourism products.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Own company creative lighting product film recordings.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://www.youtube.com/watch?v=W2bezKDh8AE
https://www.douyin.com/video/7176932603478494524
https://www.douyin.com/video/7150094147083390223
https://www.douyin.com/video/7143891666724850975
https://www.douyin.com/video/7116452245050314014
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

I don't know yet

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
> How do you plan to choose storage providers
> I don't know yet

You can find SPs in the slack channel https://filecoinproject.slack.com/ssb/redirect
Only when you find the right sps can you start using DataCap.

What's the relationship between you and the organization?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Dibaisa** [comment]
> > How do you plan to choose storage providers
> > I don't know yet
> 
> You can find SPs in the slack channel https://filecoinproject.slack.com/ssb/redirect Only when you find the right sps can you start using DataCap.
> 
> What's the relationship between you and the organization?

@Sunnyiscoming , thanks for advise, we have found some sps that willing to coorperate in fil-chinese channel. As for me, i am from interaction development team. kindly let me know if further information required.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 150TiB 

#### Client address
> f1lxz5sdss6674ruruianbmpztrp5llbiq6rxwvoa

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
