### ISSUE TITLE
[DataCap Application] <tuyouhuwai>

### ISSUE THREAD

**Issue by tuyouhuwai** [filecoin-project/filecoin-plus-large-datasets#1492]
### Data Owner Name

Hangzhou Hitu Travel Agency Co., Ltd

### Data Owner Country/Region

China

### Data Owner Industry

Other

### Website

www.tuyouhuwai.com

### Social Media

```text
1、WeChat  public account and video account:  tuyouhuwai
2、Sina Weibo:    https://weibo.com/u/5047583879
3、E-MAIL:   service@tuyouhuwai.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
"tuyouhuwai" travel club is an outdoor travel club based in Hangzhou and radiating to the whole country. It is our core competitiveness to provide outdoor companionship platforms for outdoor enthusiasts, planning, organizing and promoting outdoor light hiking around Jiangsu, Zhejiang and Shanghai, and domestic and foreign light hiking routes.

1. Club history:
      - In 2011, the idea of "tuyouhuwai" travel club was established, introduced the model of acquaintances, and organized activities.
      - In 2013, the WeChat public account of the "tuyouhuwai" travel club was created, promoted on social platforms, and organized activities on a large scale.
      - In 2016, Hangzhou Hitu Travel Agency Co., Ltd. was established, and started process management and compliance operation.

2. In terms of data:
          From 2013 to 2022, the WeChat public account (tuyouhuwai) has 80,000+ followers
There are more than 5,000 registered members, and more than 100,000+ people have participated in our various activities. Now there are more than 80 full-time team leaders in the club, and more than 30 social part-time team leaders.

3. Business scope:
Licensed project: tourism business. General items: consulting and planning services; organization of cultural and artistic exchange activities; personal business services; corporate image planning; marketing planning; outdoor product sales; fitness and leisure activities; information consulting services; passenger ticket agency; campsite services; advertising design, agency; Development and management of rural folk crafts and products, leisure agriculture and rural tourism resources; conference and exhibition services;
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Outdoor landscape shooting, outdoor event shooting, short video shooting.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
1、https://drive.google.com/drive/folders/1An7nTjShn7jA0GiOVQLztEcczcIRc5Zp?usp=share_link
2、Sina Weibo:    https://weibo.com/u/5047583879
3、Most works have been uploaded to the WeChat  public account/video account : tuyouhuwai
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
https://aiqicha.baidu.com/detail/compinfo?pid=23021391656510&rq=ef&pd=ee&from=ps&tab=risk
It seems that your organization has copyright problems, whether the data you want to store this time also has copyright problems?
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
