### ISSUE TITLE
[DataCap Application] Zhitong Finance

### ISSUE THREAD

**Issue by DuoFL** [filecoin-project/filecoin-plus-large-datasets#1497]
### Data Owner Name

Zhitong Finance

### Data Owner Country/Region

China

### Data Owner Industry

Financial Services

### Website

https://www.zhitongcaijing.com/

### Social Media

```text
https://space.bilibili.com/534841237/video
https://www.douyin.com/user/MS4wLjABAAAA38G2hBUdGDbuaxKB0VIsr8tKdRzvxH6hy86gF-YjlisDbrDbK7bbwoTD2A33Ocv6
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1fjq3elwxfirten2ardtuvnuv3aqms2tco3mpkgq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zhitong Finance is a financial information provider and investor relations solution provider website, focusing on Hong Kong and U.S. stock markets and radiating global financial markets such as A-shares and bonds, providing users with information, data, quotes and research information 24 hours a day, 7 days a year, and providing customers with one-stop investor relations solutions.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
published contents,Market data, research reports.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://www.bilibili.com/video/BV1v44y1U7sN/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1J24y1y7no/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1gY411Z7LU/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1Ag411z7Fd/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1xv4y1D71E/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

I don't know yet

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition? How much data do you have? How many copies will you store?
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by DuoFL** [comment]
> Can you explain your data composition? How much data do you have? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

Hi @Sunnyiscoming , till now some of the f01780915, f01788062, f0509980 which are not retrieval. I am the editor, and so far for the history data archives including trading data, reports from listed companys/our own analysis reports are over 600T, and platform contents over 400T, so 5Pb of datacap should be enough for us to store 5 copies.

**Comment by herrehesse** [comment]
@DuoFL hello dear applicant. Can you try and answer the above questionnaire? Thank you in advance.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1fjq3elwxfirten2ardtuvnuv3aqms2tco3mpkgq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
