### ISSUE TITLE
[DataCap Application] <The data from MCN company>

### ISSUE THREAD

**Issue by dpx-office** [filecoin-project/filecoin-plus-large-datasets#1504]
### Data Owner Name

Sichuan Horizon Culture Communication Co. LTD

### Data Owner Country/Region

China

### Data Owner Industry

Information, Media & Telecommunications

### Website

https://www.cddpx.com/

### Social Media

```text
https://www.cddpx.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1fbpvedozoqtijqf4fwkifjhhlg3i2c6twyct2xi

### Custom multisig

- [ ] Use Custom Multisig

### Identifier

None

### Share a brief history of your project and organization

```text
The Sichuan Horizon Culture Communication Co., Ltd. is a first-class MCN agency in China, founded in 2019 and headquartered in Chengdu.
We are an all-round multi-channel cashing new online culture and entertainment ecology company with IP incubation, brand promotion, video media agency operation and other main businesses, with short video as the core. We also provide a series of offline full media training services such as media operation, video creation, video shooting and editing, network operation, and also provide the lessons of advertising optimizer and SEO optimizer.etc.
The company has contracted experts in multiple categories such as games,appearance, animation and agriculture (agriculture, rural areas, farmers), with a total of 500 million+ video views and over 10 million fans.

Since 2021, the company has been responding to the "Rural Revitalisation" plan, incubating a number of new farmers from the perspective of agricultural products, rural culture and rural life, training young people in rural areas on new media production methods and special techniques to attract fans, helping them to introduce the beauty of their hometowns, recommend local cuisine and tell the history and stories of their surroundings.
By exporting diversified quality rural content, the company promotes the transformation of "local memories" into "local economy" and becomes an excellent platform for the incubation of "three agriculture" weblebrities.

The company has accumulated a large number of creators' works in our media operation business for many years, mainly short videos, which currently storage in Ali cloud and Tencent cloud platforms. We were looking for a more efficient, lower-cost storage method with long-term stability, and we were approached by Filecoin SPs who wanted to deposit the data into the Filecoin network and introduced us to decentralized storage field. On the one hand, with the help of the miners, there is no additional cost for us to store this data; On the other hand, we understand that the Filecoin network is moving forward with the Saturn Project to implement CDN capabilities and we would like to participate in the Filecoin CDN network if this is possible.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Most of data we plan to storage is from the original video works of the creators we cooperate with. Video themes are planned and filmed by the company's professional team, then released by the operations team who will continue the subsequent operations.The business partnership generates a large amount of video data and we are keen to find a decentralized storage platform like Filecoin for long-term cooperation.
The volume of data provided is over 1p and we are planning to be stored as 5 copies.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
Aliyun\Tencent Cloud
```

### How do you plan to prepare the dataset

others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here

```text
Self-developed packing tool
```

### Please share a sample of the data

```text
agriculture, the countryside and farmers
https://1drv.ms/u/s!Asy39Y6I4odCapzqHP3iQjvufgs?e=eHK7I4
Society
https://1drv.ms/u/s!Asy39Y6I4odCa9I89fRoYUnBpAg?e=Xa8Hpk
Gastronomy
https://1drv.ms/u/s!Asy39Y6I4odCbNJwthtRRAlzfDo?e=VRhFVq
Comic
https://1drv.ms/u/s!Asy39Y6I4odCabhQ7Aa2BNFrghk?e=5TAkkN
Game
https://1drv.ms/u/s!Asy39Y6I4odCaGV2oseNaLZ2zKI?e=UW5JLg
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent), Antarctica

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How do you plan to choose storage providers

Slack

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f02003553、f02003731、f02004886、f02005062
We will continue to contact more SPs and update their information here.
```

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Can you provide some Internet celebrity accounts that organizations have signed up to? And provide the signed certification materials.
What's the relationship between you and the organization? 
Whether the sps you choose can support data retrieval?

**Comment by dpx-office** [comment]
Hi, @Sunnyiscoming 
I am a member of the operations staff at the company. Regarding partner(Internet celebrity ) information, as privacy is involved, please provide the official email address below and I will send the relevant signing agreement for review. In addition, we have communicated with SP that the data we store is public and supports retrieval, and they will cooperate with a good retrieval configuration.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by kevzak** [comment]
@herrehesse @dpx-office Just to confirm, this application is listed as a public dataset. **E-Fil+ is a pilot program for private datasets**.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1fbpvedozoqtijqf4fwkifjhhlg3i2c6twyct2xi

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing duediligence.

Looking at your application i have some questions:


As you are brand new on Github and have no history of past applications. Applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 

Your application is for 5PB of datacap. Can you show us some visible proof from the datasize and the storage you have there?

Regarding the data itself you mention that it is made by professionals. I presume this is copyrighted then. How can we check that you have permission to store this copyrighted materials?

Can you provide us with a distribution plan supposingly that you would be granted datacap to store? Is the list you provided still accurate?
"f02003553、f02003731、f02004886、f02005062" because if so your LDN request would be denied.

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

I did some testing and none of this SP's are eligible to store data. 

lotus net connect f02003553
f02003553 -> {12D3KooWPo1AXAYVn1dVsbtZDNd6WtyCAcdtCVUdtsCqmfRVXh2f: []}
ERROR: failed to parse multiaddr "f02003553": must begin with /

root@proposals:~/api/fullauto# lotus net connect f02003731
f02003731 -> {12D3KooWDNT4YfVWbLW6r88UXCL3CHJ3TCYXUcD1BUgw7QYdk8xM: []}
ERROR: failed to parse multiaddr "f02003731": must begin with /

root@proposals:~/api/fullauto# lotus net connect f02004886
f02004886 -> {12D3KooWR3kiL1R2bbzTyNHYMQBRpahnfZLgVrAWergSW9QK2k1K: []}
ERROR: failed to parse multiaddr "f02004886": must begin with /

root@proposals:~/api/fullauto# lotus net connect f02005062
f02005062 -> {12D3KooWLz6CxBpUo6oubT49VxnxCsyoDAWFv5QDhu2rW9sxKFVk: []}
ERROR: failed to parse multiaddr "f02005062": must begin with /

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's are included.

**Comment by cryptowhizzard** [comment]
Hello @dpx-office 

Thanks for your clarification.

I can move ahead once i get the data i need. ( Sp's + Contact information ).

**Comment by dpx-office** [comment]
> Hello @dpx-office
> Thanks for your clarification.
> I can move ahead once i get the data i need. ( Sp's + Contact information ).
@cryptowhizzard thanks for your work,SPs info is disclosed as follows,please help us to sign the first round.
Sp id --------- Region------name------- Org
f02003553  ----   CN	  ------   Yang    ---- ---- Chengdu Jusha Cheng Box Technology Co., LTD 
f02003731   ----  SGP   ------  Gaobo  ------  AirBook Private Limited 
f02005062  ----   HK	 ------    kingkuang   ----   kingkuang
f02004886   ----  SGP    ------    Downey  ------ MetaOne Deta Ltd

**Comment by dpx-office** [comment]
Hello@cryptowhizzard, regarding the application, is there anything else you need to know? What else can I do to facilitate the application process? Please let me know, many thanks.

**Comment by OpenGate01** [comment]
Since this is currently the first round of applications, there are no bot check results available for review. We think this application meets the Fil+ criteria based on the applicant's description and the distribution plan.

**Comment by OpenGate01** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtiqixpcwjmdjht355f6igfe547gp7rbyoy6dihck7gmzcfispyk 
#### Address 
> f1fbpvedozoqtijqf4fwkifjhhlg3i2c6twyct2xi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f1im4hmtbfzqnx7ir74kdaiu4ynjhgqh3sdi2snla
#### Id
> 603acfae-2992-49ef-966d-22bc4d1353d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtiqixpcwjmdjht355f6igfe547gp7rbyoy6dihck7gmzcfispyk

**Comment by METAVERSEDATAMINING** [comment]
I noticed that the SPs you provided are concentrated in Asia. 
According to FIL+ rules, storage needs to be distributed across at least three regions. 
Since this is the first allocation and there is room for improvement, I will mark this application.
Will approve this round

**Comment by METAVERSEDATAMINING** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebskwnt5sbnvbgraztntlbrzzza23h37amirgjd2lg2uhpholfddg 
#### Address 
> f1fbpvedozoqtijqf4fwkifjhhlg3i2c6twyct2xi
#### Datacap Allocated
> 100.00TiB
#### Signer Address
> f17idrnfnxl2mbgcgr57a6z2c6lj2qx56gvm3336i
#### Id
> 603acfae-2992-49ef-966d-22bc4d1353d5
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebskwnt5sbnvbgraztntlbrzzza23h37amirgjd2lg2uhpholfddg

**Comment by dpx-office** [comment]
checker:manualTrigger

**Comment by dpx-office** [comment]
The bot hasn't triggered yet here , I need your  help. @simonkim0515 @Sunnyiscoming @fabriziogianni7 



I need your help.

**Comment by dpx-office** [comment]
How to expedite the application process? Has the issue with the bot been resolved? @fabriziogianni7

**Comment by dpx-office** [comment]
checker:manualTrigger

**Comment by dpx-office** [comment]
Please help manually trigger the allocation. The current tag display is abnormal@fabriziogianni7 @simonkim0515

**Comment by dpx-office** [comment]
We are currently in the waiting stage for the notary's review, and  making efforts to seek their assistance.

**Comment by dpx-office** [comment]
Still waiting to be reviewed....

**Comment by kernelogic** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedslbm6eej3g7f7fzbwovtp2gk2tjx5ehwlbucdrdb4w5cqdv5rqw 
#### Address 
> f1fbpvedozoqtijqf4fwkifjhhlg3i2c6twyct2xi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yjhnsoga2ccnepb7t3p3ov5fzom3syhsuinxexa
#### Id
> edfbd0b6-9119-4340-8f2d-073ab49a4159
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedslbm6eej3g7f7fzbwovtp2gk2tjx5ehwlbucdrdb4w5cqdv5rqw

**Comment by NDLABS-OFFICE** [comment]
checker:manualTrigger

**Comment by dpx-office** [comment]
This is currently the second distribution and the report information is incorrect.
Next, new service providers will join in, with quotas more dispersed, and storage will be significantly improved.

**Comment by NDLABS-OFFICE** [comment]
@dpx-office  Thanks for the explanation, it seems to me that the distribution has different onboarding speed does have this, hope to see a healthier report in the next round of check bot. No data sharing which is good and willing to support.

**Comment by NDLABS-OFFICE** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnpq2iv36jdaawo74a5r7bvffrzgkl3wefunpbyljjjvl6stvmrq 
#### Address 
> f1fbpvedozoqtijqf4fwkifjhhlg3i2c6twyct2xi
#### Datacap Allocated
> 200.00TiB
#### Signer Address
> f1yayfsv6whu3rheviucvventj3y6t542xfpb47ei
#### Id
> edfbd0b6-9119-4340-8f2d-073ab49a4159
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnpq2iv36jdaawo74a5r7bvffrzgkl3wefunpbyljjjvl6stvmrq

**Comment by dpx-office** [comment]
status update

**Comment by dpx-office** [comment]
Data Prep Phase...

**Comment by dpx-office** [comment]
PAUSE

**Comment by dpx-office** [comment]
Data Prep Phase...

**Comment by dpx-office** [comment]
In preparation.

**Comment by dpx-office** [comment]
In preparation.

**Comment by dpx-office** [comment]
In preparation

**Comment by dpx-office** [comment]
In preparation

**Comment by dpx-office** [comment]
In preparation

**Comment by dpx-office** [comment]
Please keep it open.

**Comment by dpx-office** [comment]
In preparation

**Comment by dpx-office** [comment]
In preparation

**Comment by dpx-office** [comment]
In preparation

**Comment by yvetteoor** [comment]
please keep it open

**Comment by dpx-office** [comment]
Please keep it open

**Comment by dpx-office** [comment]
In preparation

**Comment by Sunnyiscoming** [comment]
Hello, @dpx-office per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by dpx-office** [comment]
checker:manualTrigger

**Comment by dpx-office** [comment]
@Sunnyiscoming  The form is complete.

**Comment by Filplus-govteam** [comment]
SP list provided:
f02031264 |  oliver lu | SGP | yes | oliver
f0442671 | liang zhong | HK | yes | zl
f01980952 |  king kuang | CN | no | king
f02003553 |  yang | CN | no | none
f02003731 |  AirBook Private Limited | SGP | no | none

SPs taking deals:

f02031264 | Singapore, Singapore, SGAmazon.com, Inc. | 74.88 TiB | 41.58% | 74.88 TiB | 0.00%
f0442671 | Hong Kong, Central and Western, HKAmazon.com, Inc. | 24.00 TiB | 13.33% | 24.00 TiB | 0.00%
f01980952 | Chengdu, Sichuan, CNChina Mobile Communications Group Co., Ltd. | 81.19 TiB | 45.09% | 81.13 TiB | 0.08%

**Comment by herrehesse** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
f02031264 | oliver lu | SGP | yes | oliver FAKE VPN
f0442671 | liang zhong | HK | yes | zl FAKE VPN
f01980952 | king kuang | CN | no | king REAL LOCATION

This client most likely 100% self-dealing to the same entity. Provide evidence of location or close this LDN.
Over 40% of datacap goes to the same miner. Against the rules.

**Comment by dpx-office** [comment]
Please keep it open

**Comment by Sunnyiscoming** [comment]
SP List provided:
{"providerID":"f02031264","City":"XYZ","Country":"SGP","SPOrg","XYZ"},
{"providerID":"f0442671","City":"XYZ","Country":"HK","SPOrg","XYZ"},
{"providerID":"f01980952","City":"XYZ","Country":"CN","SPOrg","XYZ"},

**Comment by dpx-office** [comment]
Please keep it open

**Comment by dpx-office** [comment]
Please keep it open

**Comment by dpx-office** [comment]
Please keep it open
