### ISSUE TITLE
[DataCap Application] Speedium - Distributed Archives Neurophysiology Data Integration (DANDI) [2 / 3] 

### ISSUE THREAD

**Issue by herrehesse** [filecoin-project/filecoin-plus-large-datasets#1515]
### Data Owner Name

Massachusetts Institute Of Technology

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.dandiarchive.org/

### Social Media

```text
https://github.com/dandi
https://twitter.com/dandiarchive
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Since its launch, the Filecoin network has become an important player in the decentralised storage space, offering a secure and transparent alternative to traditional data storage solutions.

We as Speedium / DCENT have been engaged with storing real and valuable datasets on the Filecoin network since Slingshot 2.6 and have been actively developing tools to improve the process. We are always on the lookout for new and useful client data to onboard.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
DANDI is a public archive of neurophysiology datasets, including raw and processed data, and associated software containers. Datasets are shared according to a Creative Commons CC0 or CC-BY licenses. The data archive provides a broad range of cellular neurophysiology data. This includes electrode and optical recordings, and associated imaging data using a set of community standards: NWB:N - NWB:Neurophysiology, BIDS - Brain Imaging Data Structure, and NIDM - Neuro Imaging Data Model.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

IPFS, lotus, singularity, others/custom tool

### Please share a sample of the data

```text
https://registry.opendata.aws/dandiarchive/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
We do not know the exact providers in advance.
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Hi,

Hidde is taking over part of my work here. This one is valid for Speedium / Dcent as followup for my previous requests.

**Comment by raghavrmadya** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 1PiB

**Client address**

> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y

**Comment by xingjitansuo** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebscsetrgbdiptw3rhwurty7ftncnwhwmrnjsemxaku75nun6jc7u 
#### Address 
> f1xlnnzzl2d73amahvsu5uyfwdascodwtw6lopw5y
#### Datacap Allocated
> 475.76TiB
#### Signer Address
> f1a2lia2cwwekeubwo4nppt4v4vebxs2frozarz3q
#### Id
> 7fe8a054-104f-464b-b6c6-4d0752bb7fd9
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebscsetrgbdiptw3rhwurty7ftncnwhwmrnjsemxaku75nun6jc7u

**Comment by kernelogic** [comment]
Public data. Willing to support.

**Comment by yuyuhe123** [comment]
Why can you apply for so much data (30P) on your own, and on behalf of different organizations
Are you an administrator of FIL+？

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1516
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1514
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1513
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1512
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1511

**Comment by laff2022** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

Customer data

Could you demonstrate exactly how and to what extent customer contact occurred?
We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

Did the customer specify the amount of data involved in this relevant correspondence?

Why does the customer in question want to use the Filecoin+ program?

Should this only be soley for acquiring datacap this is of course out of the question. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network.

Why is the customer data considered Filecoin+ eligible?
(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)

Files and Processing

Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?
Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by chuangyuhudong** [comment]
To make this clear, you are a storage provider but also platform?

This seems very vague to me and just a way to grow your miner with the FIL+ multiplier.

I do not support this kind of request in any way and would advise notaries not to sign.

**Comment by herrehesse** [comment]
I find it very childish of the applicant in question (@chuangyuhudong) to respond in this way, as it is a copy of a response from me to one of his own datacap requests, which is doubtful to be following the Filecoin+ ecosystem rules.

Is this the level we have descended to?

I would love to have an adult level discussion about the misused datacap for fraudulent practices or completely useless files. The Filecoin+ program is meant to advance the entire Filecoin ecosystem by increasing the value of data storage, it is now mostly used for personal gain and abusive growth with spoofed files or fake data. 

It has to stop, 99% down from our all-time-high is enough.
@raghavrmadya @cryptowhizzard

**Comment by cryptowhizzard** [comment]
REQUEST MOVED TO: #1550

**Comment by simonkim0515** [comment]
Closing due to new application created.

**Comment by BDEio** [comment]
@herrehesse Hi! Congratulations on your DataCap approval！
BDE is a verified deals auction house helping you to get paid storing your data with reliable storage providers. If you need any help, please get in touch.
