### ISSUE TITLE
[DataCap Application] Xuebao app

### ISSUE THREAD

**Issue by MedFFF** [filecoin-project/filecoin-plus-large-datasets#1520]
### Data Owner Name

Xuebao app

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

https://www.xuebao100.cn/

### Social Media

```text
https://space.bilibili.com/660002952
https://www.douyin.com/user/MS4wLjABAAAAvaW5ek4KB1g6BbMSotZjsCWjBtdbWa9thiWObUAWdz8
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1wiovtfh7jh3kipzjiewourocpog22zisgecrnci

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
XueBao is a technology education company that focuses on synchronous learning and synchronous tutoring for primary and secondary schools. Through the learning method of "synchronous learning + synchronous practice", it builds synchronous learning scenarios for students in all subjects, closely follows the teaching materials, and provides personalized and systematic synchronous learning solutions for families of primary and secondary students.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Learning materials, class recordings, in-app contents.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

lotus

### Please share a sample of the data

```text
https://www.bilibili.com/video/BV1t5411L783/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1G64y1f7mG/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1fa411F73D/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1BK4y1f7GK/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
https://www.bilibili.com/video/BV1zp4y1r7xu/?spm_id_from=333.999.0.0&vd_source=95344eff1314639246a4c1cc8aec93ce
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization? 
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 200TiB 

#### Client address
> f1wiovtfh7jh3kipzjiewourocpog22zisgecrnci

**Comment by cryptowhizzard** [comment]
Seems all this content is author copyrighted and not allowed for distribution or replication without permission.

We can't store this on FIL+ without permission from the author.

![Scherm­afbeelding 2023-01-16 om 14 32 18](https://user-images.githubusercontent.com/36404435/212690320-ca78cc97-b206-4e95-89ed-5e0619d1e169.png)

**Comment by Sunnyiscoming** [comment]
Close for no update here.
