### ISSUE TITLE
[DataCap Application] <Shanghai Puying> - <Power equipment document>

### ISSUE THREAD

**Issue by lele-cool** [filecoin-project/filecoin-plus-large-datasets#1540]
### Data Owner Name

Shanghai Puying Electric Power Engineering Co. LTD

### Data Owner Country/Region

China

### Data Owner Industry

Construction, Property & Real Estate

### Website

https://www.puying-pro.com

### Social Media

```text
https://www.puying-pro.com
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f12ux7q62zbcthnj2fogt6igd6rwnbsk7eiwsiyxq

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shanghai Puying Electric Power Engineering Co., LTD., founded on September 25, 2012, is a comprehensive company with general contracting as the main body and integrating technology, industry and trade. Since its establishment, all staff work together, in good faith, active development, quality service spirit and professional, conscientious, responsible concept began a new period of all-round development.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Since its establishment in 2012, Shanghai Puying Electric Power Engineering Co., Ltd. has trained countless elites in the power engineering industry. I have accumulated about 7 PB of power equipment tutorial videos, covering the usage videos, operation videos and installation videos of almost all types and models of power equipment in the market. More tutorials will follow as companies grow, upgrade technology, and upgrade equipment
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, singularity, graphsplit

### Please share a sample of the data

```text
https://drive.google.com/file/d/1Id3Nu-xPa3w2Sq4bGOHLT9CZczemdJBo/view?usp=share_link
https://drive.google.com/file/d/1fQByT-SB7n-LxraRHPR6QDPToZQxVwvB/view?usp=share_link
https://drive.google.com/file/d/11QNb7VhWyjNY4rePZ05HkD5Ja6Vp-PTo/view?usp=share_link
https://drive.google.com/file/d/1nfZVha80DRJZxKCJ37EW-H5jBhKFcRm7/view?usp=share_link
https://drive.google.com/file/d/14aR17OzQlUaxTHMK72XMdWdgSR-Fr5Pe/view?usp=share_link
https://drive.google.com/file/d/1x9az6F8fA2_n0D1ADHIPoj8PiTrGod_r/view?usp=share_link
https://drive.google.com/file/d/1kP7bH-HetinuY4wG-WpctKjMJt61jFv8/view?usp=share_link
https://drive.google.com/file/d/1fH7WQT95VZEYd_BDMS_HI60B7V2Bgdsv/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers

Shipping hard drives

### How do you plan to choose storage providers

Slack, Big data exchange, Partners

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
**@lele-cool thank you for your application.
Can you provide answers to the questions below?**

Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
The website is not available. Please check it. 
Please 
What's the relationship between you and the organization? 
Can you provide more detailed information about storage providers participated in this program, such as you can list SPs you have contacted with at present? Whether the sps you choose can support data retrieval?

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 100TiB 

#### Client address
> f12ux7q62zbcthnj2fogt6igd6rwnbsk7eiwsiyxq

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 
Your application is for 5PB of datacap. Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included. 

As last thing I have a question about the data. The videos are not from the company and website your provided. It is from czzkplc.com. I understand the logic of programmable logic controllers and these are education videos for the controllers and how these things work. I have contacted the website owner but have not received an email reply. Can you ask him to send an e-mail to the same KYC address with a statement that you are authorised to distribute these video's on the Filecoin network?

**Comment by lele-cool** [comment]
Hello @cryptowhizzard, I have sent the email. Address: postmaster@puying-pro.com, please check.

**Comment by cryptowhizzard** [comment]
Thanks and well received. I replied back for some extra documents.

In the meantime can we work on this? 

"To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included."

In our onboarding form we have some questions that i will now ask here.

>>

![Scherm­afbeelding 2023-01-30 om 14 25 53](https://user-images.githubusercontent.com/36404435/215489968-6334eca1-f498-4d61-8291-44085d1a567f.png)

**Comment by ipollo00** [comment]
@lele-cool Are you still replying for this application?
