### ISSUE TITLE
[DataCap Application] <Changsha Shibei Information Technology Co., Ltd>

### ISSUE THREAD

**Issue by ZoeDTiger** [filecoin-project/filecoin-plus-large-datasets#1547]
### Data Owner Name

Changsha Shibei Information Technology Co., Ltd

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

http://www.wbeke.com/

### Social Media

```text
http://www.wbeke.com/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1micjkasdhtjdg5pafnv7h3tv6wtdjc6hiu6znci

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Changsha Shibei Information Technology Co., LTD., founded in 2019, forces on teaching training and career planning. 

It aims at helping students improve their technical skills, strengthen their core competitiveness of workplace, and overcome their career difficulties. 

Now, live courses about Java architecture, artificial intelligence, big data, software testing and Web front-end are offered. 

The number of online students has exceeded 1 million, and the number of VIP students has exceeded 30,000. 

With the growth of company's business, Shibei stands out in the high-end IT technology online education industry, becoming a dark horse in this field.

By gathering a number of domestic Internet famous celebrities, Changsha Shibei Information Technology Co., Ltd. has a strong ability of curriculum research and development and innovation. 

Combined with the practical application scenarios to teach classic design ideas, the implementation of online education 8S service system (enrollment evaluation, student status management, supervised learning, bonus learning management, graduation certification, employment internal promotion, lifetime membership, course iteration) makes majority of students  have lifelong benefits.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Videos for teaching, PPT for courses, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus

### Please share a sample of the data

```text
http://www.youliao.ren/f/d18ad24f-dc88-49d9-aaaa-b33a52adbd96.mp4
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose storage providers

Slack

### How do you plan to make deals to your storage providers

Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by lvschouwen** [comment]
Hi @ZoeDTiger 

Thanks for your interest in the FIL+ program. Back in September 2022 you also applied for datacap and closed your application. What was the reason for closing your application in September 2022 and reapplying now?

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/953

**Comment by ZoeDTiger** [comment]
Hi @lvschouwen 

We used a new domain name and migrated the website.   And our work had some delays due to the coronavirus.

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by ZoeDTiger** [comment]
We are happy to answer your questions.  We think that doing the due diligence for each applicant is an important step to ensure proper allocation and use of DataCap, which can make the community more open, fair and impartial.

####Customer data

We provide students with multi media live streaming teaching and record the teaching process.  Moreover, recording videos and then sharing them with students is another way of teaching.  We store multiple data sets which are classified by course type, student class, and so on.  These data sets are generated by our faculty in the process of spreading knowledge, so the intellectual property of these data sets belongs to us.  I think "we" is the "customer" in the question.

After years of teaching, we have accumulated a large number of instructional videos. We hope to store the corresponding data sets in the past on a useful, public and open platform so that everyone can use them. Filecoin+is very suitable for storing these data sets, So we submitted a DataCap request.

We know that knowledge is the most important asset of mankind, so the way to acquire knowledge is very important. We also believe that useful information will increase  the consensus about Filecoin.

These data sets are stored on hard disk in the data center. and the size of each data sets is specified, from which we can determine how much DataCap is required.

####Files and Processing

The server where we currently store the data sets is hosted at a local IDC data center, where we download, package, and send these data sets.  We have applied for a 10Gbps optical port from the carrier, which is sufficient to handle daily data transmission and send it to the selected storage provider.  And we will also make data processing capability an important condition for selecting storage provider.

Developing centralized system is what we do best.  We give each data that needs to be packaged a unique ID, save the record to centralized database, and do a simple comparison each time we package to avoid repackaging the data sets.

I expect to have informed the community with this information,and let me know if there are any other questions.

**Comment by herrehesse** [comment]
@ZoeDTiger thank you for your detailed answer. I do not agree with some of your statements but I would like to ask you, how much video's are you talking about because:

- 5 PiB of HD video is 444 THOUSAND hours

If you want to do this, I suggest you begin with 50T of datacap and show the community that the files are perfectly retrievable and spread across multiple miners on different continents and cities. Full transparency.

**Comment by simonkim0515** [comment]
## Datacap Request Trigger

#### Total DataCap requested 
> 5PiB

#### Expected weekly DataCap usage rate 
> 500TiB 

#### Client address
> f1micjkasdhtjdg5pafnv7h3tv6wtdjc6hiu6znci

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As notary i am screening your application and doing due diligence.

Looking at your application i have some questions:

As you are brand new on Github and have no history of past applications. Applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing data and it's requirements and distribution of the data. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you provide me with some KYC details per e-mail at kyc@dcent.nl. I would like to receive an e-mail from the original domainname / contact as listed on the website that refers to this application. 
Your application is for 5PB of datacap. Can you show us some visible proof from the data size and the storage you have there?

Can you provide us with a distribution plan supposably that you would be granted datacap to store?

As you can see here : https://github.com/filecoin-project/filecoin-plus-large-datasets it states:

> In order for a client and their dataset to be eligible:
> the dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone > in the network, without requiring any special permissions or access requirement
> stored data should be readily retrievable on the network and this should be regularly verified (though the use of manual or automated verification > that includes retrieving data from various miners over the course of the DataCap allocation timeframe)

To make sure that you understand the rules and guidelines I would like to receive a detailed allocation plan where the amount of data and reputational SP's where you are going to store this data are included. 

Ps. Your website is offline.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by ZoeDTiger** [comment]
@cryptowhizzard @simonkim0515 Thank all notaries very much for your attention and questions. I'm sorry for not answering your questions in time.

For the passed several weeks, we have experienced the Chinese New Year and the enrollment and opening ceremony of new students, which are very time consuming.

To facilitate the presentation of the data, we have reclassified some of the data by technical type and migrated it to an FTP server, which can be seen by typing ftp://120.226.39.177 in "My Computer".

<img width="1080" alt="20230228094924" src="https://user-images.githubusercontent.com/100336530/221735851-ce42178b-0cb3-4cc3-a459-a8e64631b855.png">

Enter the following address in your browser to view the sample data:
http://www.youliao.ren/f/106bab9e-4772-441c-9cbe-bd3320a1aadf.mp4
http://www.youliao.ren/f/20d61280-9666-472a-ab9b-fe7d6b51f3d1.mp4
http://www.youliao.ren/f/5d062922-78f0-4abb-bc50-d762df82a49f.mp4
http://www.youliao.ren/f/5f8f60cd-0d91-4464-925a-36230e3b8f40.mp4
http://www.youliao.ren/f/754207ea-4a31-498c-8267-4fe62f7d3394.mp4
http://www.youliao.ren/f/7a307ec9-a527-4ccb-bb71-4f65838a20bb.mp4
http://www.youliao.ren/f/7d85b694-2199-4d82-9f99-08e484d537c2.mp4
http://www.youliao.ren/f/a88f033b-d70e-4e9f-accf-344cc1608098.mp4
http://www.youliao.ren/f/c473ef4c-d148-4127-bbb5-b7045e8d74c0.mp4
http://www.youliao.ren/f/c52321d2-16d5-4963-b526-a037f9588a4e.mp4

**Comment by ipollo00** [comment]
@ZoeDTiger Hey, are you still applying? Do you mind share with us your SPs onboarding plan?
