### ISSUE TITLE
[DataCap Application] <NHAM> - <Data Storage>

### ISSUE THREAD

**Issue by DCFIL** [filecoin-project/filecoin-plus-large-datasets#1548]
### Data Owner Name

New Huo Asset Management (Hong Kong) Limited

### Data Owner Country/Region

Hong Kong

### Data Owner Industry

Financial Services

### Website

https://www.nhasset.com/en-us/

### Social Media

```text
https://www.nhasset.com/en-us/
```

### Total amount of DataCap being requested

5PiB

### Weekly allocation of DataCap requested

700TiB

### On-chain address for first allocation

https://filfox.info/zh/address/f01791896

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Established in 2019, New Huo Asset Management (Hong Kong) Limited ("NHAM")  is a wholly-owned subsidiary of New Huo Tech and holds the Type 4 and 9 licenses of the Hong Kong Securities and Futures Commission. 

NHAMM is a new-era asset management institution that bridges the gap between digital assets and traditional finance by offering a regulated, secure and frictionless investment experience.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
With the rapid growth and increasing importance of virtual assets, it has become a new investment hotspot for both institutional and individual investors. Virtual assets fund not only provides an easy access for investors but also the benefits of diversification, professional management, risk control, secured custody of assets and so on.
In the past five years, virtual assets represented by Bitcoin and Ethereum have gradually been recognized by mainstream institutions. The scale of asset management in the virtual assets has increased by nearly 140 times, and the market value of Bitcoin has exceeded one trillion U.S. dollars.
The admission of high-net-worth individuals and institutional investors are accelerated.
New Huo Asset Management (Hong Kong) Limited (“NHAM”) provide customers with innovative and diversified products and services that represent cutting-edge investment concepts and make socially responsible investments with investors.
NHAM holds Type 4 License (Advising on Securities), providing research reports on various types of securities (industry or individual stock analysis reports, etc.,). Also, NHAM can provide investment advice to clients (financial advice, such as asset allocation, buying and selling securities, etc.)
NHAM also hold Type 9 License (Asset Management), providing management account, manage the investment portfolio of the special account (Discretionary Account) NHAM can issue and manage various funds in the form of discretionary management account.
Throughout the whole operation and investment procedure, NHAM needs to collect as much as data, screen these raw data and develop its own strategy. Also, NHAM needs to do the back test via its strategy. These data analyses and strategy development requires a big data storage.
In addition, NHAM will share some market reviews, which is public for all people.
We hope these data can be stored in different storage form with a low cost and secure guarantee.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### How do you plan to prepare the dataset

I don't know yet

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1bTB0BYEY9FC4981oae0n4nLiRyKiPsQk?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

I don't know yet

### How do you plan to choose storage providers

Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
Node ID: f01791896
Node ID: f01488667
```

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by DCFIL** [comment]
The address is: f3s54sgr5wlwiwpdhcsevbxk7nnmhncg42aodv4grpzzmeo3d6fiydaldcv3ub4znvkwuh2ww5ekcjjc7g6waq


>

**Comment by cryptowhizzard** [comment]
@DCFIL this is the address of your miner.

What is the wallet address you intend to use to send the storage deals from?

**Comment by lvschouwen** [comment]
@DCFIL 
Both SPs you mention in your application do not have their IP announced to the network. Can you work with your SP(s) first to get this resolved?

f01791896 -> {12D3KooWGzZG4JaZxAhrV7ThpR5LarpVLwNgaoMjyGP5MLzyrV61: []}
f01488667 -> {12D3KooWQyysjqLVjCosCef7wr8GNE3Jrd3Hg4ehJwjWRBDH3ReZ: []}

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Data sample requires access permissions, please check it.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by stcouldlisa** [comment]
<img width="697" alt="WX20230227-170855@2x" src="https://user-images.githubusercontent.com/112812896/221521117-265ac476-4eed-4b32-908c-643149189d14.png">

**Comment by stcouldlisa** [comment]
@DCFIL Unable to open, please give permission
