### ISSUE TITLE
[DataCap Application] <Organization> - <Project Name>

### ISSUE THREAD

**Issue by ymyglbt** [filecoin-project/filecoin-plus-large-datasets#1565]
### Data Owner Name

广州数字宇宙码链云科技有限公司

### Data Owner Country/Region

China

### Data Owner Industry

Web3 / Crypto

### Website

www.tcpyj.com

### Social Media

```text
抖音、微信短视频
广州数字宇宙码链云科技有限公司成立于2018年，立足于互联网科技，是一家跟随和迎合时代发展趋势走的科技公司，从事研究区块链技术、元宇宙建设、web3.0、数字虚拟人、数字产品、自动化、人工智能、大数据、云计算等，随着互联网的向前发展，我们人类最终的发展方向必定是物联网，万物互联，区块链技术改变了web1.0和web2.0的互联网模式，正式迎来web3.0，元宇宙、web3.0的到来，必定改变人类原有的生活方式，让我们一起努力，创建数字版权、赋能实体经济和元宇宙，用区块连和元宇宙服务于政务，为社会创造更多的福利，让科技改变和提高生产力，促进社会的发展，造福人类！
```

### Total amount of DataCap being requested

100TiB

### Weekly allocation of DataCap requested

10TiB

### On-chain address for first allocation

www.tcpyj.com

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
广州数字宇宙码链云科技有限公司成立于2018年，立足于互联网科技，是一家跟随和迎合时代发展趋势走的科技公司，从事研究区块链技术、元宇宙建设、web3.0、数字虚拟人、数字产品、自动化、人工智能、大数据、云计算等，随着互联网的向前发展，我们人类最终的发展方向必定是物联网，万物互联，区块链技术改变了web1.0和web2.0的互联网模式，正式迎来web3.0，元宇宙、web3.0的到来，必定改变人类原有的生活方式，让我们一起努力，创建数字版权、赋能实体经济和元宇宙，用区块连和元宇宙服务于政务，为社会创造更多的福利，让科技改变和提高生产力，促进社会的发展，造福人类！
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
fil代币交易以及购买持有
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### Please share a sample of the data

```text
www.tcpyj.com
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How do you plan to choose storage providers

Partners

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Total amount of DataCap being requested
100TiB

Fil+ large dataset serves as the hub for client applications for DataCap at a large scale - currently defined as > 500 TiB of DataCap. Please apply to notaries.

**Comment by herrehesse** [comment]
Dear Applicant @ymyglbt,

_(Can i kindly ask you to do the application in English, no one can read it at the moment)_

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Close for no reply.
