### ISSUE TITLE
[DataCap Application] Corrupted Pixels

### ISSUE THREAD

**Issue by ghost** [filecoin-project/filecoin-plus-large-datasets#1622]
### Data Owner Name
Corrupted Pixels

### Data Owner Country/Region
Germany

### Data Owner Industry
Arts & Recreation

### Website
[https://corrupted-pixels.art](https://corrupted-pixels.art)

### Social Media
@corrupted_art (Twitter)

### Total amount of DataCap being requested
5 PiB

### Weekly allocation of DataCap requested
1 PiB

### On-chain address for first allocation
f173ijffhxb4pnaugwqexy3cf6zkalrclstumwocq

### Custom multisig
No

### Share a brief history of your project and organization
Corrupted Pixels is innovating in the NFT space.  We are combining NFTs, gamefi, storfi, high end technology and social engineering into art. Passionate about the future of web3, our DNA woven into the fabric of technology we care deeply about the success of collaborative, decentralized technology! 

### Is this project associated with other projects/ecosystem stakeholders?
Yes

### If answered yes, what are the other projects/ecosystem stakeholders
Yes. Most to all of our team members have deeply rooted connections in the filecoin community. Storage Providers, Community Participants, Projects, StartUps, Officials

### Describe the data being stored onto Filecoin
The dataset contains NFT data used in our Art installation(s)

### Where was the data currently stored in this dataset sourced from
Other

### If you answered "Other" in the previous question, enter the details here
The data we use for our art installation(s) is the result of sophisticated use of technology combined with a cultural aspect rooted in our personal socialization. 

### How do you plan to prepare the dataset
others/custom tool

### If you answered "other/custom tool" in the previous question, enter the details here
We will use custom tooling to prepare the data for collaborative storage on the Filecoin network

The tool we are using to create our NTF art is written with Filecoin in mind and will allow friction-less data on boarding onto the network

### Please share a sample of the data
Yes. We can and will provide data samples as needed by notaries

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
We will not provide, so called, online retrieval out of the box. In later phases of the project we will discuss with collaborating SPs if it is desirable to provide, so called, online retrieval. The data will be accessible to anyone as needed and we can provide access at all time

### What is the expected retrieval frequency for this data
Yearly

### For how long do you plan to keep this dataset stored on Filecoin
Permanently

### In which geographies do you plan on making storage deals
Global

### How will you be distributing your data to storage providers
Others

### How do you plan to choose SP
Other

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
We seek to collaborate with SPs that are collaborating with a notary. We plan to find additional SPs via auctioning platforms

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
We are currently not collaborating with any particular SPs. This application seeks to find SPs to collaborate with to allow a friction-less on boarding of the data to the network

### How do you plan to make deals to your storage providers
Others/custom tool

### If you answered "Others/custom tool" in the previous question, enter the details here
Please see "Data preparation Plan" above.

We plan to store 5 copies with SPs that collaborate with notaries to streamline initial storage. 5 additional copies are planned to be stored with random SPs (See "Storage provider selection plan" above)

### Can you confirm that you will follow the Fil+ guideline
Yes

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!

**Comment by corrupted-pixels** [comment]
Dear Crypto Whizzard,

Thank you for showing interest in our application. 

Please refer to our art collectives website regarding the nature of the data we intend to store and how the technical side of a data on baording process will potentially look like. We are not new to the Filecoin space. No member of our collective has applied for datacap in the past. The github account is brand new as we do not seek to have our members personal social (and professional) networks play a role in our art collectives work in the Filecoin Space.

After scrolling a bit if found your recent notary application on https://github.com/filecoin-project/notary-governance/tree/main/notaries. To us it is currently not clear whom exactly we would potentially provide personal data to via [this form](https://form.jotform.com/230337462961356). Can you  give us a little bit more insight why you choose a non GDPR compliant free-form provider and what entity, Speedium or Dcent, will process the data potentially provided through that form and how GDPR compliant handling of said data will be ensured?

You mention in your notary application that you plan to onboard "user content (personal user storage)", "scientific datasets (AI training, geological data, autonomous driving)", " media & entertainment (video & music)". Our project falls not in these categories but "Arts & Recreation". Is there a precedent when a dissonance between a notaries listed use cases and a projects use case has been detrimental for an application? Is there even a rule in writing regarding the issue of use case categories and how clients/notaries are supposed to handle these? It would be nice if you, as an expert in the field of Filecoin Plus governance could give us some insight on this topic!

Given that your notary seems currently under scrutiny regarding a mishandled datacap signature, see discussion https://github.com/filecoin-project/notary-governance/discussions/827#discussioncomment-5003208, we would like to wait until that issue is resolved before pursuing a consideration from your side for our datacap application. We are not sure if you will be able to provide the notary services needed for the long lasting friction-less on-boarding experience we seek for our projects data. 

As soon as the issues is resolved we will be happy to reconsider your consideration.

In you notary application we noticed that you collaborate with plenty of SPs. Would it be possible to to let them know about our application? We would like to discuss a potential collaboration with these SPs regarding the storage of our data.

Thanks for you time!

**Comment by swatchliu** [comment]
Hi buddy, hold my German beer and enjoy your journey of exploration!

**Comment by Sunnyiscoming** [comment]
Hi @corrupted-pixels 
Because of the amount of application is up to 5PB, it is better for you to describe in detail about the source, type and corresponding data samples of the data you want to store. It will help the notary review your application quickly.

**Comment by RobQuistNL** [comment]
> Hi @corrupted-pixels Because of the amount of application is up to 5PB, it is better for you to describe in detail about the source, type and corresponding data samples of the data you want to store. It will help the notary review your application quickly.

In contrast to other applications, this one actually has all the data and explanations lined out on their website.
And in contrast to other applications, this website is actually online, is in English, works, and has no dead links or Lorem Ipsum text!

**Comment by cryptowhizzard** [comment]
> > Hi @corrupted-pixels Because of the amount of application is up to 5PB, it is better for you to describe in detail about the source, type and corresponding data samples of the data you want to store. It will help the notary review your application quickly.
> 
> In contrast to other applications, this one actually has all the data and explanations lined out on their website. And in contrast to other applications, this website is actually online, is in English, works, and has no dead links or Lorem Ipsum text!

Yes....  I know someone who knows someone who knows the owner of this company. He told me all is fine. I spoke to him a few days ago so no need to do KYC whatsoever! I am supportive on this application!

**Comment by herrehesse** [comment]
@corrupted-pixels Thanks for your KYC in our email. Willing to support this project. When do you expect to start? Happy to help with packing your valuable data, we can facilitate up to 500T daily.

**Comment by Sunnyiscoming** [comment]
@corrupted-pixels I have checked the website and social media before. But I have not seen any data samples. And it is hard to say that you have 5 PB storage needs.

**Comment by corrupted-pixels** [comment]
@Sunnyiscoming right. the application states that we provide them to notaries as needed. if you are a SP with a cooperating notary, please send us a mail to 

collaboration@corrupted-pixels.art

ps: we have 10 Exa byte storage needs. thats what the website states and that is what  we intend to store. it is also clearly stated where the data is coming from.

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f173ijffhxb4pnaugwqexy3cf6zkalrclstumwocq

**Comment by corrupted-pixels** [comment]
@Sunnyiscoming thank you for showing confidence in our project. 

@cryptowhizzard / @herrehesse  it would be nice if you could proceed with signing so we can move closer to a point where we can start storing our projects data

thank you all very much - we are looking forward to great collaborations!

**Comment by MetaWaveInfo** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfktmdtk6mmxvqbhs7iibrvgu4ebjias4ijelcjj45tbzotyk2ga 
#### Address 
> f173ijffhxb4pnaugwqexy3cf6zkalrclstumwocq
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1ktlkcxnmzxcdaoqfsunrg3vocfbmgv4n3mrn74a
#### Id
> 996952ba-2bd0-4fa4-ad7f-38c1d82c11e0
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfktmdtk6mmxvqbhs7iibrvgu4ebjias4ijelcjj45tbzotyk2ga

**Comment by spaceT9** [comment]
Did you find any SP to work with?  What's your distribution plan? Is the data retrievable or not?

**Comment by RobQuistNL** [comment]
Ofcourse the data is retrievable :) and I'm quite sure there's a lot of SP's willing to work with this project.

**Comment by spaceT9** [comment]
Can you provide data samples and also the proof of data size？
