### ISSUE TITLE
[DataCap Application] MATCHI FOUNDATION LTD

### ISSUE THREAD

**Issue by yongzifei** [filecoin-project/filecoin-plus-large-datasets#1915]
### Data Owner Name
MATCHI FOUNDATION LTD

### Data Owner Country/Region
Singapore

### Data Owner Industry
Web3 / Crypto

### Website
[https://matchi.games](https://matchi.games)

### Social Media
https://twitter.com/matchi_games (Twitter)

### Total amount of DataCap being requested
2 PiB

### Weekly allocation of DataCap requested
100 TiB

### On-chain address for first allocation
f1cyjg3wqns7jfarxumea7ydebwr4vdabg2pdzehq

### Data Type of Application
Private Commercial/Enterprise

### Custom multisig
No

### Share a brief history of your project and organization
MATCHI is a Web3 dance game  with Token, NFT, DAO. Players use NFT to enter the game and get Token rewards by dancing.  The game uses advanced motion capture and matching technology, and can run not only on mobile phones, but also on professional equipment such as "fitness mirrors". It is the only dance game on Web3 at present. All dance music videos in the game are created and shared by users, which requires a large amount of video storage space.
This project was launched by Singapore MATCHI FOUNDATION LTD,  Which registered on Sept. 2022. Founded by 4 partners with rich experience in market, technology and financing respectively. At present, seed investment has been obtained, and the progress of the project is in line with expectations.

### Is this project associated with other projects/ecosystem stakeholders?
No

### Describe the data being stored onto Filecoin
The gameplay of our game is that the player chooses a dance video, imitates the dance movements in the video, and rewards the player by calculating the degree of completion through AI motion capture. These dance videos are also uploaded by other players for dancers to learn from. At present, our repository has collected a lot of dance videos created by users, and it is constantly increasing. We hope to use Filecoin's storage and make NFT into Filecoin's smart contracts in the future.

### Where was the data currently stored in this dataset sourced from
My own storage infra

### How do you plan to prepare the dataset
lotus

### Please share a sample of the data
https://matchi.games/download/matchi_data_sample.mp4

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
1 to 1.5 years

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
HTTP or FTP server

### How do you plan to choose SP
Partners

### How do you plan to make deals to your storage providers
Lotus client

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
Can you provide more data samples or data sources?

**Comment by yongzifei** [comment]
Maybe the video you are watching is a bit large. 
This is not streaming media. It needs to be downloaded before you can watch it. Wait for a while for the download to complete.

**Comment by yongzifei** [comment]
> Please share more detailed information about sps you will cooperate with.
f02625        China, cn
f0107753    China, cn
f073697      Hongkong, hk
f014768      Singapore, sg

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 2PiB

**Expected weekly DataCap usage rate**
> 100TiB

**Client address**
>f1cyjg3wqns7jfarxumea7ydebwr4vdabg2pdzehq

**Comment by zcfil** [comment]
dear,

Thank you for applying for datacap. As a Filecoin FIL+Notary Public, I am currently screening your application and conducting due diligence.

Looking at your application, I have some questions:

Because you are a novice on Github and do not have a history of past applications. Can you introduce who you are and your company?

You declare that you are a data preparer. What hardware do you have on your end to prepare this dataset? What is your internet connection speed? Have you downloaded the data locally?

In my opinion, there are many datacaps that apply for 2PB. People need to have a comprehensive understanding of Filecoin, data packaging, data distribution, and all the requirements that come with it. Are you a novice in the Filecoin field, or have you previously applied for datacap on different Github account names?

Can you show us some visible evidence of the size of your data and the storage/packaging hardware you have?

As a final question, I would like you to fill out [this form](https://form.jotform.com/230953098450156) in order to provide us with the necessary information to make a wise decision on your LDN request when we are willing to support it.

thank you!
