### ISSUE TITLE
[DataCap Application] <Zetacube Inc> - <Korean Music Broadcast>

### ISSUE THREAD

**Issue by hooonc** [filecoin-project/filecoin-plus-large-datasets#2060]
### Data Owner Name

IPFSKDC

### What is your role related to the dataset

Data Preparer

### Data Owner Country/Region

Korea, Republic of

### Data Owner Industry

Information, Media & Telecommunications

### Website

http://www.kbnitv.net/?r=s072608&c=23

### Social Media

```text
none
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f13y7egp3cu7o6eog5fliizqt24f5o6qwnedbdq5a

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Zetacube Inc is a 'Ultra-high-capacity decentralized storage hyper server solution company' in the Web 3.0 era, established to research and commercialize the IPFS storage system, an innovative technology for safely storing huge data in the 4th industrial age. Also, Zetacube Inc is participant in the Slingshot V3, both as DP and SP. Zetacube website is https://www.zetacube.net/
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data is Korean music broadcast dataset. Currently, we have only prepared 500TiB capacity, and the data volume will continue to increase because music broadcasts are aired every week.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
https://www.youtube.com/@kbnitv2493/videos
http://www.kbnitv.net/?r=s072608&c=23
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Big Data Exchange, Partners

### If you already have a list of storage providers to work with, fill out their names and provider IDs below

```text
f0838467
f01227505
f01942239
f01695888
f01823110
f01103160
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
Please provide related materials to prove that you are authorized to store data from KBN ITV.

**Comment by HoonChoi-Zetacube** [comment]
@Sunnyiscoming  I would like to notify you that all the documents are written in Korean.

These documents provide evidence that KBN iTV is a broadcasting channel operated by IPFSKDC.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/e7ec131a-bdbf-479c-9a4a-c8f979ae523c)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/d24c68b7-65b1-4450-9ccc-14f19adcea53)
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/085bf906-46f4-404b-b810-69d37c63f8c5)

This is a document stating that Zetacube is managing KBNiTV broadcast data, which is data from IPFSKDC.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/8b5e985d-b804-4721-a21d-e9d2cf4d09e9)

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f13y7egp3cu7o6eog5fliizqt24f5o6qwnedbdq5a

**Comment by zcfil** [comment]
dear,

Thank you for applying for datacap. As a Filecoin FIL+Notary Public, I am currently screening your application and conducting due diligence.

Looking at your application, I have some questions:

Because you are a novice on Github and do not have a history of past applications. Can you introduce who you are and your company?

You declare that you are a data preparer. What hardware do you have on your end to prepare this dataset? What is your internet connection speed? Have you downloaded the data locally?

In my opinion, there are many datacaps that apply for 5PB. People need to have a comprehensive understanding of Filecoin, data packaging, data distribution, and all the requirements that come with it. Are you a novice in the Filecoin field, or have you previously applied for datacap on different Github account names?

Can you show us some visible evidence of the size of your data and the storage/packaging hardware you have?

As a final question, I would like you to fill out[ this form](https://form.jotform.com/230953098450156) in order to provide us with the necessary information to make a wise decision on your LDN request when we are willing to support it.

thank you!

**Comment by HoonChoi-Zetacube** [comment]
@zcfil Regrettably, it appears that my application did not receive proper consideration. I have previously submitted three applications, one of which has been assigned a datacap. Currently, we are in the onboarding phase. My name is Hoon Choi from ZetaCube, and I have already completed the company introduction and homepage sections within the application form.

Regarding the hardware infrastructure, our company currently possesses six sets of node-miners and 86 workers. We have established 2GB fiber backbone. In terms of storage capacity, we utilize 32 petabytes of NAS storage. Additionally, our network configuration consists of two 40GB core switches and twelve 10GB switches. Data is downloaded and stored locally.

If you have any additional details or specific inquiries, please let me know.
Thank you.

**Comment by nj-steve** [comment]
@HoonChoi-Zetacube Have you contacted the SPs? Are they all in favor of retrieval ?

**Comment by HoonChoi-Zetacube** [comment]
@nj-steve We have contacted three SPs. They are all based in Korea and are in favor of retrieval.

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceckz66ftlo5hj67n6vf3xnhjb3q5ukxvcwjkzcqpsppxuilzbp3f6 
#### Address 
> f13y7egp3cu7o6eog5fliizqt24f5o6qwnedbdq5a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> 209a581c-0acf-463f-bde3-a4ee95be4800
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceckz66ftlo5hj67n6vf3xnhjb3q5ukxvcwjkzcqpsppxuilzbp3f6

**Comment by HoonChoi-Zetacube** [comment]
@nj-steve I appreciate your assistance.

**Comment by psh0691** [comment]
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2060#issuecomment-1606408403

Hi, @HoonChoi-Zetacube 

I'd like to ask you some practical questions that will help you.

1. You said you had applied for 3 data caps before, so please let me know the link or application number.

2. You said that the data you have is 500 TiB, so please prove it with a screenshot.

3. You said in the application that you would do 10 copies, but there are only 6 SPs. This is all in Seoul, and it is estimated to be one SP. This is against FIL+ regulations. Could you explain other regional distribution plans as well?

**Comment by HoonChoi-Zetacube** [comment]
@psh0691 Thank you for expressing interest in my application. I will address your inquiries sequentially.

1. The applications we have previously submitted are #1991, #2003, and #2025. Currently, we have been allocated Datacap for #1991 and are in the process of onboarding. However, we have not yet received Datacap for #2003 and #2025.

2. At present, we possess a portion of KBNiTV data in our storage, and we are transferring raw data from broadcast editorial companies affiliated with KBNiTV to our storage. Data will be generated more than 100 TiB per week. The data volume generated exceeds 100 TiB per week. To ensure transparency, we are developing a webserver that will allow notaries to verify the data themselves. We will share the corresponding link as soon as it becomes available.

3. If I understand correctly, you are referring to the list of nodes, but SPs are located in Incheon, Gwangju, Jeonju, and Seoul. We plan to onboard at three of these SPs initially. Additionally, we intend to onboard one SP in China and two SPs from Greater Heat in Dallas, USA. In the event that we require additional SPs in other regions, we will utilize Slack or BDE to identify suitable SPs.

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by psh0691** [comment]
Hi, @HoonChoi-Zetacube 

My specific question is for active help, so I hope you don't misunderstand.
If it is not clear due diligence, the T&T WG may be flagged and it may be more difficult to obtain a DC assignment. In addition, due diligence and the notary who signed it are also responsible.

I have some questions, so I'm inquiring about the data. 

1. This is an unverified identity that has only been subscribed to GitHub for 3 months. But I'm already applying for a fourth DC. One of the three previous applications (#1991) was assigned 50 TiB DC and 10.25 TiB was used. 
However, we have deployed only one f01227505 (IPFSKDC) node, and the search is 0%.
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1991#issuecomment-1612310838

2. Failed to prove retention data. 

3. All nodes listed above are nodes in IPFSKDC 1SP; Chinese SP and US nodes are not disclosed. FIL+ guidelines must be distributed to at least four SPs in at least three regions.
https://github.com/filecoin-project/filecoin-plus-large-datasets

4. If the above is not resolved, you cannot sign it.

**Comment by herrehesse** [comment]
@psh0691 Thank you for conducting proper due diligence.

**Comment by herrehesse** [comment]
[nj-steve](https://github.com/nj-steve) Why have you conducted zero due diligence? Will open a dispute.

**Comment by nj-steve** [comment]
Hello @herrehesse 
Thank you for your suggestion. I think the dataset of Korean music broadcast a great dataset and will contribute to filecoin data development.
But I neglected to investigate the client's previous application records. This is something we need to check together. Thanks for all your hard work for the community.

**Comment by cryptowhizzard** [comment]
Please see #2003 

This application is against FIL+ rules and guidelines and needs guidelines before allocations of datacap can be made.

**Comment by cryptowhizzard** [comment]
#1991 

100% selfdealing of the granted datacap.

**Comment by HoonChoi-Zetacube** [comment]
I apologize for the delayed response. As previously mentioned, we are currently developing a system for notaries to check the data themselves. However, the process is taking longer than anticipated due to the extensive volume of data involved. 

1. Does the duration of my GitHub presence have any significance? We have submitted three applications as we have claimed three datasets for Slingshot. Currently, we are in the process of optimizing the onboarding procedure. If you monitor of DC we have been allocated, you will see a sharp increase in onboarding in the near future 

2. The system construction process
is experiencing delays due to the extensive data volume. I will replace the evidence with lots of screenshots
![1688570234512.png](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/4f8d6b03-9413-46f1-baff-6114da6400d5)

![1688570247035.jpg](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/c27dc6b7-ff56-418b-8ee9-5e645ea67dab)

![1688570260966.jpg](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/df7eab75-052d-44d5-ba48-02ab779b8dd7)

![1688570266745.jpg](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/c8cf3a08-c8a4-4777-8542-d8265666ecf7)

![1688570269437.jpg](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/ae60d2ee-963f-49f1-969e-e90b3c18b25a)

![1688570272390.jpg](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/2f127def-12d7-4735-9fc6-03686fa7fdba)

![1688570286184.jpg](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/cdd13361-dd82-48aa-b215-831488aee92c)

![1688570234339.png](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/c65b1ba8-8609-422d-b64a-ed7db1334ace)

![1688570234408.png](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/552f3c07-0b7b-4c0b-b83e-abdbb3b1874b)

![1688570234468.png](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/fb7fc0ff-a053-4acb-97bf-de4edc720a05)


3. IPFSKDC is distinguished by its shared ownership model, where multiple individuals serve as operators for their respective data centers under the IPFSKDC brand. As a result, IPFSKDC does not operate as a single SP. 
We participated in DSPA and established connections with various SPs. I cannot tell you the exact nodes right now, but we will store data on SPs in various regions. And I mentioned this previously, but it is worth reiterating that should the need arise for additional local SPs, I will utilize the Slack channel and BDE to identify and collaborate with suitable partners.

**Comment by cryptowhizzard** [comment]
Hello,

It does not mean that when you type a long story that it makes things better :)

You sealed 100% of the granted datacap in #1991 with one sp, your own. We call this selfdealing.

Please read the rules of Fil+ as they are written at

https://github.com/filecoin-project/filecoin-plus-large-datasets

**Comment by psh0691** [comment]
Hi, @HoonChoi-Zetacube 

Thank you for your reply.

1. The importance of the GitHub subscription period is due to the reliability of customers. As there have been cases of fake accounts, DC fraud, and abuse in connection with FIL+ DC applications, the policy is being discussed to allow only subscribers to apply for more than a year and more than six months.
https://github.com/filecoin-project/notary-governance/issues/887

2. The amount of data you applied for (500TiB) doesn't show if you have enough screenshots, but I think I can support Round 1. 

3. The use of DC allocated to #1991 still needs improvement as mentioned above. This is because the history of the previous application has a lot of influence on T&T. I'll wait a little longer.

**Comment by HoonChoi-Zetacube** [comment]
@psh0691 I updated the comment on #1991. I would appreciate it if you could check it out.

**Comment by psh0691** [comment]
@HoonChoi-Zetacube 
The search rate for #1991 has been updated.
I see it is still stored in 1SP. It is expected to be added afterward.
I'm willing to apply for this round.

**Comment by psh0691** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahlyckjkewqrnzpysu4ekjutyvpe2s5l7caifuijbwwro6o4dp72 
#### Address 
> f13y7egp3cu7o6eog5fliizqt24f5o6qwnedbdq5a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1qdko4jg25vo35qmyvcrw4ak4fmuu3f5rif2kc7i
#### Id
> 209a581c-0acf-463f-bde3-a4ee95be4800
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahlyckjkewqrnzpysu4ekjutyvpe2s5l7caifuijbwwro6o4dp72

**Comment by HoonChoi-Zetacube** [comment]
@psh0691 Thank you for your valuable support. We will start storing data in other SPs this week. And as other regional SPs are finalized, I will let you know about them.

**Comment by herrehesse** [comment]
@psh0691, it is concerning that you have signed for this fully self-dealing entity. I urge you to reconsider and revoke your involvement. The client should be given an opportunity to explain their behavior and propose solutions.

However, until that clarification occurs, it is crucial that no datacap is granted.

**Comment by HoonChoi-Zetacube** [comment]
@herrehesse What additional evidence or documentation do I need to provide? I provided sincere responses to the notary's inquiries and talked about potential future solutions. Consequently, @psh0691 signed this application. However, you did not request any information or supporting evidence. You just advised other notaries against signing and urged them to withdraw their endorsements. Do you consider this to be a fair and equitable process? I am of the opinion that you have not thoroughly reviewed my answers.

I would like you to tell me directly what proofs you would like me to require. Then I will answer your questions in good faith.

**Comment by herrehesse** [comment]
@HoonChoi-Zetacube Please respond to: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2060#issuecomment-1622112664

Please familiarize yourself with the rules and provide us with a plan outlining the next steps. Engaging in complete self-dealing is a violation of the rules, and it is your responsibility to ensure that you have read and understood them correctly. Simply granting you additional data capacity will not resolve this issue.

**Comment by HoonChoi-Zetacube** [comment]
@herrehesse Did not you check my comments with notaries in #1991? I have already answered this question last week, and the other notaries have accepted my answer. As a result, you know, @psh0691 signed this application. He was the first notary to raise concerns about our situation and problems. I believe he signed based on his understanding of our responses and belief in our future plans.

To validate our assertions, notaries have mentioned #1991 several times in this application, and we have asked and answered questions there. If you intend to comment on the signatures of other notaries, I recommend reviewing #1991 in addition to examining this application.

The answer is here: [#1991 (comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1991#issuecomment-1622953875)

**Comment by hyunmoon** [comment]
FYI, this applicant is a storage provider.
Beware of self dealing.

[https://youtu.be/lNFeH2c61sc](url)

**Comment by hyunmoon** [comment]
FYI, this applicant is a storage provider.

https://www.youtube.com/@ipfs8151

**Comment by zcfil** [comment]
Thank you to @psh0691  for conducting the first round of review, which is very detailed @HoonChoi-Zetacube  also appreciates your cooperation in the review. Due to the abuse of DC, we notaries are now very cautious. The first review has been approved, and we continue to observe whether your stored data meets the standards.

**Comment by zcfil** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5pbiiwzgwlahc6wzhvgjpygeisjtuj4twsx3aa5i5t6bipyeits 
#### Address 
> f13y7egp3cu7o6eog5fliizqt24f5o6qwnedbdq5a
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
#### Id
> 209a581c-0acf-463f-bde3-a4ee95be4800
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5pbiiwzgwlahc6wzhvgjpygeisjtuj4twsx3aa5i5t6bipyeits

**Comment by hyunmoon** [comment]
```
If you already have a list of storage providers to work with, fill out their names and provider IDs below
f0838467
f01227505
f01942239
f01695888
f01823110
f01103160
```

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2025#issuecomment-1569094876

Why would you write your own node in the applicaation?

**Comment by hyunmoon** [comment]
```
If you already have a list of storage providers to work with, fill out their names and provider IDs below
f0838467
f01227505
f01942239
f01695888
f01823110
f01103160
```

https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2025#issuecomment-1569094876

Why would you write your own node in your application?

**Comment by cryptowhizzard** [comment]
> ## Request Proposed
> Your Datacap Allocation Request has been proposed by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzaceb5pbiiwzgwlahc6wzhvgjpygeisjtuj4twsx3aa5i5t6bipyeits
> 
> #### Address
> > f13y7egp3cu7o6eog5fliizqt24f5o6qwnedbdq5a
> 
> #### Datacap Allocated
> > 256.00TiB
> 
> #### Signer Address
> > f1cjzbiy5xd4ehera4wmbz63pd5ku4oo7g52cldga
> 
> #### Id
> > 209a581c-0acf-463f-bde3-a4ee95be4800
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5pbiiwzgwlahc6wzhvgjpygeisjtuj4twsx3aa5i5t6bipyeits

All nodes are located in Korea. This is *against* FIL+ rules and guidelines.

**Comment by cryptowhizzard** [comment]
All nodes are located in Korea. This is against FIL+ rules and guidelines.

**Comment by herrehesse** [comment]
@raghavrmadya,

Numerous notaries have clearly crossed boundaries and disregarded multiple rules within the system. I request the immediate removal of this client and the revocation of their remaining datacap.

Furthermore, I strongly suggest initiating a dispute or removal process for the notaries in question, as it has become evident that a considerable number of them are recurring abusers (as documented in the open issues here: https://github.com/filecoin-project/notary-governance/issues).

**Comment by HoonChoi-Zetacube** [comment]
@cryptowhizzard @herrehesse 
You guys are right. The nodes in the node list of this application are all located in Korea. They are our customer nodes, and we will only store data in three of them.
I have already said that we will use Slack Channel or BDE to find other regional SPs. And we posted an application on BDE. This is something you can check. We are currently engaged in discussions with GH, who has their nodes situated in both Singapore and Dallas. We also have been introduced to several regional SPs by the Protocol Labs Foundation and are currently negotiating data storage fees with them. We will update the node list as soon as everything is finalized.

**Comment by HoonChoi-Zetacube** [comment]
> **We have found some problems in the information provided in the Approved Comment. We could not find **Address** field in the information provided
> 
> ```
> Please, take a look at the comment and edit the body of the comment providing all the required information.
> ```
@Sunnyiscoming Could you please provide me with an explanation as to why the error label was added? I'm currently unaware of the specific reasons behind its inclusion and would greatly appreciate your insights.

**Comment by cryptowhizzard** [comment]
> @cryptowhizzard @herrehesse You guys are right. The nodes in the node list of this application are all located in Korea. They are our customer nodes, and we will only store data in three of them. I think I may have made a mistake in this aspect. It seems that we should have proactively selected three nodes for storing this data and included them in the node list beforehand. I have already said that we will use Slack Channel or BDE to find other regional SPs. And we posted an application on BDE. This is something you can check. We are currently engaged in discussions with GH, who has their nodes located in both Singapore and Dallas. We also have been introduced to several regional SPs by the Protocol Labs Foundation and are currently negotiating data storage fees with them. We will update the node list as soon as everything is finalized.

Thank you. It seems you understand the expectations, that is good to hear!
Looking forward to the first round ;-)

**Comment by Filplus-govteam** [comment]
Hello @HoonChoi-Zetacube we see you have answered many questions from the community regarding your distributed storage plan. 

Per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and then the application will be approved for notary review. Let us know if you have any questions.

Also, notaries please note your guidelines are to not allocate DataCap BEFORE SP entities and distribution plan is clear. Clients need to meet guidelines upfront moving foward.

**Comment by HoonChoi-Zetacube** [comment]
> Hello @HoonChoi-Zetacube we see you have answered many questions from the community regarding your distributed storage plan.
> 
> Per the new guidelines [filecoin-project/notary-governance#922](https://github.com/filecoin-project/notary-governance/issues/922) for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
> 
> This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and then the application will be approved for notary review. Let us know if you have any questions.
> 
> Also, notaries please note your guidelines are to not allocate DataCap BEFORE SP entities and distribution plan is clear. Clients need to meet guidelines upfront moving foward.

I submitted the Fil+ Registration Form.

**Comment by Filplus-govteam** [comment]
First - FYI, we submitted a ticket regarding the error issue: https://github.com/keyko-io/filecoin-verifier-frontend/issues/829

Second - Thank you @HoonChoi-Zetacube for sharing SP information and contacts, confirming this information was shared.

Confirming that you shared the following:
SP ID/ Entity / Location
f01227505 IPFSKDC Incheon Korea
f01695888 IPFSKDC Gwangju Korea
f01823110 IPFSKDC Jeonju Korea
f02005421 Greaterheat Dallas, USA
f02289399  self-employ Hong Kong


Also a note to the client @HoonChoi-Zetacube  - [guidelines](https://github.com/filecoin-project/filecoin-plus-large-datasets#current-scope) state that no more than one copy per SP ID and no entity should store more than 30% of DataCap. Please keep that in mind. Thank you.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
Again : 

All nodes are located in Korea, this is against FIL+ rules and guidelines.

Secondly , retrieval does not work.

 cat 2060-f02195553-f01695888-48039055-baga6ea4seaqh7ezhl6fbe2bq5zzfb3amtljh3pqznn4hfdbmexiok6gxqq5iahi.log
Recv 0 B, Paid 0 FIL, Open (New), 1ms [1691497513256515296|0]
Recv 0 B, Paid 0 FIL, DealProposed (WaitForAcceptance), 42ms [1691497513256515296|0]
Recv 64 B, Paid 0 FIL, BlocksReceived (WaitForAcceptance), 22.547s [1691497513256515296|64]
Recv 124 B, Paid 0 FIL, BlocksReceived (WaitForAcceptance), 22.55s [1691497513256515296|124]
Recv 222 B, Paid 0 FIL, BlocksReceived (WaitForAcceptance), 22.552s [1691497513256515296|222]
Recv 295 B, Paid 0 FIL, BlocksReceived (WaitForAcceptance), 22.555s [1691497513256515296|295]
Recv 408 B, Paid 0 FIL, BlocksReceived (WaitForAcceptance), 22.557s [1691497513256515296|408]
Recv 513 B, Paid 0 FIL, BlocksReceived (WaitForAcceptance), 22.559s [1691497513256515296|513]
Recv 1.83 KiB, Paid 0 FIL, BlocksReceived (WaitForAcceptance), 22.562s [1691497513256515296|1874]
Recv 2.132 KiB, Paid 0 FIL, BlocksReceived (WaitForAcceptance), 22.564s [1691497513256515296|2183]
Recv 2.132 KiB, Paid 0 FIL, DealAccepted (Accepted), 1m47.34s [1691497513256515296|2183]
Recv 2.132 KiB, Paid 0 FIL, PaymentChannelSkip (Ongoing), 1m47.341s [1691497513256515296|2183]

It's slower then a 56K6 modem .....? This is not readily retrievable.

**Comment by HoonChoi-Zetacube** [comment]
@cryptowhizzard Thank you for your continued interest in us.
1. GH, located in Dallas, is ready for sealing and they will start onboarding within this week. However, SP located in Hong Kong informed us a few days ago that it is currently unable to store this data due to their HW issue. So we are currently looking for different local SPs in various ways.
2. 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/751a82af-251a-4f0b-8cc9-20df3785ab95)
 This is the current internet speed of f01695888. I don't know why the retrieval speed is so slow. I'll look into this a bit more.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
@HoonChoi-Zetacube - note above reviewed. Definitely need to show more distribution before future allocations should be considered

**Comment by cryptowhizzard** [comment]
<img width="667" alt="Scherm­afbeelding 2023-08-14 om 18 10 13" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/570064f7-a80f-48f7-8e91-5b715a2febe1">

From my understanding and from some of the community these are pictures of a wedding ( Private ).

**Comment by maxvint** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
@Filplus-govteam Locacion information in CID Checker Report is constantly changing according to Korea Telecom's routing settings. You can see it if you look at the image below. But clearly, the Korean SPs storing the data are located in Incheon, Gwangju, and Jeonju.
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/028132d1-b993-4fd0-a09a-b5ab3254a13a) 
![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/809a2063-1627-47fe-860b-66e39bf49776) ![image](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/129706575/59eaf0ea-ef6d-4b7c-b2b9-ed3f6dc907d0)
Also, Greaterheat seems to be using Amazon's CDN. I believe that Amazon has an endpoint on the router connecting the US and Korea, which is why GH's location in the CID Checker Report shows Seoul.

**Comment by HoonChoi-Zetacube** [comment]
@cryptowhizzard KBNiTV once conducted a wedding broadcast to promote the Elina Hotel in Gangnam, Seoul. A large number of Korean broadcasters have filmed at this hotel, and many celebrities get married here. You can check it on this link. (http://elienahotel.com/eliena/content.php?co_id=wedding0_kr)

The data we stored included celebrity weddings and celebrity family weddings. This is public data, not private data, so it's okay to make it public. However, if storing this data were an issue, we would not store any more wedding-related data.

Thank you for pointing out this would be a problem.

**Comment by cryptowhizzard** [comment]
> ```
> The data is Korean music broadcast dataset. Currently, we have only prepared 500TiB capacity, and the data volume will continue to increase because music broadcasts are aired every week.
> ```

Hi,

Thanks for the honest answer. The point is:

"The data is Korean music broadcast dataset. Currently, we have only prepared 500TiB capacity, and the data volume will continue to increase because music broadcasts are aired every week."

This is what you were supposed to be storing. No wedding broadcasts.
I will however revoke my dispute given the honest explanation. @raghavrmadya can you close it please?

@HoonChoi-Zetacube please make sure that from now on you store what you indicated ( Music ).

**Comment by HoonChoi-Zetacube** [comment]
@cryptowhizzard I will double-check the data to make sure that only Korean music is stored. Thank you.

**Comment by Filplus-govteam** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
Dear the governance team and notaries,
We made a big mistake when we made verified deals. When creating deals for #1991, we entered addresses for #2060 and some of them were already sealed. We realized our mistake, stopped the deals, and looked for a solution, but could not find one. I would really appreciate it if anyone could let me know the solution.
Again, we sincerely apologize for the trouble our mistake caused.

**Comment by HoonChoi-Zetacube** [comment]
We had almost exhausted our allocated DataCap, but DataCap request bot did not kick off a second allocation request.

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
checker:manualTrigger

**Comment by HoonChoi-Zetacube** [comment]
I'm waiting for the SSA bot issue to be resolved.

**Comment by 1613557499** [comment]
checker:manualTrigger

**Comment by Sunnyiscoming** [comment]
Hello, @hooonc per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity and then the application will be allowed to move forward for additional notary review.

**Comment by hooonc** [comment]
@Sunnyiscoming I've already sent the FIL+ registration form to the Fil+ governance team and received a comment. [(comment)](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2060#issuecomment-1655850687)]
Do I need to complete this form again?

**Comment by Sunnyiscoming** [comment]
SP List provided:
[{"providerID":"f01227505,City":Incheon","Country":"Korea","SPOrg","IPFSKDC"},
{"providerID":"f01695888,City":Gwangju","Country":"Korea","SPOrg","IPFSKDC"},
{"providerID":"f01823110,City":Jeonju","Country":"Korea","SPOrg","IPFSKDC"},
{"providerID":"f02005421,City":XYZ","Country":"USA","SPOrg","GreaterheatDallas"},
{"providerID":"f02289399,City":HongKong","Country":"CN","SPOrg","self-employ"},]

**Comment by Filplus-govteam** [comment]
checker:manualTrigger
