### ISSUE TITLE
[DataCap Application] <Architectural design> - all architectural design Co., Ltd.

### ISSUE THREAD

**Issue by Designguy1** [filecoin-project/filecoin-plus-large-datasets#2082]
### Data Owner Name

Guangzhou All Architectural Design Co., Ltd.

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

http://www.a.cn/

### Social Media

```text
http://www.a-ll.cn/
```

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

800TiB

### On-chain address for first allocation

f1xjdq6fopvir2ikm4vcfrchhkwajxq57xj3kzzky

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are an independent design team established in Guangzhou, China. The three partners graduated from Berlage College in the Netherlands. We were officially established in 2015, but since 2012, we have been in the field of design and research of architecture and cities.

We currently have 36 employees in the company, 17 of whom are designers, and we have undertaken many designs from all over the world, such as a hotel with an area of ​​three kilometers in Italy, a sports park in the north of Songshan Lake in Dongguan, China, and an office in Foshan, China renovation, office space renovation in Guangzhou, China, etc.

Whether it is an office space of 3,000 square meters or a corner of an urban village of 30 square meters, we will go to the site to conduct project research, take pictures and videos, measure the project, communicate customer needs, plan setting and post-construction, etc. These data are very large, but also very important, and we want to store the data on the Filecoin network.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Whether it is a 3,000-square-meter office space or a 30-square-meter urban village, we will go to the site to conduct project research, take pictures and videos, measure the project, communicate customer needs, plan setting, and post-construction.

The data we want to store is:
1. Design draft (before a real design plan is determined, at least 10 drafts need to be designed back and forth)
2. Project information (address, floor area, renovation needs, budgeted cost)
3. Pictures and videos before construction
4. Pictures and videos after the construction is completed
As designers, we store a lot of data, and we hope to reduce the storage burden for us by storing publicly available data on the filecoin network. Thank you Filecoin Network!
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

IPFS, lotus, singularity

### Please share a sample of the data

```text
We provide about 5G data cases.This is a greenway project we did for Chengdu, China.
Link: https://pan.baidu.com/s/1-cDn173CpF8wIIqfCK38Og
Extraction code: mpvh
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives, Lotus built-in data transfer

### How do you plan to choose storage providers

Slack, Filmine

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by herrehesse** [comment]
@Designguy1, could you please clarify the public benefit that this dataset will bring? Additionally, it is important to know if you are willing to compensate the storage providers who will be storing this business data on your behalf.

**Comment by Designguy1** [comment]
We re-uploaded the case, here are our design pictures, CAR, etc. We are committed to creating architectural aesthetics and bringing different beautiful experiences to customers https://drive.google.com/drive/folders/1x1EMlhaaNxs_o3jx8pUuR6by6mfWukw2?usp=sharing

**Comment by Designguy1** [comment]
@Sunnyiscoming

**Comment by herrehesse** [comment]
@Designguy1 I am sorry I do not see the added value to the Filecoin ecosystem here.

**Comment by Designguy1** [comment]
Don't bring out the saying that "the company's data has no value, only public data has value",Last year  @dkkapur  has expressed its opinion

**Comment by Sunnyiscoming** [comment]
Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.
You should list Miner ID, Business Entity, Location of sps you will cooperate with.
Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2082.

**Comment by Designguy1** [comment]
We have sent an email, we are confirming the cooperation of sp, we will reply you tomorrow
<img width="1069" alt="WX20230713-154300@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138544716/2242e12e-dda8-4499-981b-0a0756673484">

**Comment by Sunnyiscoming** [comment]
Look forward your reply.

More information wanted.
- Have you prepared enough token for sector pledge?
- Are you a data preparer? What is your previous experience as a data-preparer? List previous applications and client IDs
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?

**Comment by Designguy1** [comment]
1. We plan to cooperate with f02237295, f02009673, f02143523, f02127257, f02224517. In addition, we have also contacted many other sps.
2. As far as I know, they are basically ready to pledge FIL, and one of them plans to borrow 200,000 pledges from STFIL.
3. The data will be prepared by us. We only need to copy the data and post it on the hard disk. This is not a very complicated thing for us, but it needs to increase the cost of broadband. As a data preparer, we are proficient in using boost, and continue to update it according to the official version of boost. Although we have not issued bills ourselves, we have tested it with our partners. Our current procedures and technologies are mature.
4. We generate a lot of data. I’m not sure if you believe that a design company, especially a decoration design company like ours, and a company including construction, is really generating a lot of data every day. I can even provide more data cases, such as 1TiB data case to you, and you will believe that our data is really a lot, and our data is indeed valuable.
5. Please pass our application as soon as possible, thank you!

**Comment by herrehesse** [comment]
@Designguy1,

While it's understandable that a design company, particularly one involved in decoration and construction, generates a significant amount of data on a daily basis, it is important to clarify who finds this data valuable.

As far as I can assess, it appears that you are a business seeking to store your proprietary business data on Filecoin, utilizing the community-granted multiplier to store it at minimal cost. However, this usage does not align with the intended purpose of FIL+. FIL+'s primary objective is to store open and public data, thereby adding value to the entire ecosystem. By promoting open data storage, we aim to encourage wider usage and attract clients who will eventually contribute to the sustainability of our services through payment.

Considering this, it is unclear how your data holds value for anyone beyond your own business. I fail to see any evidence or convincing argument supporting its broader significance.

Adding to this, this is your first application on FIL+ ever, you need to build trust with the community first:

Here are some steps you can take:
1. Seek out storage providers in different regions who are willing to store your data and ensure retrievability. Making sure these SP's are not on a blacklist/abuselist.
2. Start with a smaller data request, such as 100T, and ask for the community's signature. I'm willing to assist you with this.
3. Store your data, showcase its retrievability, value, and distribution.
4. If everything goes well and you can establish trust, you can request additional datacap. I'll be the first one to offer my assistance.

By following these steps, you can build trust within the community and demonstrate the worthiness of your data.

**Comment by Designguy1** [comment]
We don't need to discuss the issue of "corporate data has no value, only public data has value".Because there is no need for discussion.

@dkkapur Conclusions have been drawn.

Therefore, your thoughts will not affect the @raghavrmadya @Sunnyiscoming and the result

**Comment by cryptowhizzard** [comment]
> 

Who will be the SP's with presence outside of China if i may ask?

All the mentioned miners are located in China. [Can you read the FIL+ rules here please](https://github.com/filecoin-project/filecoin-plus-large-datasets/)

A small snapshot from it:
The dataset should be public, open, and mission aligned with Filecoin and Filecoin Plus. This also means that the data should be accessible to anyone in the network, without requiring any special permissions or access requirement. If this is not the case - consider instead going via the E-Fil+ pathway to getting DataCap. You can read more about that [here](https://efilplus.super.site/)

**If a client wants to onboard more than 5+PiBs, the recommendation would be to start with a few applications and earn trust from the community. Having a positive reputation and proving to the community first by onboarding a smaller amount of data will help anyone who wants to onboard massive amounts of data much faster and smoother.**

Stored data should be readily retrievable on the network and this can be regularly verified (though the use of manual or automated verification that includes retrieving data from various miners over the course of the DataCap allocation timeframe). At this time all LDNs may have full retrievability, but it is not required. Each project should specify what portion of the data is retrievable and provide justification. From there notaries can decide during the due diligence phases if the client’s application is justifiable and can agree to sign it or not.

There should be no open disputes in the Fil+ ecosystem against the client during the time that the application is open for review

With the current tooling and workflow, the recommendation would be to use a different address for every application. However, if you cannot, know that the workaround requires manual attention. We strongly do not recommend this due to delays created and mixed math for subsequent allocation issues. In the short term, we can support this. Please notify Simon Kim and add this to your LDN application if you absolutely have to go down this path and share why.

**Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners, and having at least 5 replicas of the dataset. No more than one replica should be stored with one SP ID, and if the data cannot leave a particular geographic boundary, then it is expected that replication will still happen across different locations (cities, datacenters, etc.). Each storage provider should not exceed 30% of the total datacap that the client was allocated and the storage provider should have published its public IP address. If you cannot follow these practices due to policy or any other issues, you may explain your case in the application and provide to the community what method you can do instead. These are recommendations and not strict rules that every client must follow.**

Regarding cases of abusing the program’s incentive structure, notaries should not be signing their own applications. For the program to work, each stakeholder will need to play their parts in a truthful manner.

Datasets that have been stored previously, may be allowed to be copied over time on chain. This can provide value to the network if it is a new team, a new datacenter, and a new geopolitical region. However, storage providers should not be storing more than 20% of the duplicated data. While same datasets may help the network, this should not be a reason for client’s to onboard the same exact dataset repeatedly, client’s should explicitly justify their reasoning on why the repeated dataset should be onboarded.

To help notaries more efficiently complete their due diligence process, clients should justify their reasoning of the amount of DataCap that you are applying for will help notaries with their due diligence process. Clients should explain how their dataset is useful for the network, and visible proof of the size of the data that is being onboarded.

**Comment by Filplus-govteam** [comment]
Hello @Designguy1 per the new guidelines https://github.com/filecoin-project/notary-governance/issues/922 for Open Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

This information will be reviewed by Fil+ Governance team to confirm validity toward the Fil+ guideline of a distributed storage plan and then the application will be triggered for notary review. Let us know if you have any questions.

**Comment by Designguy1** [comment]
Hello @Designguy1 we have submitted the form.

**Comment by Filplus-govteam** [comment]
Thank you for sharing SP details @Designguy1 

The following SP Entity info was shared: 
SP 1 f02252024   applecould New York
SP 2 f02238557  applecould  New York
SP 3 f02252111  TopHubpool Kuala Lumpur
SP 4 f02252023 Vpool Hong Kong
SP 5 f01422327 Huineng Tokyo

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 5PiB

**Expected weekly DataCap usage rate**
> 800TiB

**Client address**
>f1xjdq6fopvir2ikm4vcfrchhkwajxq57xj3kzzky

**Comment by a1991car** [comment]
It seems that the SPs are spread across multiple regions, and sending domain name emails. As the first round, I support

> We have sent an email, we are confirming the cooperation of sp, we will reply you tomorrow <img alt="WX20230713-154300@2x" width="1069" src="https://user-images.githubusercontent.com/138544716/253202719-2242e12e-dda8-4499-981b-0a0756673484.png">

**Comment by a1991car** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxbefd4ipwantwo3uny5oqfqpau37lxqfzuv4a4uiiuufhwiiji6 
#### Address 
> f1xjdq6fopvir2ikm4vcfrchhkwajxq57xj3kzzky
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1qnumecdypgrbaebtkdfjnwt5ndacadcuas3deiq
#### Id
> 3b678aaf-0bf4-47ff-b330-4074426b1bb7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxbefd4ipwantwo3uny5oqfqpau37lxqfzuv4a4uiiuufhwiiji6

**Comment by nj-steve** [comment]
hello , before I agree with you, I have some questions:
1.Have you learned how to seal data on the filecoin network？
2.How did you get in touch with these SPs？
3.Will you retrieve this data often in the future?

**Comment by Designguy1** [comment]
Yes, as you can see, it has been 1 month since we applied, before we applied for LDN, we studied for another half a year, now, we were ready. It took us a very long time to communicate with the SP, and finally we determined the SP to cooperate with. We communicated with the SP on multiple platforms, such as whatsapp, slack, TG, etc. Regarding the data, we may retrieve it once every 2-3 months, thank you!

**Comment by Filplus-govteam** [comment]
Just to re-confirm the process here @tmzxi - after storage is complete we will ask notaries to:

- Confirm SP IDs and locations match your plan
- Confirm data is retrievable and data sample matches said datasets

**Comment by Designguy1** [comment]
Thank you for your reminder, we will abide by the rules and wish Filecoin better and better.

**Comment by ipollo00** [comment]
> Just to re-confirm the process here @tmzxi - after storage is complete we will ask notaries to:
> 
> * Confirm SP IDs and locations match your plan
> * Confirm data is retrievable and data sample matches said datasets

Will do.

**Comment by ipollo00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmb3rbrmxiz6ofiorayi5xgyv4d4jqikcdy2zbjhshbsihn5o75i 
#### Address 
> f1xjdq6fopvir2ikm4vcfrchhkwajxq57xj3kzzky
#### Datacap Allocated
> 256.00TiB
#### Signer Address
> f1n5wlrrhoxpkgwij25xrtt7w7g2k3fhbthmdn6ri
#### Id
> 3b678aaf-0bf4-47ff-b330-4074426b1bb7
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmb3rbrmxiz6ofiorayi5xgyv4d4jqikcdy2zbjhshbsihn5o75i

**Comment by cryptowhizzard** [comment]
checker:manualTrigger

**Comment by cryptowhizzard** [comment]
@Filplus-govteam 

The datacap is spent, no deals visible yet on this client. Where did the CID checker bot hide them? :)

**Comment by Designguy1** [comment]
Hello, @cryptowhizzard @Filplus-govteam ，SP received the DC order, but it has not been packaged yet, wait 2 days, check again, thank you!

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by Designguy1** [comment]
checker:f1xjdq6fopvir2ikm4vcfrchhkwajxq57xj3kzzky

**Comment by Designguy1** [comment]
Bot delay, hope @xinaxu to help us, thank you!<img width="1022" alt="WX20230805-150259@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138544716/e408e13f-4ae2-4cd0-ae9c-42cb438282a5">
<img width="998" alt="WX20230805-150346@2x" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/1385447
![WechatIMG1032](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138544716/b8373c4f-2189-485a-b4c5-358065c44f1d)
![WechatIMG1031](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138544716/4ac6b4e3-2a4b-4470-8b51-1ce2225e7978)
![WechatIMG1030](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/138544716/a9240a88-fb0e-4b92-9da2-39a58ce07d8f)
16/4478e04f-8f87-49f6-bc40-77d4908bafd2">

**Comment by Designguy1** [comment]
checker:manualTrigger

**Comment by nj-steve** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea666pd2qk7ywnkl2smyqphxmmuyusglw2na74xmiorzfstvs2nry 
#### Address 
> f1xjdq6fopvir2ikm4vcfrchhkwajxq57xj3kzzky
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xx6555qijma7igpnjspyvdunc4vfxkawnpqy5ii
#### Id
> e3a7c594-8bd8-4e20-a5af-863f8b548602
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea666pd2qk7ywnkl2smyqphxmmuyusglw2na74xmiorzfstvs2nry

**Comment by nj-steve** [comment]
The reports look good.The client was cooperative with due diligence.

**Comment by junyaoren** [comment]
checker:manualTrigger

**Comment by junyaoren** [comment]
Not sure why the bot is doing only 1 or 2 checks. But the rate is good anyway. Also tried retrieval by myself, also successful with a decent transmitting rate. The distribution looks ok. No dispute. Will support for this round.

**Comment by junyaoren** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebg5txu53zkbmogopdjip74m3lgiol3aja6ix7lul7cy7hlqb2ico 
#### Address 
> f1xjdq6fopvir2ikm4vcfrchhkwajxq57xj3kzzky
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1xzff5xup63o5sygr2swp4zvcajg54lotliimdty
#### Id
> e3a7c594-8bd8-4e20-a5af-863f8b548602
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebg5txu53zkbmogopdjip74m3lgiol3aja6ix7lul7cy7hlqb2ico

**Comment by cryptowhizzard** [comment]
<img width="681" alt="Scherm­afbeelding 2023-08-08 om 20 24 51" src="https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/36404435/a0e2dda1-5937-4b15-92e2-811c22c85a53">

I can't get retrieval beyond this point.

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by Filplus-govteam** [comment]
Client self closed this. @raghavrmadya 

Let's make a note to monitor applications with these SPs, including f02252097
