### ISSUE TITLE
[DataCap Application] <> - <>

### ISSUE THREAD

**Issue by ryeturn** [filecoin-project/filecoin-plus-large-datasets#2210]

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2210.
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2210.
- How will the data be prepared? Please include tooling used and technical details
- If you are not preparing the data, who will prepare the data?  (Name and Business)
- Has this dataset been stored on Filecoin before? If so, why are you choosing to store it again?
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.

**Comment by Sunnyiscoming** [comment]
Have you complete 
### Datacap Request Trigger
**Total DataCap requested**
> 8PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi

**Comment by Sunnyiscoming** [comment]
### Datacap Request Trigger
**Total DataCap requested**
> 8PiB

**Expected weekly DataCap usage rate**
> 1PiB

**Client address**
>f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi

**Comment by herrehesse** [comment]
f02062851 USA
f02237006 England
f02122388 China
f01986229 Hubei,China

All miners are located in ASIA, no miner in englang. Please stop lying @Sunnyiscoming remove the allocation.

**Comment by Sunnyiscoming** [comment]
@tuyouhuwai Can you explain about that.

> f02062851 USA
> f02237006 England
> f02122388 China
> f01986229 Hubei,China
> 
> All miners are located in ASIA, no miner in England.

**Comment by woshidama323** [comment]
@Sunnyiscoming  GM
Wanna help with this application, Is that okay for this latest update from the owner of this application?
Thanks

**Comment by woshidama323** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaea2bd6ad646g4znfnjkykfuqjn6dfusxgonn45zfh2pj5zux2vq 
#### Address 
> f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f12tk3adljauwnd3hjbigpfxb7b7gdlj63p6afwtq
#### Id
> aa3a4c12-9706-445f-a3bf-66c36a530c05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaea2bd6ad646g4znfnjkykfuqjn6dfusxgonn45zfh2pj5zux2vq

**Comment by Chuangshi1** [comment]
Hope you can add more sps in the future and do the best work. Support for the first round.

**Comment by Chuangshi1** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamm7jzwejex4jqwen552xialhbwgtho3bfadc6zqk72nd5etn3fc 
#### Address 
> f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi
#### Datacap Allocated
> 409.59TiB
#### Signer Address
> f1mdk7s2vntzm6hu35yuo6vjubtrpfnb2awhgvrri
#### Id
> aa3a4c12-9706-445f-a3bf-66c36a530c05
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamm7jzwejex4jqwen552xialhbwgtho3bfadc6zqk72nd5etn3fc

**Comment by AlanGreaterheat** [comment]
checker:manualTrigger

**Comment by herrehesse** [comment]
Again, same notaries scamming and assisting abuse. @woshidama323 @Chuangshi1

Are we looking @raghavrmadya @kevzak @galen-mcandrew

**Comment by zcfil** [comment]
checker:manualTrigger

**Comment by tuyouuhuwai** [comment]
checker:manualTrigger

**Comment by tuyouuhuwai** [comment]
checker:manualTrigger

**Comment by Bitrise0111** [comment]
Check report shows healthy and we'd like to give a support. And we'll check it from time to time.

**Comment by Bitrise0111** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced3uh74sndz2rky35hzfefoi5gs66yqfrianqlgowq4ce6sqdgy3y 
#### Address 
> f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1nknj7ayq4o43czrtdoauggtwl43fbqatmqis3yy
#### Id
> 3b1fd2cf-0683-45b0-9c50-6b21f52f1c7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced3uh74sndz2rky35hzfefoi5gs66yqfrianqlgowq4ce6sqdgy3y

**Comment by laurarenpanda** [comment]
Only 3 SPs in this application seem too few according to FIL+ rules.
However, it has been through the 1st round, and this problem could be improved in the next round.
Please pay more attention to it.

**Comment by laurarenpanda** [comment]
## Request Proposed
Your Datacap Allocation Request has been proposed by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedm2m46swewlb7rckeppbfwcsldzkb4blakylgw2am46dftl4wrng 
#### Address 
> f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f1bp3tzp536edm7dodldceekzbsx7zcy7hdfg6uzq
#### Id
> 3b1fd2cf-0683-45b0-9c50-6b21f52f1c7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedm2m46swewlb7rckeppbfwcsldzkb4blakylgw2am46dftl4wrng

**Comment by SuperChaiChai** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauozu6buhaw5jxioc5qfl47vixpxcvbl2f2eint2df3pxseh7ado 
#### Address 
> f1dxdkahwsyptsc2ehiok6x2jf3kajrblhwrt7cfi
#### Datacap Allocated
> 512.00TiB
#### Signer Address
> f12mckci3omexgzoeosjvstcfxfe4vqw7owdia3da
#### Id
> 3b1fd2cf-0683-45b0-9c50-6b21f52f1c7e
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauozu6buhaw5jxioc5qfl47vixpxcvbl2f2eint2df3pxseh7ado

**Comment by herrehesse** [comment]
![Screenshot 2023-10-17 at 15 06 37](https://github.com/filecoin-project/filecoin-plus-large-datasets/assets/70132857/a35502f4-5e04-428f-9eac-b37b5ed9083e)

Fake distribution with VPN and abusive notaries signing. Can we PLEASE stop this behaviours and halt scammers?
@laurarenpanda @SuperChaiChai @Bitrise0111 you should be ashamed.

@Kevin-FF-USA @raghavrmadya @dkkapur @simonkim0515 Can anyone assist here please?

All self-dealing, can we remove the datacap immediately?

**Comment by tuyouuhuwai** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
checker:manualTrigger
