### ISSUE TITLE
[DataCap Application] Youyou Interactive (Beijing) Technology Co., Ltd.

### ISSUE THREAD

**Issue by HouserWang** [filecoin-project/filecoin-plus-large-datasets#2259]
### Data Owner Name 

Youyou Interactive (Beijing) Technology Co., Ltd.

### What is your role related to the dataset

Dataset Owner

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

http://www.yoyoo.ltd/#/game

### Social Media

```text
http://www.yoyoo.ltd/#/index
```

### Total amount of DataCap being requested

15PiB

### Expected size of single dataset (one copy)

1.5PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1shskrtkbfzgycly3ehmgp5v3xwtpgvtrr4gbzmi

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Youyou Interactive (Beijing) Technology Co., Ltd. is an Internet technology company focusing on original games. Founded in 2018, the company has always adhered to the purpose of "giving back to the market with high-quality games" and with the vision of "creating high-quality games that players love", it accurately positions and segments the game market; with gorgeous art style and scene special effects, standard rules and Excellent customer experience, bringing players an unprecedented gaming experience.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
It mainly stores game data, design data, marketing and promotion data, etc.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
Link: https://pan.baidu.com/s/11rMZEEsYl0I-GAQTJIcopA
Extraction code: ebar
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, South America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives

### How do you plan to choose storage providers

Slack, Filmine, Partners

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Sunnyiscoming** [comment]
- Could you send an email to filplus-app-review@fil.org with your official domain in order to confirm your identity? Email name should includes the issue id #2259.
- Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners.You should list Miner ID, Business Entity, Location of sps you will cooperate with.
- Per the https://github.com/filecoin-project/notary-governance/issues/922 for Open, Public Dataset applicants, please complete the following [Fil+ registration form](https://form.jotform.com/231862753015656) to identify yourself as the applicant and also please add the contact information of the SP entities you are working with to store copies of the data.
