### ISSUE TITLE
[DataCap Application] wanyou

### ISSUE THREAD

**Issue by awake2023** [filecoin-project/filecoin-plus-large-datasets#2305]
### Data Owner Name
wanyou

### What is your role related to the dataset
Data Preparer

### Data Owner Country/Region
China

### Data Owner Industry
Life Science / Healthcare

### Website
[http://www.lotuschanlun.com](http://www.lotuschanlun.com)

### Social Media
chanlun (twitter)

### Total amount of DataCap being requested
4.5 PiB

### Expected size of single dataset (one copy)
1000 PiB

### Number of replicas to store
1

### Weekly allocation of DataCap requested
150 TiB

### On-chain address for first allocation
f3qmo6gqk2mev7aevvxkd72s4tmwhfpqliht65jkf37dvpm2yuce6u5ehobqeiesgkxoznbwqebiup3jivqira

### Data Type of Application
Public, Open Dataset (Research/Non-Profit)

### Custom multisig
- [ ] Use Custom Multisig

### Identifier
n/a

### Share a brief history of your project and organization
kline, macd

### Is this project associated with other projects/ecosystem stakeholders?
No

### If answered yes, what are the other projects/ecosystem stakeholders
n/a

### Describe the data being stored onto Filecoin
data

### Where was the data currently stored in this dataset sourced from
Other

### If you answered "Other" in the previous question, enter the details here
data

### If you are a data preparer, what is your location (City and Country)
hongkong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
data

### If you are not preparing the data, who will prepare the data?  (Provide name and business)
n/a

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

### Please share a sample of the data
data

### Confirm that this is a public dataset that can be retrieved by anyone on the Network
Yes

### If you chose not to confirm, what was the reason
n/a

### What is the expected retrieval frequency for this data
Weekly

### For how long do you plan to keep this dataset stored on Filecoin
1 to 1.5 years

### In which geographies do you plan on making storage deals
Greater China

### How will you be distributing your data to storage providers
IPFS

### How do you plan to choose SP
Big Data Exchange

### If you answered "Others" in the previous question, what is the tool or platform you plan to use
n/a

### If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

### How do you plan to make deals to your storage providers
None

### If you answered "Others/custom tool" in the previous question, enter the details here
n/a

### Can you confirm that you will follow the Fil+ guideline
Yes

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Sunnyiscoming** [comment]
Share a brief history of your project and organization
kline, macd

Describe the data being stored onto Filecoin
data

Where was the data currently stored in this dataset sourced from
Other

If you answered "Other" in the previous question, enter the details here
data

If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
data

If you are not preparing the data, who will prepare the data? (Provide name and business)
n/a

Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
n/a

Please share a sample of the data
data

If you already have a list of storage providers to work with, fill out their names and provider IDs below
n/a

How do you plan to make deals to your storage providers
None

If you answered "Others/custom tool" in the previous question, enter the details here
n/a

The answers is too simple to understand. Please specify each answer in the application to let others have a knowledge of your project and approve it. 
Otherwise, you should specify the list of sps you will cooperate with. Best practice for storing large datasets includes ideally, storing it in 3 or more regions, with 4 or more storage provider operators or owners. Please provide ID, City, Country, Organization of each SP here.
