### ISSUE TITLE
[DataCap Application] NFTCommercial application

### ISSUE THREAD

**Issue by Nemophlist** [filecoin-project/filecoin-plus-large-datasets#495]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: NFTmoon
- Website / Social Media: https://nftbomb.org
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 3PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation: f1rhpecsedmbwdmeqnzxwtc3j5euqx3gqbyf6umuy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
NFTBmob is the first open ecosystem that integrates the NFT contract protocol layer and application layer. 
In simple terms, NFTBomb is an NFT+DeFi+BSC ecosystem of NFT protocols. 
The core vision of NFTBomb is to nurture and accelerate creative NFT protocols in terms of liquidity and user adoption. 
NFTBomb aims to bring one-stop NFT+DeFi experience on BSC.
https://nftbomb-1.gitbook.io/nftbomb/
```

What is the primary source of funding for this project?
```
We are a self-funded company. We trade our own capital at our own risk

```
What other projects/ecosystem stakeholders is this project associated with?
```
zkimart NFT : http://zkimart.online/

```
## Use-case details

Describe the data being stored onto Filecoin
```
The data to be stored: mainly for storing NFT data and the records 
and interaction data generated by customers in the process of using NFTBomb.
```

Where was the data in this dataset sourced from?
```
Mainly from the storage data of the business line and the application data of the cooperation project
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
https://nftbomb.org/metadata/top10.zip

```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
we confirm that dataset is publicly retrievable.
```

What is the expected retrieval frequency for this data?
```
A month or three months or a quarter
```

For how long do you plan to keep this dataset stored on Filecoin?
```
Two years or more
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Asia
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Both online and offline small-capacity data can be transmitted online
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We hope to find some storage providers in Asia through slack. The purpose of applying for datacap is to hope that more storage providers can finish our deals.
```

How will you be distributing deals across storage providers?
```
We will choose cheaper miners preferentially.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes. We will make deals since we apply successfully.
```

**Comment by Sunnyiscoming** [comment]
@bjchend Is this issue the same as https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/469 and https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/493?

**Comment by Nemophlist** [comment]
yes .

**Comment by Nemophlist** [comment]
Has anyone taken care of it?

**Comment by Nemophlist** [comment]
No one responded? @galen-mcandrew @

**Comment by Sunnyiscoming** [comment]
@Nemophlist  As mentioned in #469 

> For how long do you plan to keep this dataset stored on Filecoin?
> 
> 1. customer private data needs to be stored for more than 3 years, maybe longer
> 2. public data is stored for at least 2 years

Whether you will store private data?

There are some comments on https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/469 and https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/493 without any reply.

**Comment by Sunnyiscoming** [comment]
You can close #493 directly.

**Comment by raghavrmadya** [comment]
Closing this out for now since multiple issues have been opened. Please open up a new application if still relevant. 
In the new application, please provide more clarity on your DataCap allocation plan. We require geographic diversity and mentioning only Asia is not enough. We need to have a more concrete plan. Are there SPs already waiting for DataCap on your end? Please provide as much information as possible on SP distribution and how you plan to move the data to SPs.

**Comment by Nemophlist** [comment]
The reason for submitting multiple applications is:  that after we submitted an application,we did not get feedback for a long time. We are not clear whether the notary has seen the application, so we will submit it every once in a while, hoping to get the attention and feedback of the notary.

 @raghavrmadya According to the notary's feedback, we will re-submit a more detailed application and hope the notary can review it.

thanks.  @Sunnyiscoming

**Comment by Nemophlist** [comment]
> 您可以直接关闭 #493。

yes，Unless the user logs out, the user's private data, user's usage data and similar data will always be stored.

**Comment by Nemophlist** [comment]
> @Nemophlist如 #469 中所述
> 
> > 您计划将此数据集存储在Filecoin上多长时间？
> > 
> > 1. 客户私人数据需要存储3年以上，也许更长
> > 2. 公共数据至少存储 2 年
> 
> 您是否将存储私有数据？
> 
> 对#469和#493有一些评论，没有任何回复。

Yes, the user's private data, user usage data, and similar data will always be stored unless the user logs out.

**Comment by Nemophlist** [comment]
@raghavrmadya @Sunnyiscoming According to the requirements, I have resubmitted the application. Please timely approve it. If you have any questions, please contact me in time

**Comment by Sunnyiscoming** [comment]
@Nemophlist  Hi,
1.There are some comments on https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/469 and https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/493 without any reply. It can not be pushed without any reply.
2.LDN is suit for open and meaningful data. If you will store private data, as Deep mentioned https://github.com/filecoin-project/notary-governance/issues/514, you will need to find notaries that can support your application since it includes private enterprise data.

You will need to follow a process similar to https://github.com/filecoin-project/notary-governance/issues/489. This means:

Find notaries that can support your application. You can do this best in Slack, #fil-plus or #fil-plus-application-review
Once you have them, make an issue in the Notary Governance repo, similar to https://github.com/filecoin-project/notary-governance/issues/489, stating your plan and the notaries that can support your request
FIL+ governance can then set up a custom LDN for this with those notaries and proceed from there
These additional steps are required to ensure that notaries can establish a relationship with you and back you as a trustworthy client, since the usual deal data will be encrypted and not open to access for the community to validate your actions on chain after DataCap has been used.

**Comment by Nemophlist** [comment]
I am very glad to receive your reply

Nftbom is a social NFT trading platform

The data to be stored consists of two aspects, public data and private data of registered users

Public data: Shared and retrieved by all users accessing nftbom.com

Private data of registered users, mainly including (private data of registered users, and personal data of registered users)

Private data of registered users, such as user name, password, gender, age, and contact information, can only be accessed and used by registered users

Personal data of registered users, mainly for social purposes, is available for retrieval and use by all registered users

I use Github as an example. For example, users' hobbies, passwords, gender, etc. on Github are private data and cannot be retrieved

Users' names and followers belong to public data, which can be used to retrieve

Nftbom is a platform that wants to store this data on Filecoin to provide better performance, improve data security, etc

We hereby apply for the data encapsulation quota @Sunnyiscoming

**Comment by Sunnyiscoming** [comment]
As I mentioned above.
You should find notaries that can support your application if you want to store some data belongs to private data. Or you can just store public data in LDN and adjust DataCap requested according to the public data you have at present.

**Comment by Nemophlist** [comment]
Thank you for your reply

According to your requirements, we make the following adjustments

1. Our private data will continue to be stored on Amazon Cloud

2. We store public data in LDN

3. We reduced the requirement for DataCap by 50% to 1.5Pib @Sunnyiscoming

**Comment by raghavrmadya** [comment]
@Nemophlist , thanks for being transparent and answering the questions. As you are requesting the reduced amount of DataCap, I'd ask you to open a new application and link this application and any other relevant discussion so that we can move quickly. I look forward to your new application with the updated information and looking forward to having you on the Filecoin network. 

Thanks.
