### ISSUE TITLE
[DataCap Application]Pioneer Futures

### ISSUE THREAD

**Issue by nicechain** [filecoin-project/filecoin-plus-large-datasets#965]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name: Pioneer Futures
- Website / Social Media:https://www.xfqh.cn/
- Total amount of DataCap being requested (between 500 TiB and 5 PiB):5PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB):100TiB
- On-chain address for first allocation:f1ddkeo5iqon5zgnv2sg4n2yt2tibxjwi4mvnqsza

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Founed in March 1993, Pioneer Futures Co.Ltd is one of the earliest futures companies established in China and is a member of the Shanghai Futures Exchange (Member No. 0138), Shanghai International Energy Exchange (Member No. 8138), Dalian Commodity Exchange (Member No. 0075), Zhengzhou Commodity Exchange (Member No. 0215) and China Financial Futures Exchange (Clearing Member, Member No. 0325). The company has a registered capital of RMB 15000.00 million. Legal representative Li Junwei, registered in Luohu District, Shenzhen, with 10 branches including Shanghai branch, Zhejiang Branch, Fujian branch, Guangzhou branch, Jiangsu branch, Dalian sales Department, Jinxiang sales Department, Fuzhou Sales Department, Hangzhou Wenyi Road Sales Department and Changzhou Sales Department. 
```

What is the primary source of funding for this project?
```
Company income.
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other project/ecosystems stakeholders.
```

## Use-case details

Describe the data being stored onto Filecoin
```
Market historical data, trading data
```

Where was the data in this dataset sourced from?
```
Company data
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Yes
https://1drv.ms/u/s!AvAsfKS71N_sapNKEYwpCayAH4w?e=f25uhl
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Confirm, those are public historical trading data.
```

What is the expected retrieval frequency for this data?
```
Once per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
For 18 to 24 months
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
Global.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
We hope it’s online transfer.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
 We want to choose well-funded storage providers that understands how to deal with our data type .
```

How will you be distributing deals across storage providers?
```
 We plan to find more storage providers as we can and average the data. 
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
 We are ready to work with SPs on the data.
```

**Comment by Sunnyiscoming** [comment]
![image](https://user-images.githubusercontent.com/105098820/203003056-e0ed5ce1-6c89-44c7-a6e6-2a031adc8dc8.png)
It seems that I have no right to check it. Please check it.
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by nicechain** [comment]
> ![image](https://user-images.githubusercontent.com/105098820/203003056-e0ed5ce1-6c89-44c7-a6e6-2a031adc8dc8.png) It seems that I have no right to check it. Please check it. What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

Hi @Sunnyiscoming , i have tested again, seems IE and windows edge having issue open the link, kindly help to verify again with  another browser like chrome or firefox. I am the staff from IT department, and we have contacted with serval SPs which are f033189, f0145162, f01579921, f017665, f01315486.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

>f1ddkeo5iqon5zgnv2sg4n2yt2tibxjwi4mvnqsza

**Comment by stcouldlisa** [comment]
You should send a confirmation email to filplus-app-review@fil.org using the email address of your company domain. And Email name should contain Issue ID #965

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Hey @nicechain , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by Sunnyiscoming** [comment]
No KYC email received.

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230232885049356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
