### ISSUE TITLE
[DataCap Application] Eloam Technology Co.Ltd

### ISSUE THREAD

**Issue by three3b** [filecoin-project/filecoin-plus-large-datasets#998]
# Large Dataset Notary Application

To apply for DataCap to onboard your dataset to Filecoin, please fill out the following.

## Core Information
- Organization Name:  Shenzhen Eloam Technology Co.Ltd
- Website / Social Media: www.eloam.cn
- Total amount of DataCap being requested (between 500 TiB and 5 PiB): 5 PiB
- Weekly allocation of DataCap requested (usually between 1-100TiB): 100TiB
- On-chain address for first allocation: f1e5j2jdkht6sz4vlial7oqu6ayg6tk3fha37lddy

_Please respond to the questions below by replacing the text saying "Please answer here". Include as much detail as you can in your answer._

## Project details

Share a brief history of your project and organization.
```
Shenzhen Eloam Technology Co.Ltd is the No.1 high speed document scanner, document camera and panoramic camera supplier in china, which is a professional IT peripherals, School, Home & Office Products manufacturer providing customized optimal manufacturing services and sophisticated products. We keep adopting advanced technology incorporated with concepts of environmental protection, ergonomics and user’s behavior to develop innovative and high-quality products worldwide at affordable competitive prices.
Founded in 2005, Eloam Technology has been devoting itself to researching and developing digital video technology. Its camera series has gradually won a leading position in the computer market.
```

What is the primary source of funding for this project?
```
Company itself
```

What other projects/ecosystem stakeholders is this project associated with?
```
No other parties.
```

## Use-case details

Describe the data being stored onto Filecoin
```
- Software, firmware (including different device models and recusive software/firmware versions) 
- Guiding videos
- Promotion videos 
- User manuals, 
```

Where was the data in this dataset sourced from?
```
All data are generated by our company.
```

Can you share a sample of the data? A link to a file, an image, a table, etc., are good ways to do this. 
```
Sure. Kindly refer to below link.

https://1drv.ms/u/s!Av7H2EJRxFShat-e-uci2iWuKu0?e=UZUpd3
```
        
Confirm that this is a public dataset that can be retrieved by anyone on the Network (i.e., no specific permissions or access rights are required to view the data).
```
Yes, we confirm.
```

What is the expected retrieval frequency for this data?
```
Multiple times per year.
```

For how long do you plan to keep this dataset stored on Filecoin?
```
36 Months.
```

## DataCap allocation plan

In which geographies (countries, regions) do you plan on making storage deals?
```
We prefer Asia region, easier for us to transfer data offline.
```

How will you be distributing your data to storage providers? Is there an offline data transfer process?
```
Due to bandwidth limitation, offiline transfer is preferred.
```

How do you plan on choosing the storage providers with whom you will be making deals? This should include a plan to ensure the data is retrievable in the future both by you and others.
```
We are not familier with the providers, so we are getting in touch with the possible SPs now. Data security is the first concern, we are trying to get some qualified storage supplier and store multiple copies of our data.
```

How will you be distributing deals across storage providers?
```
We will commit to the rules, distribute the deal to at least 4 to 5 SPs with each no more than 25%.
```

Do you have the resources/funding to start making deals as soon as you receive DataCap? What support from the community would help you onboard onto Filecoin?
```
Yes, we hope to store our data as soon as possible.
```

**Comment by Sunnyiscoming** [comment]
Can you explain your data composition and provide sufficient data samples separately? How many copies will you store?
What's the relationship between you and the organization?
Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

**Comment by three3b** [comment]
> Can you explain your data composition and provide sufficient data samples separately? How many copies will you store? What's the relationship between you and the organization? Can you provide more detailed information about other storage providers participated in this program, such as you can list SPs you have contacted with at present?

@Sunnyiscoming 
Please check this link for data samples, https://1drv.ms/u/s!Av7H2EJRxFShat-e-uci2iWuKu0?e=UZUpd3
we would like to store 8 copies of our total data.
I am the R&D team lead of our company and so far SPs we contacted are f01162221, f01340400, f01097957, f01780915, f01275559.
Hope can get back from you soon.

**Comment by simonkim0515** [comment]
### Datacap Request Trigger
**Total DataCap requested**

> 5PiB

**Expected weekly DataCap usage rate**

> 100TiB

**Client address**

> f1e5j2jdkht6sz4vlial7oqu6ayg6tk3fha37lddy

**Comment by stcouldlisa** [comment]
You should send a confirmation email to filplus-app-review@fil.org using the email address of your company domain. And Email name should contain Issue ID #998

**Comment by herrehesse** [comment]
Dear Applicant,

Due to the increased amount of erroneous/wrong Filecoin+ data recently, on behalf of the entire community, we feel compelled to go deeper into datacap requests. Hereby to ensure that the overall value of the Filecoin network and Filecoin+ program increases and is not abused.

Please answer the questions below as comprehensively as possible.

**Customer data**

- Could you demonstrate exactly how and to what extent customer contact occurred? 

We expect that for the onboarding of customers with the scale of an LDN there would have been at least multiple email and perhaps several chat conversations preceding it. A single email with an agreement does not qualify here.

- Did the customer specify the amount of data involved in this relevant correspondence?

- Why does the customer in question want to use the Filecoin+ program? 

_Should this only be soley for acquiring datacap this is of course **out of the question**. The customer must have a legitimate reason for wanting to use the Filecoin+ program which is intended as a program to store useful and public datasets on the network._ 

- Why is the customer data considered Filecoin+ eligible?

_(As an intermediate solution Filecoin offers the FIL-E program or the glif.io website for business datasets that do not meet the requirements for a Filecoin+ dataset)_


**Files and Processing**

- Could you please demonstrate to us how you envision processing and transporting the customer data in question to any location for preparation?
- Would you demonstrate to us that the customer, the preparer and the intended storage providers all have adequate bandwidth to process the set with its corresponding size?
- Would you tell us how the data set preparer takes into account the prevention of duplicates in order to prevent data cap abuse?


Hopefully you understand the caution the overall community has for onboarding the wrong data. We understand the increased need for Filecoin+, however, we must not allow the program to be misused. Everything depends on a valuable and useful network, let's do our best to make this happen. Together.

**Comment by Sunnyiscoming** [comment]
Hey @three3b , if you still want to apply for datacap, you can ask notaries to do client due diligence in slack channel. https://app.slack.com/client/TEHTVS1L6/C036JKD8NVA/thread/C03BG1MNQ4T-1673888660.823499

**Comment by cryptowhizzard** [comment]
Dear applicant,

Thank you for applying for datacap. As Filecoin[ FIL+ notary](https://github.com/filecoin-project/notary-governance/tree/main/notaries) i am screening your application and conducting due diligence.

Looking at your application i have some questions:
As you are brand new on Github and have no history of past applications it seems to me that applying for 5PB of datacap is a lot. One needs comprehensive knowledge of Filecoin, packing of data, distribution of data and all it's requirements coming with it. Are you brand new in the Filecoin space or have you applied for datacap in the past on different Github account names?

Can you show us visible proof of the size of your data and the storage systems you have there?

As last question i would like you to fill out [this form](https://form.jotform.com/230337462961356) to provide us with the necessary information to make a educated decision on your LDN request if we would like to support it.

Thanks!
